### ISSUE TITLE
Release 2019.01 - RC3

### ISSUE THREAD

**Issue by aabadie** [RIOT-OS/Release-Specs#105]
This issue lists the status of all tests for the [Release Candidate 3 of the 2019.01](https://github.com/RIOT-OS/RIOT/releases/tag/2019.01-RC3) release.

Specs tested:
- [x] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/01-ci/01-ci.md)
  - [x] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/01-ci/01-ci.md#task-01---compile-test)
  - [x] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/01-ci/01-ci.md#task-02---unittests-on-native) @aabadie 
  - [x] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/01-ci/01-ci.md#task-03---unittests-on-native-separated) @aabadie 
  - [x] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3) @aabadie 
- [x] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/02-tests/02-tests.md)
  - [x] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/02-tests/02-tests.md#task-01---all-tests-on-native) @aabadie 
  - [x] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [x] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md) @aabadie 
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native)
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native)
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
  - [x] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-04---icmpv6-stress-test-on-native-1-hour)
  - [x] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/4b7c854856b90ff52c7006e80366fb6ab28acc14/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
- [x] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md) @aabadie 
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03---icmpv6-echo-with-large-payload)
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [x] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [x] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [x] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-09---icmpv6-stress-test-on-iotlab-m3)
- [x] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/05-single-hop-route/05-single-hop-route.md) @aabadie 
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [x] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/06-single-hop-udp/06-single-hop-udp.md) @aabadie 
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3)
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression)
  - [x] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/06-single-hop-udp/06-single-hop-udp.md#task-03---udp-on-native-non-existent-neighbor)
  - [x] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/06-single-hop-udp/06-single-hop-udp.md#task-04---udp-on-iotlab-m3-non-existent-neighbor)
- [x] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/07-multi-hop/example_test_guide.md)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/07-multi-hop/example_test_guide.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/07-multi-hop/example_test_guide.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/07-multi-hop/example_test_guide.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/07-multi-hop/example_test_guide.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
- [x] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [x] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [x] [Task #03 - ICMPv6 echo between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-03---icmpv6-echo-between-iotlab-m3-and-contiki) @miri64
  - [x] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [x] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router) @jia200x
  - [x] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router) @jia200x
  - [x] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload) @jia200x
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3) @miri64
  - [x] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3) @jia200x
  - [x] [Task #10 - UDP between lwIP and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3) @miri64
- [x] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/09-coap/coap.md) @kb2ma
  - [x] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/09-coap/coap.md#task-01---cord-endpoint)
  - [x] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/09-coap/coap.md#task-02---confirmable-retries)
  - [x] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/09-coap/coap.md#task-03---block1)
  - [x] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/09-coap/coap.md#task-04---block2)
  - [x] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/09-coap/coap.md#task-05---observe-registration-and-notification)
- [x] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md) @miri64
  - [x] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-01---destination-unreachable---no-route-to-destination)
  - [x] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [x] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-03---destination-unreachable---address-unreachable-target-node-address)
  - [x] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss)
  - [x] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-05---destination-unreachable---port-unreachable)
  - [x] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-06---destination-unreachable---port-unreachable-large-payload)
  - [x] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-07---packet-too-big)
  - [x] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [x] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-09---parameter-problem---erroneous-header-field-encountered)
  - [x] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/10-icmpv6-error/10-icmpv6-error.md#task-10---ipv6-in-ipv6-encapsulation)
- [x] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/11-lorawan/11-lorawan.md) @jia200x
  - [x] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/11-lorawan/11-lorawan.md#task-01---lorawan-example)
  - [x] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/11-lorawan/11-lorawan.md#task-02---otaa-join-procedure)
  - [x] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/11-lorawan/11-lorawan.md#task-03---abp-join-procedure)
  - [x] [Task #03 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/11-lorawan/11-lorawan.md#task-03---lorawan-device-parameters-persistence)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/6df7e05d72bac7f00aac28b71d995528660ce940/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by miri64** [comment]
@aabadie did you remove 3.5 intentionally?

**Comment by aabadie** [comment]
> did you remove 3.5 intentionally?

No, maybe another mistake with issue not being synchronized ? Can you add it again ?

**Comment by miri64** [comment]
Will do

**Comment by aabadie** [comment]
Thanks, it's here again :)

**Comment by miri64** [comment]
Just to make sure I cherry-picked https://github.com/RIOT-OS/RIOT/pull/10908 onto `2019.01-RC3` again and ran it. Still works :+1:

**Comment by kb2ma** [comment]
CoAP still looking good.

**Comment by aabadie** [comment]
Tasks 04 passed (skipped 4.5 and 4.6 because I don't have a 'remote')

**Comment by miri64** [comment]
Can't test 8.2 atm. I don't have my Laptop with me and the back-up I'm usually using for that case is not in house this week :-(.

**Comment by aabadie** [comment]
I could check 8.2 using the RPI/6LowPAN which is in my office (and hosting http://riot-demo.inria.fr). It works :)

**Comment by miri64** [comment]
:+1: I was surprised to see the check mark set and unsure I set it accidentally ^^

**Comment by miri64** [comment]
Then you should also be able to do 8.4. Since we don't have small enough prefixes here to expose the WPAN to the Internet I usually just ping a global address of the Raspberry Pi that is not the `wpan0` interface's address. That should be proof that forwarding on the Linux side works.

**Comment by aabadie** [comment]
>  I usually just ping a global address of the Raspberry Pi that is not the `wpan0` interface's address

Thanks for the tip, I was trying to ping google DNS without success and tried looking into ipforwarding stuff, still without success...

But it works with global ipv6 of the PI :+1:

**Comment by aabadie** [comment]
The native stress tests passed smoothly

**Comment by aabadie** [comment]
@jia200x, I'm sorry I completed tasks 11 (lorawan) because I want to check the release specs fast.

**Comment by jia200x** [comment]
> I'm sorry I completed tasks 11 (lorawan) because I want to check the release specs fast.
No problem.

I will have some time to run the tests I marked by tomorrow morning.

**Comment by aabadie** [comment]
We are just missing tasks 1.1, 7.x and 8.5-10. @cgundogan, @miri64, are you planning to perform the multi-hop checks soonish ? @jia200x, let me know when you are done with the interop tests. For 1.1, can we trust Murdock? Because I won't have the time to run it today.

**Comment by miri64** [comment]
> @cgundogan, @miri64, are you planning to perform the multi-hop checks soonish ?

I didn't plan to, but can do.

**Comment by miri64** [comment]
> I didn't plan to, but can do.

BTW the links above refer to the wrong document somehow.

**Comment by miri64** [comment]
> > @cgundogan, @miri64, are you planning to perform the multi-hop checks soonish ?
> 
> I didn't plan to, but can do.

Done

**Comment by miri64** [comment]
Also found a bug in the example test guide (see https://github.com/RIOT-OS/Release-Specs/pull/108).

**Comment by miri64** [comment]
> For 1.1, can we trust Murdock?

You are the release manager, so you decide. However, I ran compile tests for RC1 on my machine, so I was able to just compile a subset of some applications that were definitely touched by the changes since RC1:

```
$ git diff --stat  2019.01-RC1..2019.01-RC3
 core/msg.c                                                         |   1 +
 cpu/esp8266/Makefile.dep                                           |   2 +-
 cpu/esp8266/esp-wifi/esp_wifi_netdev.c                             | 178 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 cpu/esp8266/esp-wifi/esp_wifi_netdev.h                             |   3 +-
 cpu/esp8266/sdk/lwip.c                                             | 213 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 cpu/native/native_cpu.c                                            |   5 ++--
 cpu/saml21/include/periph_cpu.h                                    |  33 ++++++++++++++++++++++
 drivers/w5100/w5100.c                                              |  45 +++++++++++++++++++----------
 examples/lorawan/main.c                                            |  12 ++++++--
 pkg/semtech-loramac/contrib/semtech_loramac.c                      |  28 ++++++++++++------
 pkg/semtech-loramac/include/semtech_loramac.h                      |  14 +++++++--
 sys/include/net/eui48.h                                            |  31 ++++++++++++++------
 sys/include/net/gnrc/netif/internal.h                              |  59 ++++++++++++++++++++++++++++++++++++++
 sys/net/application_layer/dns/dns.c                                |  12 ++++++--
 sys/net/gnrc/netif/gnrc_netif_device_type.c                        | 125 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 sys/net/gnrc/network_layer/icmpv6/echo/gnrc_icmpv6_echo.c          |   6 ++++
 sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c                     |   9 +++---
 sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.c                    |  26 ++++++-----------
 sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.h                    |  37 ++++++++++++++++++++++++
 sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c                |  11 ++++++--
 sys/net/gnrc/network_layer/ipv6/nib/nib.c                          |  61 +++++++++++++++++++++++++--------------
 sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c    |   5 +++-
 sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c                        |  29 +++++++++++++++----
 sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c                    |   1 +
 sys/shell/commands/sc_gnrc_ipv6_nib.c                              |  37 ++++++++++++++++++++++++
 tests/periph_eeprom/main.c                                         |  18 +++++++-----
 tests/pkg_semtech-loramac/main.c                                   |  14 +++++++--
 tests/unittests/tests-gnrc_ipv6_nib/tests-gnrc_ipv6_nib-internal.c |  93 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 28 files changed, 885 insertions(+), 223 deletions(-)
```

According to that

```
for app in examples/gnrc_networking examples/lorawan tests/gnrc_tcp_server tests/periph_eeprom tests/periph_gpio tests/pkg_semtech-loramac tests/unittests;
do
    CCACHE_MAXSIZE=20G CCACHE=ccache make -C ${app} buildtest
done
```

Should suffice (it appears there are no applications that include `esp_wifi` or `w5100` per default) to spot any compile errors that came from those changes. I currently run those. They should most likely be done after lunch.

**Comment by aabadie** [comment]
> You are the release manager, so you decide

I decide that it is ok :)

**Comment by miri64** [comment]
Ok, but nevertheless I ran my sample set and can report, that nothing is broken ;-).

**Comment by miri64** [comment]
I finished 8.8 and 8.10. @jia200x any reason you skipped those?

**Comment by aabadie** [comment]
Thanks, so it seems that we are all set on this side :)

**Comment by aabadie** [comment]
Regarding task 99, the `compile_and_test_one_board` was run on iotlab-m3/samr21-xpro/nrf51dk/nrf52dk/b-l475e-iot01a.

The results are listed [here](https://ci.inria.fr/iotlab-os-ci/job/test-job/59/testReport/)

**Comment by jia200x** [comment]
> I finished 8.8 and 8.10. @jia200x any reason you skipped those?

I spent a lot of time fixing an Arch issue with 8.5. Then, I just did 8.8 before lunch

**Comment by jia200x** [comment]
Release 2019.01 is out there. Closing this one ;)
