### ISSUE TITLE
Release 2019.07 - RC2

### ISSUE THREAD

**Issue by MrKevinWeiss** [RIOT-OS/Release-Specs#133]
This issue lists the status of all tests for the [Release Candidate 2 of the 2019.07](https://github.com/RIOT-OS/RIOT/releases/tag/2019.07-RC2) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/01-ci/01-ci.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/01-ci/01-ci.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/01-ci/01-ci.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/01-ci/01-ci.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/02-tests/02-tests.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [ ] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native)
  - [ ] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native)
  - [ ] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
  - [ ] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-04---icmpv6-stress-test-on-native-1-hour)
  - [ ] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md)
  - [ ] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [ ] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [ ] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-03---icmpv6-echo-with-large-payload)
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/04-single-hop-6lowpan-icmp/example_test_guide.md#task-09---icmpv6-stress-test-on-iotlab-m3)
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/05-single-hop-route/05-single-hop-route.md)
  - [ ] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [ ] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [ ] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [ ] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md)
  - [ ] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3)
  - [ ] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression)
  - [ ] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md#task-03---udp-on-native-non-existent-neighbor)
  - [ ] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md#task-04---udp-on-iotlab-m3-non-existent-neighbor)
  - [ ] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md#task-05---empty-udp-on-native)
  - [ ] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/06-single-hop-udp/06-single-hop-udp.md#task-06---empty-udp-on-iotlab-m3)
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/07-multi-hop/example_test_guide.md)
  - [ ] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/07-multi-hop/example_test_guide.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/07-multi-hop/example_test_guide.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/07-multi-hop/example_test_guide.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/07-multi-hop/example_test_guide.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md)
  - [ ] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [x] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan) @smlng 
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [x] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan) @smlng 
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [ ] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)
  - [ ] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3)
  - [ ] [Task #10 - UDP between lwIP and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/09-coap/coap.md)
  - [ ] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/09-coap/coap.md#task-01---cord-endpoint)
  - [ ] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/09-coap/coap.md#task-02---confirmable-retries)
  - [ ] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/09-coap/coap.md#task-03---block1)
  - [ ] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/09-coap/coap.md#task-04---block2)
  - [ ] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/09-coap/coap.md#task-05---observe-registration-and-notification)
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md)
  - [ ] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-01---destination-unreachable---no-route-to-destination)
  - [ ] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [ ] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-03---destination-unreachable---address-unreachable-target-node-address)
  - [ ] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss)
  - [ ] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-05---destination-unreachable---port-unreachable)
  - [ ] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-06---destination-unreachable---port-unreachable-large-payload)
  - [ ] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-07---packet-too-big)
  - [ ] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [ ] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-09---parameter-problem---erroneous-header-field-encountered)
  - [ ] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/10-icmpv6-error/10-icmpv6-error.md#task-10---ipv6-in-ipv6-encapsulation)
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/11-lorawan/11-lorawan.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/11-lorawan/11-lorawan.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/11-lorawan/11-lorawan.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/11-lorawan/11-lorawan.md#task-03---abp-join-procedure)
  - [ ] [Task #03 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/11-lorawan/11-lorawan.md#task-03---lorawan-device-parameters-persistence)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/80799c5b48f9801f1f5ee55b31815849a9c50fdc/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by MrKevinWeiss** [comment]
@miri64 @cladmi @fjmolinas @josephnoir @leandrolanzieri @smlng @jcarrano 
RC2 is out and ready for testing.  Hopefully this one will be the one.  The big fixes were mostly on the tests and lorawan so it would be good to focus on that.

Thanks again for all the help testing this stuff!

**Comment by fjmolinas** [comment]
@MrKevinWeiss I found a problem in the doc and debug info for  `examples/lorawan`, https://github.com/RIOT-OS/RIOT/pull/11869 addresses it. The return code changed, so although the message is correctly sent the debug info says it failed. Maybe that needs to be back-ported too, the functionality is not affected but the doc is wrong.

**Comment by smlng** [comment]
interop 8 task 2 and 4 still work as reported for RC1

**Comment by MrKevinWeiss** [comment]
Many thanks.  We are going RC3 with 11869 in but I think we don't need to retest a lot.

**Comment by MrKevinWeiss** [comment]
Closing in favor of #134
