### ISSUE TITLE
02-tests Release 2015.12 - RC3

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/Release-Specs#14]
Let's collect the test results for **02-tests** here, task by task.

**Comment by BytesGalore** [comment]
### Task 01 - Execute all tests on `native` and check their output.

Feel free to edit this list.

* [x] bitarithm_timings
* [x] bloom_bytes
* [x] coap
* [ ] **conn_ip (<- just built and looked into the shell)**
* [x] cpp11_condition_variable
* [x] cpp11_mutex
* [x] cpp11_thread

**Skipped all driver_***
* [x] fault_handler
* [x] **float (<- don't understand if only `-` printed is correct)**
* [x] fmt_print
* [x] irq
* [ ] **libfixmath (<- needs SVN)**
* [ ] **libfixmath_unittests (<- this guy too)**
* [ ] **malloc (<- not tested fully haven't been patient enough to let it finish yet)**
* [x] minimal
* [x] msg_send_receive
* [x] mutex_unlock_and_sleep
* [x] nhdp

**Skipped all preiph***
* [x] **pipe (<- dont know if the output is correct)**
* [ ] **pkg_cmsis-dsp (<- fails to build for native, correct?)**
* [x] pkg_micro-ecc (<- takes a lot of time to finish ~2h)
* [x] posix_semaphore
* [x] posix_sleep
* [x] pthread
* [x] pthread_barrier
* [x] pthread_cleanup
* [x] pthread_condition_variable
* [x] pthread_cooperation
* [x] pthread_rwlock
* [x] pthread_tls
* [x] sched_testing
* [x] shell
* [x] sizeof_tcb
* [ ] **slip (<- fails to build for native, i.e. correct )**
* [x] struct_tm_utility
* [x] thread_basic
* [x] thread_cooperation
* [x] thread_exit
* [x] thread_msg
* [x] thread_msg_avail
* [x] thread_msg_block_wo_queue
* [x] thread_msg_block_w_queue
* [x] thread_msg_seq
* [x] unittests
* [x] vtimer_msg
* [x] vtimer_msg_diff
* [x] warn_conflict
* [x] xtimer_drift
* [ ] **xtimer_hang (<- fails on `make term`)** !!!!!!!
* [x] xtimer_msg
* [ ] xtimer_msg_receive_timeout
* [x] xtimer_remove
* [x] xtimer_reset
* [ ] **xtimer_shift_on_compare (<- fails to build for native, i.e. correct)**
* [x] xtimer_usleep_until
* [ ] **zep (<- untested yet)**

**Comment by BytesGalore** [comment]
### Task 02 - Perform a subset of tests on `iotlab-m3` node.

Feel free to edit this (currently empty) list.

**Comment by gebart** [comment]
> pkg_cmsis-dsp (<- fails to build for native, correct?)

pkg_cmsis-dsp should only be buildable for Cortex platforms. CMSIS-DSP is supplied by ARM for use with Cortex-M0,3,4,7 only and contains quite a lot of inline (Thumb2) assembly.

**Comment by BytesGalore** [comment]
@gebart thx for clarification

**Comment by authmillenon** [comment]
Superseded by #17
