### ISSUE TITLE
Release 2020.01 - RC3

### ISSUE THREAD

**Issue by fjmolinas** [RIOT-OS/Release-Specs#148]
This issue lists the status of all tests for the [Release Candidate 3 of the 2020.01](https://github.com/RIOT-OS/RIOT/releases/tag/2020.01-RC3) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/01-ci/01-ci.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/01-ci/01-ci.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/01-ci/01-ci.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/01-ci/01-ci.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/02-tests/02-tests.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [ ] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native)
  - [ ] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native)
  - [ ] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
  - [ ] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-04---icmpv6-stress-test-on-native-1-hour)
  - [ ] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
  - [ ] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md)
  - [ ] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [ ] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [ ] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-03---icmpv6-echo-with-large-payload)
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [x] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [x] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-09---icmpv6-stress-test-on-iotlab-m3)
  - [ ] [Task #10 (Exprimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/04-single-hop-6lowpan-icmp/example_test_guide.md#task-10-exprimental---icmpv6-echo-with-large-payload-ipv6-fragmentation)
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/05-single-hop-route/05-single-hop-route.md)
  - [ ] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [ ] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [ ] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [ ] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md)
  - [ ] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3)
  - [ ] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression)
  - [ ] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md#task-03---udp-on-native-non-existent-neighbor)
  - [ ] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md#task-04---udp-on-iotlab-m3-non-existent-neighbor)
  - [ ] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md#task-05---empty-udp-on-native)
  - [ ] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/06-single-hop-udp/06-single-hop-udp.md#task-06---empty-udp-on-iotlab-m3)
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/07-multi-hop/example_test_guide.md)
  - [ ] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/07-multi-hop/example_test_guide.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/07-multi-hop/example_test_guide.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/07-multi-hop/example_test_guide.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/07-multi-hop/example_test_guide.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/07-multi-hop/example_test_guide.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md)
  - [ ] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [ ] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)
  - [ ] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3)
  - [ ] [Task #10 - UDP between lwIP and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/09-coap/coap.md)
  - [ ] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/09-coap/coap.md#task-01---cord-endpoint)
  - [ ] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/09-coap/coap.md#task-02---confirmable-retries)
  - [ ] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/09-coap/coap.md#task-03---block1)
  - [ ] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/09-coap/coap.md#task-04---block2)
  - [ ] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/09-coap/coap.md#task-05---observe-registration-and-notification)
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md)
  - [ ] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-01---destination-unreachable---no-route-to-destination)
  - [ ] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [ ] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-03---destination-unreachable---address-unreachable-target-node-address)
  - [ ] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss)
  - [ ] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-05---destination-unreachable---port-unreachable)
  - [ ] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-06---destination-unreachable---port-unreachable-large-payload)
  - [ ] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-07---packet-too-big)
  - [ ] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [ ] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-09---parameter-problem---erroneous-header-field-encountered)
  - [ ] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/10-icmpv6-error/10-icmpv6-error.md#task-10---ipv6-in-ipv6-encapsulation)
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/11-lorawan/11-lorawan.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/11-lorawan/11-lorawan.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/11-lorawan/11-lorawan.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/11-lorawan/11-lorawan.md#task-03---abp-join-procedure)
  - [ ] [Task #03 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/11-lorawan/11-lorawan.md#task-03---lorawan-device-parameters-persistence)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/8f394349d965891c96dfa505db36b1e5127a5740/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by fjmolinas** [comment]
Merged PR's sinc RC2:

- #13187 from fjmolinas/backport/2020.01/pr_suit_docker 
- #13186 from fjmolinas/backport/2020.01/pr_efm32_series1_rtc_normalize
- #13193 from fjmolinas/backport/2020.01/pr/drivers/xbee_fix_ref_to_device
- #13206 from fjmolinas/backport/2020.01/pr_fix_info_board_RIOTBASE
- #13207 from MichelRottleuthner/pr_bp_13185 xtimer/xtimer.c:_mutex_timeout() improved
- #13219 from fjmolinas/backport/2020.01/pr_openocd_stm32f7_probe
- #13235 from benpicco/backport/2020.01/lpc2387-rtc-fix
-  #13237 from MichelRottleuthner/pr_bp13212 sys/xtimer: compare two offsets rather than absolute times

**Comment by fjmolinas** [comment]
I'll re run the tests fixes that where merged and:

- 04.07
- 04.08

**Comment by fjmolinas** [comment]
<details><summary> <b> BOARD=iotlab-m3 RIOT_CI_BUILD=1 BUILD_IN_DOCKER=1 make -C examples/suit_update/ flash test
</b> </summary>

```
Header chksum: 0x140d72d3

suit_coap: started.
Starting the shell
> ifconfig
ifconfig
Iface  5  HWaddr: 02:79:B3:0F:3B:AC 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          RTR_ADV  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::79:b3ff:fe0f:3bac  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
pinging node...
PING fe80::79:b3ff:fe0f:3bac%riot0(fe80::79:b3ff:fe0f:3bac%riot0) 56 data bytes

--- fe80::79:b3ff:fe0f:3bac%riot0 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 61.125/61.125/61.125/0.000 ms
pinging node succeeded.
TEST PASSED

```
</details>

<details><summary> <b> RIOT_CI_BUILD=1 BUILD_IN_DOCKER=1 BOARD=slstk3402a make -C tests/periph_rtt/ flash test --no-print-directory</b> </summary>

```
2020-01-31 17:53:48,867 # RIOT RTT low-level driver test
2020-01-31 17:53:48,869 # This test will display 'Hello' every 5 seconds
2020-01-31 17:53:48,869 # 
2020-01-31 17:53:48,870 # Initializing the RTT driver
2020-01-31 17:53:48,871 # RTT now: 0
2020-01-31 17:53:48,875 # Setting initial alarm to now + 5 s (5)
2020-01-31 17:53:48,877 # Done setting up the RTT, wait for many Hellos
2020-01-31 17:53:53,866 # Hello
2020-01-31 17:53:58,864 # Hello
2020-01-31 17:54:03,863 # Hello
2020-01-31 17:54:08,861 # Hello
2020-01-31 17:54:13,860 # Hello
```
</details>

<details><summary> <b> RIOT_CI_BUILD=1 BUILD_IN_DOCKER=1 BOARD=nucleo-f767zi make -C tests/riotboot/ flash test --no-print-directory</b> </summary>

```
### Flashing Target ###
WARN: Failed to probe board flash.
WARN: Falling back to using the openocd configuration value.
Binfile detected, adding ROM base address: 0x08000000
Flashing with IMAGE_OFFSET: 0x08000000
Open On-Chip Debugger 0.10.0+dev-gded6799 (2019-12-19-12:01)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
WARNING: interface/stlink-v2-1.cfg is deprecated, please switch to interface/stlink.cfg
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
srst_only separate srst_nogate srst_open_drain connect_assert_srst

Info : clock speed 2000 kHz
Info : STLINK V2J28M17 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.247800
Info : stm32f7x.cpu: hardware has 8 breakpoints, 4 watchpoints
Info : Listening on port 35515 for gdb connections
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32f7x.cpu       hla_target little stm32f7x.cpu       reset

Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08000330 msp: 0x20000200
Info : device id = 0x10006451
Info : flash size = 2048 kbytes
Info : Single Bank 2048 kiB STM32F76x/77x found
auto erase enabled
wrote 1310720 bytes from file /builds/boards/bin/nucleo-f767zi_flashfile.bin in 20.024244s (63.923 KiB/s)

verified 1049088 bytes in 4.265742s (240.169 KiB/s)

Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
shutdown command invoked
Done flashing

```
</details>

**Comment by fjmolinas** [comment]
<details><summary> <b> 04-single-hop-6lowpan-icmp </b> Task 7 RC3 Passes </summary>

```
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................. 
fe80::d1c1:6d4e:ab6a:1336: icmp_seq=999 ttl=64 rssi=59 dBm time=166.206 ms
2020-01-31 18:04:18,589 # 
2020-01-31 18:04:18,592 # --- ff02::1 PING statistics ---
2020-01-31 18:04:18,597 # 1000 packets transmitted, 977 packets received, 2% packet loss

2020-01-31 18:04:18,602 # round-trip min/avg/max = 166.206/224.681/263.716 ms
> 2020-01-31 18:04:21,660 #  pktbuf
2020-01-31 18:04:21,667 # packet buffer: first byte: 0x200019b0, last byte: 0x200031b0 (size: 6144)

2020-01-31 18:04:21,670 #   position of last byte used: 432
2020-01-31 18:04:21,674 # ~ unused: 0x200019b0 (next: (nil), size: 6144) ~

> 2020-01-31 18:04:24,736 #  pktbuf
2020-01-31 18:04:24,742 # packet buffer: first byte: 0x1fffdbd4, last byte: 0x1ffff3d4 (size: 6144)

2020-01-31 18:04:24,745 #   position of last byte used: 384
2020-01-31 18:04:24,749 # ~ unused: 0x1fffdbd4 (next: (nil), size: 6144) ~
```
</details>

<details><summary> <b> 04-single-hop-6lowpan-icmp </b> Task 8 RC3 <b> 50 bytes payload</b> Passes </summary>

```
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... fe80::d1c1:6d4e:ab6a:1336: icmp_seq=999 ttl=64 rssi=55 dBm time=172.344 ms
2020-01-31 18:10:07,633 # 
2020-01-31 18:10:07,637 # --- fe80::d1c1:6d4e:ab6a:1336 PING statistics ---
2020-01-31 18:10:07,643 # 1000 packets transmitted, 969 packets received, 3% packet loss

2020-01-31 18:10:07,647 # round-trip min/avg/max = 172.344/180.797/280.075 ms
> 2020-01-31 18:10:10,713 #  pktbuf
2020-01-31 18:10:10,719 # packet buffer: first byte: 0x200019b0, last byte: 0x200031b0 (size: 6144)

2020-01-31 18:10:10,722 #   position of last byte used: 432
2020-01-31 18:10:10,727 # ~ unused: 0x200019b0 (next: (nil), size: 6144) ~

> 2020-01-31 18:10:13,788 #  pktbuf
2020-01-31 18:10:13,795 # packet buffer: first byte: 0x1fffdbd4, last byte: 0x1ffff3d4 (size: 6144)

2020-01-31 18:10:13,798 #   position of last byte used: 392
2020-01-31 18:10:13,802 # ~ unused: 0x1fffdbd4 (next: (nil), size: 6144) ~
```
</details>

**Comment by fjmolinas** [comment]
Closing now that 2020.01 is out.
