### ISSUE TITLE
02-tests Release 2015.12 - RC4

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/Release-Specs#17]

**Comment by A-Paul** [comment]
### Task 01 - Execute all tests on `native` and check their output.

Feel free to edit this list.

* [ ] bitarithm_timings
* [ ] bloom_bytes
* [ ] coap
* [ ] **conn_ip (NN)**
* [ ] cpp11_condition_variable
* [ ] cpp11_mutex
* [ ] cpp11_thread

**Skipped all driver_***
* [ ] fault_handler
* [ ] float
* [ ] fmt_print
* [ ] irq
* [ ] **libfixmath (slight errors, details in https://github.com/RIOT-OS/Release-Specs/issues/12#issuecomment-169499548)**
* [ ] libfixmath_unittests
* [ ] malloc
* [ ] minimal
* [ ] msg_send_receive
* [ ] mutex_unlock_and_sleep
* [ ] nhdp

**Skipped all preiph*** Almost
* [ ] **pipe (<- dont know if the output is correct)**
* [ ] **pkg_cmsis-dsp (<- fails to build for native,i.e. correct)**
* [ ] pkg_micro-ecc (<- takes a lot of time to finish ~2h)
* [ ] posix_semaphore
* [ ] posix_sleep
* [ ] pthread
* [ ] pthread_barrier
* [ ] pthread_cleanup
* [ ] pthread_condition_variable
* [ ] pthread_cooperation
* [ ] pthread_rwlock
* [ ] pthread_tls
* [ ] sched_testing
* [ ] shell
* [ ] sizeof_tcb
* [ ] slip
* [ ] struct_tm_utility
* [ ] thread_basic
* [ ] thread_cooperation
* [ ] thread_exit
* [ ] thread_msg
* [ ] thread_msg_avail
* [ ] thread_msg_block_wo_queue
* [ ] thread_msg_block_w_queue
* [ ] thread_msg_seq
* [ ] unittests
* [ ] vtimer_msg
* [ ] vtimer_msg_diff
* [ ] warn_conflict
* [ ] xtimer_drift
* [ ] xtimer_hang
* [ ] xtimer_msg
* [ ] xtimer_msg_receive_timeout
* [ ] xtimer_remove
* [ ] xtimer_reset
* [ ] xtimer_shift_on_compare
* [ ] xtimer_usleep_until
* [ ] zep (<- untested yet unknown what to do)

**Comment by A-Paul** [comment]
Maybe someone who has *cmake* installed can run and (hopefully) check *unittests* ?

**Comment by cgundogan** [comment]
closing, because the 2015.12 version of RIOT was released.
