### ISSUE TITLE
Release 2020.07 - RC3

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/Release-Specs#175]
This issue lists the status of all tests for the [Release Candidate 3 of the 2020.07](https://github.com/RIOT-OS/RIOT/releases/tag/2020.07-RC3) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/01-ci/01-ci.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/01-ci/01-ci.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/01-ci/01-ci.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/01-ci/01-ci.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/02-tests/02-tests.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663078994) 
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663080023) 
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour) @riot-ci 
  - [x] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-04---icmpv6-stress-test-on-native-1-hour) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663141787) 
  - [ ] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
  - [ ] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663079636) 
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663081204) 
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-03---icmpv6-echo-with-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663083062) 
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [x] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-09---icmpv6-stress-test-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663094385) 
  - [x] [Task #10 (Exprimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/04-single-hop-6lowpan-icmp/example_test_guide.md#task-10-exprimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663096473) 
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/05-single-hop-route/05-single-hop-route.md)
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663144828) 
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663097356) 
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663144958) 
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663145097) 
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md)
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663115771) 
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663134314) 
  - [x] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md#task-03---udp-on-native-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663145252) 
  - [x] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md#task-04---udp-on-iotlab-m3-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663134826) 
  - [x] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md#task-05---empty-udp-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663145586) 
  - [x] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/06-single-hop-udp/06-single-hop-udp.md#task-06---empty-udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663135419) 
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/07-multi-hop/example_test_guide.md)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/07-multi-hop/example_test_guide.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663136217) 
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/07-multi-hop/example_test_guide.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663137165) 
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/07-multi-hop/example_test_guide.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663138208) 
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/07-multi-hop/example_test_guide.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663139247) 
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/07-multi-hop/example_test_guide.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663145803) 
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663142619) 
  - [ ] [Task #09 - deprecated](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-09---deprecated)
  - [ ] [Task #10 - deprecated](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-10---deprecated)
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/08-interop/08-interop.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/09-coap/coap.md)
  - [x] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/09-coap/coap.md#task-01---cord-endpoint) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663146362) 
  - [x] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/09-coap/coap.md#task-02---confirmable-retries) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663146470) 
  - [x] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/09-coap/coap.md#task-03---block1) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663148271) 
  - [ ] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/09-coap/coap.md#task-04---block2)
  - [x] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/09-coap/coap.md#task-05---observe-registration-and-notification) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663148500) 
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md)
  - [ ] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-01---destination-unreachable---no-route-to-destination)
  - [ ] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [x] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-03---destination-unreachable---address-unreachable-target-node-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663148778) 
  - [x] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663148879) 
  - [x] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-05---destination-unreachable---port-unreachable) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663148954) 
  - [x] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-06---destination-unreachable---port-unreachable-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663149021) 
  - [x] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-07---packet-too-big) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663149180) 
  - [ ] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [x] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-09---parameter-problem---erroneous-header-field-encountered) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/175#issuecomment-663149382) 
  - [ ] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/10-icmpv6-error/10-icmpv6-error.md#task-10---ipv6-in-ipv6-encapsulation)
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/11-lorawan/11-lorawan.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/11-lorawan/11-lorawan.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/11-lorawan/11-lorawan.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/11-lorawan/11-lorawan.md#task-03---abp-join-procedure)
  - [ ] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/11-lorawan/11-lorawan.md#task-04---lorawan-device-parameters-persistence)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by aabadie** [comment]
For [99. Task 01](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares), some results are available [here](https://github.com/aabadie/RIOT/actions/runs/180134784).

**Comment by miri64** [comment]
The only failures reported by @riot-ci were due to TAP loss.

> For [99. Task 01](https://github.com/RIOT-OS/Release-Specs/blob/3a04eafdb623d67a42228034cde1586d19979385/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares), some results are available [here](https://github.com/aabadie/RIOT/actions/runs/180134784).

From what I can see there and in [@fjmolinas' setup](https://ci.inria.fr/ci-riot-tribe/blue/organizations/jenkins/build-boards.jk/detail/build-boards.jk/127/pipeline/) I'd say there are no big surprises, so let's go on with the release.

**Comment by fjmolinas** [comment]
Published the results https://github.com/miri64/RIOT-2020.07-results.

**Comment by miri64** [comment]
2020.07 is out
