### ISSUE TITLE
Release 2020.10 - RC4

### ISSUE THREAD

**Issue by bergzand** [RIOT-OS/Release-Specs#196]
This issue lists the status of all tests for the [Release Candidate 4 of the 2020.10](https://github.com/RIOT-OS/RIOT/releases/tag/2020.10-RC4) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/01-ci/README.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/01-ci/README.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/01-ci/README.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/01-ci/README.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/01-ci/README.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/02-tests/README.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/02-tests/README.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md)
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718731237) 
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718732103) 
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour) @riot-ci 
  - [x] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718820930) 
  - [x] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718823093) 
  - [x] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718824921) 
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718731643) 
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718745251) 
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-03---icmpv6-echo-with-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718747135) 
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes) @riot-ci 
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [x] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-09---icmpv6-stress-test-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718759704) 
  - [x] [Task #10 (Exprimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/04-single-hop-6lowpan-icmp/example_test_guide.md#task-10-exprimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718762350) 
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/05-single-hop-route/README.md)
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718825138) 
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718763343) 
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718825311) 
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718825528) 
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md)
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718786691) 
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718810976) 
  - [x] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718825733) 
  - [x] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718811693) 
  - [x] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md#task-05---empty-udp-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718826132) 
  - [x] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718812519) 
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/07-multi-hop/example_test_guide.md)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/07-multi-hop/example_test_guide.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718813686) 
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/07-multi-hop/example_test_guide.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718814987) 
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/07-multi-hop/example_test_guide.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718816472) 
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/07-multi-hop/example_test_guide.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718817937) 
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/07-multi-hop/example_test_guide.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718826400) 
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718822603) 
  - [x] ~~Task #09 - deprecated~~
  - [x] ~~Task #10 - deprecated~~
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
  - [ ] [Task #12 - GNRC Border Router with WiFi uplink to the Internet](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-12---gnrc-border-router-with-wifi-uplink-to-the-internet)
  - [ ] [Task #13 - GNRC Networking](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/08-interop/README.md#task-13---gnrc-networking)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/09-coap/README.md)
  - [x] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/09-coap/README.md#task-01---cord-endpoint) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718827256) 
  - [x] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/09-coap/README.md#task-02---confirmable-retries) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718827539) 
  - [x] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/09-coap/README.md#task-03---block1) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718830084) 
  - [x] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/09-coap/README.md#task-04---block2) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718831669) 
  - [x] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/09-coap/README.md#task-05---observe-registration-and-notification) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718831803) 
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md)
  - [x] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718831911) 
  - [x] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832031) 
  - [x] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832157) 
  - [x] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832308) 
  - [x] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832396) 
  - [x] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832522) 
  - [x] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-07---packet-too-big) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832745) 
  - [x] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718832922) 
  - [x] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718833036) 
  - [x] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/196#issuecomment-718833176) 
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/11-lorawan/README.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/11-lorawan/README.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/11-lorawan/README.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/11-lorawan/README.md#task-03---abp-join-procedure)
  - [ ] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/99-compile-and-test-one-board/README.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/41350b98d9c4fc4a5ef2823e2217fc12a903e2b8/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares)

**Comment by bergzand** [comment]
One last RC, blame RIOT-OS/RIOT#15319 :disappointed:

**Comment by miri64** [comment]
> One last RC, blame [RIOT-OS/RIOT#15319](https://github.com/RIOT-OS/RIOT/pull/15319) disappointed

As long as we don't shoot the messenger ;-).

**Comment by bergzand** [comment]
> As long as we don't shoot the messenger ;-).

Never!

**Comment by bergzand** [comment]
Release is done, no need to keep this around
