### ISSUE TITLE
Release 2021.01 - RC3

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/Release-Specs#207]
This issue lists the status of all tests for the [Release Candidate 3 of the 2021.01](https://github.com/RIOT-OS/RIOT/releases/tag/2021.01-RC3) release.

Specs tested:
- [x] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md) (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770109162)
  - [x] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md)
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770089107) 
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770089744) 
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour) @riot-ci 
  - [x] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770123090) 
  - [ ] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
  - [x] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124358) 
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770089455) 
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770090599) 
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-03---icmpv6-echo-with-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770091705) 
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes) @riot-ci 
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xprocc2538)
  - [ ] [Task #06 (Experimental)- ICMPv6 link-local echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xprocc2538)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [x] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-09---icmpv6-stress-test-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770098919) 
  - [x] [Task #10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770100138) 
  - [x] [Task #11 (Experimental) - ICMPv6 stress test on nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-11-experimental---icmpv6-stress-test-on-nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770100998) 
  - [x] [Task #12 (Experimental) - ICMPv6 multicast echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-12-experimental---icmpv6-multicast-echo-with-iotlab-m3nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770101738) 
  - [x] [Task #13 (Experimental) - ICMPv6 link-local echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-13-experimental---icmpv6-link-local-echo-with-iotlab-m3nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770102521) 
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md)
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124426) 
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770102918) 
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124463) 
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124524) 
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md)
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770113049) 
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770121874) 
  - [x] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124582) 
  - [x] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770122099) 
  - [x] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-05---empty-udp-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124690) 
  - [x] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770122354) 
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770122704) 
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770123087) 
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770123542) 
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770123969) 
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770124772) 
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770125476) 
  - [x] ~~Task #09 - deprecated~~
  - [x] ~~Task #10 - deprecated~~
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
  - [ ] [Task #12 - GNRC Border Router with WiFi uplink to the Internet](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-12---gnrc-border-router-with-wifi-uplink-to-the-internet)
  - [ ] [Task #13 - GNRC Networking](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-13---gnrc-networking)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md)
  - [x] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-01---cord-endpoint) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770125024) 
  - [x] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-02---confirmable-retries) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770125140) 
  - [x] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-03---block1) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770125999) 
  - [x] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-04---block2) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126515) 
  - [x] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-05---observe-registration-and-notification) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126553) 
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md)
  - [x] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126580) 
  - [x] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126601) 
  - [x] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126633) 
  - [x] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126668) 
  - [x] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126699) 
  - [x] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126725) 
  - [x] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-07---packet-too-big) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126801) 
  - [x] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126847) 
  - [x] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126876) 
  - [x] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/207#issuecomment-770126908) 
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md)
  - [x] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-03---abp-join-procedure)
  - [ ] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence)
  - [ ] [Task #05 - GNRC LoRaWAN (Over The Air Activation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-05---gnrc-lorawan-over-the-air-activation)
  - [ ] [Task #06 - GNRC LoRaWAN (ABP)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-06---gnrc-lorawan-abp)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/99-compile-and-test-one-board/README.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares)

**Comment by jia200x** [comment]
As stated in https://github.com/RIOT-OS/Release-Specs/issues/206#issuecomment-770086206, we should run specs 01 and 02 and 11-T01 (`examples/lorawan`).

**Comment by jia200x** [comment]
(It doesn't hurt though that the CI tests the rest ;)

**Comment by jia200x** [comment]
### [01. Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-01---compile-test)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
-- github reports HEAD of 2021.01-branch as 36e102a81c3cd790d92880749accb0b393d53ce1
--- creating merge commit ...
-- merging 8d1e3effec279c99b2406f67edc25240abd5431c into 36e102a81c3cd790d92880749accb0b393d53ce1
--- done.
---- using merge commit SHA1=710eeaa3f2693da5b79b2a7840ac6c287d2ccac7
-- Building PR#15889 https://github.com/RIOT-OS/RIOT/pull/15889 head: 8d1e3effec279c99b2406f67edc25240abd5431c...
-- processing results ...
- running script "/opt/murdock2/scripts/post-build.d/00sizes.py"
- running script "/opt/murdock2/scripts/post-build.d/01metrics.py"
-- done processing results

--- result: BUILD SUCCESSFUL.

```

</details>

**Comment by jia200x** [comment]
### [11. Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-01---lorawan-example)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
Join procedure succeeded
Sendi==========
Starting join procedure
Join procedure succeeded
Sending: This is RIOT!
Sending: This is RIOT!
Sending: This is RIOT!
Sending: This is RIOT!
```

</details>

**Comment by jia200x** [comment]
I will open the RC-4, since https://github.com/RIOT-OS/RIOT/pull/15905  was backported. I don't expect anything new to fail now, so I think it should be ok to run specs-01-{02,03,04} and specs-02.

**Comment by jia200x** [comment]
Closing in favor of #208
