### ISSUE TITLE
Release 2021.01 - RC4

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/Release-Specs#208]
This issue lists the status of all tests for the [Release Candidate 4 of the 2021.01](https://github.com/RIOT-OS/RIOT/releases/tag/2021.01-RC4) release.

Specs tested:

(accidentaly cleared, sorry. last state is in edit history)

- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md)
  - [ ] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native)
  - [ ] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native)
  - [ ] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
  - [ ] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour)
  - [ ] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
  - [ ] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md)
  - [ ] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [ ] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [ ] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-03---icmpv6-echo-with-large-payload)
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xprocc2538)
  - [ ] [Task #06 (Experimental)- ICMPv6 link-local echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xprocc2538)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-09---icmpv6-stress-test-on-iotlab-m3)
  - [ ] [Task #10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation)
  - [ ] [Task #11 (Experimental) - ICMPv6 stress test on nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-11-experimental---icmpv6-stress-test-on-nrf802154)
  - [ ] [Task #12 (Experimental) - ICMPv6 multicast echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-12-experimental---icmpv6-multicast-echo-with-iotlab-m3nrf802154)
  - [ ] [Task #13 (Experimental) - ICMPv6 link-local echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-13-experimental---icmpv6-link-local-echo-with-iotlab-m3nrf802154)
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md)
  - [ ] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [ ] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [ ] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [ ] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md)
  - [ ] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771598948) 
  - [ ] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771618064) 
  - [ ] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771624779) 
  - [ ] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771618643) 
  - [ ] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-05---empty-udp-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771625111) 
  - [ ] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771619377) 
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md)
  - [ ] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771621450) 
  - [ ] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771623873) 
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md)
  - [ ] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771625367) 
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [ ] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771627855) 
  - [ ] ~~Task #09 - deprecated~~
  - [ ] ~~Task #10 - deprecated~~
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
  - [ ] [Task #12 - GNRC Border Router with WiFi uplink to the Internet](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-12---gnrc-border-router-with-wifi-uplink-to-the-internet)
  - [ ] [Task #13 - GNRC Networking](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-13---gnrc-networking)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md)
  - [ ] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-01---cord-endpoint) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771626096) 
  - [ ] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-02---confirmable-retries) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771626335) 
  - [ ] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-03---block1)
  - [ ] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-04---block2)
  - [ ] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-05---observe-registration-and-notification) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771629936) 
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md)
  - [ ] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination)
  - [ ] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [ ] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address)
  - [ ] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771630334) 
  - [ ] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771630423) 
  - [ ] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload)
  - [ ] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-07---packet-too-big) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771630723) 
  - [ ] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [ ] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771630971) 
  - [ ] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771631089) 
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-03---abp-join-procedure)
  - [ ] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence)
  - [ ] [Task #05 - GNRC LoRaWAN (Over The Air Activation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-05---gnrc-lorawan-over-the-air-activation)
  - [ ] [Task #06 - GNRC LoRaWAN (ABP)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-06---gnrc-lorawan-abp)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/99-compile-and-test-one-board/README.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares)

**Comment by jia200x** [comment]
We should only run specs-01 (without the compile test) and specs-02

**Comment by jia200x** [comment]
https://github.com/RIOT-OS/RIOT/actions/runs/530524468 is taking care of `samr21-xpro` and `iotlab-m3 in specs-02 :)

**Comment by jia200x** [comment]
nothing new on 02-01 :)

**Comment by jia200x** [comment]
### [01. Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-03---unittests-on-native-separated)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
...
main(): This is RIOT! (Version: 2021.04-devel-30-gce1ca-HEAD)
Help: Press s to start test, r to print it is ready
READY
s
START
..............
OK (14 tests)

Building application "tests_unittests" for "native" with MCU "native".

"make" -C RIOTBASE/RIOT/boards/native
"make" -C RIOTBASE/RIOT/boards/native/drivers
"make" -C RIOTBASE/RIOT/core
"make" -C RIOTBASE/RIOT/cpu/native
"make" -C RIOTBASE/RIOT/cpu/native/periph
"make" -C RIOTBASE/RIOT/cpu/native/stdio_native
"make" -C RIOTBASE/RIOT/drivers
"make" -C RIOTBASE/RIOT/drivers/periph_common
"make" -C RIOTBASE/RIOT/sys
"make" -C RIOTBASE/RIOT/sys/embunit
"make" -C RIOTBASE/RIOT/sys/fmt
"make" -C RIOTBASE/RIOT/sys/test_utils/interactive_sync
"make" -C RIOTBASE/RIOT/tests/unittests/tests-fmt
/usr/bin/ld: RIOTBASE/RIOT/tests/unittests/bin/native/cpu/tramp.o: warning: relocation against `_native_saved_eip' in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
   text	 data	  bss	  dec	  hex	filename
  69609	  928	51932	122469	1de65	RIOTBASE/RIOT/tests/unittests/bin/native/tests_unittests.elf
r
RIOTBASE/RIOT/tests/unittests/bin/native/tests_unittests.elf /dev/ttyACM0 
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2021.04-devel-30-gce1ca-HEAD)
Help: Press s to start test, r to print it is ready
READY
s
START
.............................
OK (29 tests)

SUCCESS
```

</details>

**Comment by jia200x** [comment]
### [01. Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-02---unittests-on-native)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
~/RIOT/results/native/ ls tests/unittests/*
tests/unittests/compilation.success  tests/unittests/test.success
```

</details>

**Comment by jia200x** [comment]
### [02. Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-01---all-tests-on-native)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
Failures during compilation:
- [tests/pkg_flatbuffers](tests/pkg_flatbuffers/compilation.failed)

Failures during test:
- [examples/micropython](examples/micropython/test.failed)
- [tests/bench_xtimer_load](tests/bench_xtimer_load/test.failed)
- [tests/driver_at86rf2xx_aes](tests/driver_at86rf2xx_aes/test.failed)
- [tests/gnrc_dhcpv6_client](tests/gnrc_dhcpv6_client/test.failed)
- [tests/lwip](tests/lwip/test.failed)
```

</details>

These failures are mostly false positives and XFAILs (examples/micropython)

**Comment by jia200x** [comment]
### [02. Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
<!-- Please add the description -->
 ERROR:iotlab-m3:Tests failed: 17
Failures during test:
- [examples/suit_update](examples/suit_update/test.failed)
- [tests/driver_hd44780](tests/driver_hd44780/test.failed)
- [tests/emcute](tests/emcute/test.failed)
- [tests/gnrc_dhcpv6_client](tests/gnrc_dhcpv6_client/test.failed)
- [tests/gnrc_dhcpv6_client_6lbr](tests/gnrc_dhcpv6_client_6lbr/test.failed)
- [tests/gnrc_ipv6_ext](tests/gnrc_ipv6_ext/test.failed)
- [tests/gnrc_ipv6_ext_frag](tests/gnrc_ipv6_ext_frag/test.failed)
- [tests/gnrc_ipv6_ext_opt](tests/gnrc_ipv6_ext_opt/test.failed)
- [tests/gnrc_ipv6_nib_dns](tests/gnrc_ipv6_nib_dns/test.failed)
- [tests/gnrc_rpl_srh](tests/gnrc_rpl_srh/test.failed)
- [tests/gnrc_sock_dns](tests/gnrc_sock_dns/test.failed)
- [tests/gnrc_tcp](tests/gnrc_tcp/test.failed)
- [tests/periph_timer_short_relative_set](tests/periph_timer_short_relative_set/test.failed)
- [tests/pkg_fatfs_vfs](tests/pkg_fatfs_vfs/test.failed)
- [tests/pkg_libfixmath_unittests](tests/pkg_libfixmath_unittests/test.failed)
- [tests/pkg_semtech-loramac](tests/pkg_semtech-loramac/test.failed)
- [tests/riotboot](tests/riotboot/test.failed)
```

</details>

Nothing new here (XFAILs because of configs and/or sudo. https://github.com/RIOT-OS/RIOT/pull/15771 took care of this

**Comment by jia200x** [comment]
### [02. Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
<details>
<summary>
<b>
PASSED
</b>
</summary>

```
 ERROR:samr21-xpro:Tests failed: 17
Failures during test:
- [examples/suit_update](examples/suit_update/test.failed)
- [tests/driver_ds3231](tests/driver_ds3231/test.failed)
- [tests/emcute](tests/emcute/test.failed)
- [tests/gnrc_dhcpv6_client](tests/gnrc_dhcpv6_client/test.failed)
- [tests/gnrc_dhcpv6_client_6lbr](tests/gnrc_dhcpv6_client_6lbr/test.failed)
- [tests/gnrc_ipv6_ext](tests/gnrc_ipv6_ext/test.failed)
- [tests/gnrc_ipv6_ext_frag](tests/gnrc_ipv6_ext_frag/test.failed)
- [tests/gnrc_ipv6_ext_opt](tests/gnrc_ipv6_ext_opt/test.failed)
- [tests/gnrc_ipv6_nib_dns](tests/gnrc_ipv6_nib_dns/test.failed)
- [tests/gnrc_rpl_srh](tests/gnrc_rpl_srh/test.failed)
- [tests/gnrc_sock_dns](tests/gnrc_sock_dns/test.failed)
- [tests/gnrc_tcp](tests/gnrc_tcp/test.failed)
- [tests/periph_timer_short_relative_set](tests/periph_timer_short_relative_set/test.failed)
- [tests/pkg_fatfs_vfs](tests/pkg_fatfs_vfs/test.failed)
- [tests/pkg_libfixmath_unittests](tests/pkg_libfixmath_unittests/test.failed)
- [tests/pkg_semtech-loramac](tests/pkg_semtech-loramac/test.failed)
- [tests/riotboot](tests/riotboot/test.failed)
```

</details>

Same as https://github.com/RIOT-OS/Release-Specs/issues/208#issuecomment-771657551. Nothing new...

**Comment by jia200x** [comment]
The specs required for this RC passed. This means, this should be the actual release

**Comment by fjmolinas** [comment]
Seems like this one can be closed.

**Comment by miri64** [comment]
Yepp, 2021.04-RC1 is out ;-)
