### ISSUE TITLE
Release 2021.04 - RC1

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/Release-Specs#213]
This issue lists the status of all tests for the [Release Candidate 1 of the 2021.04](https://github.com/RIOT-OS/RIOT/releases/tag/2021.04-RC1) release.

(this is the list of the last release, links are off)

- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-01---compile-test)
  - [x] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-02---unittests-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823118843) 
  - [x] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-03---unittests-on-native-separated) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823118961) 
  - [x] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/01-ci/README.md#task-04---unittests-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822743644) 
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md)
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823125766) 
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823127191) 
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour) @riot-ci 
  - [x] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823197972) 
  - [x] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823198795) 
  - [x] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823200005) 
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822744594) 
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822746710) 
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-03---icmpv6-echo-with-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823125519) 
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes) @riot-ci 
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xprocc2538)
  - [ ] [Task #06 (Experimental)- ICMPv6 link-local echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xprocc2538)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [x] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-09---icmpv6-stress-test-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822762591) 
  - [x] [Task #10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822764529) 
  - [x] [Task #11 (Experimental) - ICMPv6 stress test on nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-11-experimental---icmpv6-stress-test-on-nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822766154) 
  - [x] [Task #12 (Experimental) - ICMPv6 multicast echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-12-experimental---icmpv6-multicast-echo-with-iotlab-m3nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822767657) 
  - [ ] [Task #13 (Experimental) - ICMPv6 link-local echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/04-single-hop-6lowpan-icmp/README.md#task-13-experimental---icmpv6-link-local-echo-with-iotlab-m3nrf802154)
- [x] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md)
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823200283) 
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822769957) 
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823200476) 
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823200667) 
- [x] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md)
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822386091) 
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822405202) 
  - [x] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823200809) 
  - [x] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822405781) 
  - [x] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-05---empty-udp-on-native)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823201214) 
  - [x] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822406567) 
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822407684) 
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822408687) 
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822409848) 
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822411065) 
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/07-multi-hop/README.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823201481) 
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-822415025) 
  - [x] ~~Task #09 - deprecated~~
  - [x] ~~Task #10 - deprecated~~
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
  - [ ] [Task #12 - GNRC Border Router with WiFi uplink to the Internet](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-12---gnrc-border-router-with-wifi-uplink-to-the-internet)
  - [ ] [Task #13 - GNRC Networking](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/08-interop/README.md#task-13---gnrc-networking)
- [x] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md)
  - [x] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-01---cord-endpoint)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823202201) 
  - [x] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-02---confirmable-retries)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823202398) 
  - [x] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-03---block1) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823204484) 
  - [x] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-04---block2) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823205703) 
  - [x] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/09-coap/README.md#task-05---observe-registration-and-notification)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823205797) 
- [x] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md)
  - [x] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823205891) 
  - [x] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823205962) 
  - [x] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206031) 
  - [x] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206133) 
  - [x] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206194) 
  - [x] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206262) 
  - [x] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-07---packet-too-big)  @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206445) 
  - [x] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206580) 
  - [x] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered)   @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206640) 
  - [x] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823206725) 
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-03---abp-join-procedure)
  - [ ] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence)
  - [ ] [Task #05 - GNRC LoRaWAN (Over The Air Activation)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-05---gnrc-lorawan-over-the-air-activation)
  - [ ] [Task #06 - GNRC LoRaWAN (ABP)](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/11-lorawan/README.md#task-06---gnrc-lorawan-abp)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/99-compile-and-test-one-board/README.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/cd89479badfae5df2021013a68971b9bd26c2a39/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares)

**Comment by miri64** [comment]
Not sure why Murdock only reports the `iotlab_creds`, but the `not iotlab_creds, sudo` tests that where able to pass, passed.

**Comment by kaspar030** [comment]
> Not sure why Murdock only reports the `iotlab_creds`, but the `not iotlab_creds, sudo` tests that where able to pass, passed.

did they maybe succeed faster than I managed to create the issue?

**Comment by miri64** [comment]
Nah I reran the action tonight and it includes several hour long tests ;-)

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/16350. Seems to work!

**Comment by miri64** [comment]
Ok, all non-experimental tasks failed. For some reason, [`pylint` fails](https://github.com/miri64/RIOT/runs/2389082443?check_suite_focus=true#step:12:175) within the release tests. Any idea why @aabadie?

**Comment by aabadie** [comment]
> For some reason, pylint fails within the release tests

Could it be related to https://github.com/PyCQA/astroid/issues/942 ?

**Comment by miri64** [comment]
Mh, I can reproduce it locally, however, when I set `astroid` to 2.5.2 I still get the same result, so doesn't seem like it.

**Comment by miri64** [comment]
IIRC correctly (I restarted then cancelled the run due to the feature freeze so I can't confirm) the problem was not yet occurring on Saturday.

**Comment by miri64** [comment]
Definitely not [last week](https://github.com/RIOT-OS/RIOT/runs/2333712158)

**Comment by kaspar030** [comment]
Closing in favor of #214
