### ISSUE TITLE
02-tests/task 01 Release 2016.07 - RC1

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/Release-Specs#22]
# Task \# 01
## Execute all tests on `native` and check their output:

- [x] bitarithm_timings
- [x] bloom_bytes
- [x] coap
- [x] conn_ip
- [x] cpp11_condition_variable
- [x] cpp11_mutex
- [x] cpp11_thread
- [x] driver_adt7310
- [x] driver_at30tse75x
- [x] driver_at86rf2xx
- [x] driver_bh1750
- [x] driver_bmp180
- [x] driver_dht **-> compiles without warning runs and obviously fails**
- [x] driver_enc28j60
- [x] driver_encx24j600
- [x] driver_hdc1000
- [x] driver_hih6130
- [x] driver_ina220
- [x] driver_isl29020
- [x] driver_isl29125
- [x] driver_kw2xrf
- [x] driver_l3g4200d
- [x] driver_lis3dh
- [x] driver_lis3mdl
- [x] driver_lps331ap
- [x] driver_lsm303dlhc
- [x] driver_mag3110
- [x] driver_mma8652
- [x] driver_mpl3115a2
- [x] driver_mpu9150
- [x] driver_mq3
- [x] driver_nrf24l01p_lowlevel
- [x] driver_nrfmin
- [x] driver_nvram_spi
- [x] driver_pcd8544
- [x] driver_pir **-> compiles without warning runs and obviously fails on GPIO access**
- [x] driver_servo
- [x] driver_si70xx
- [x] driver_srf02
- [x] driver_srf08
- [x] driver_tcs37727
- [x] driver_tmp006
- [x] driver_xbee
- [x] emb6 **-> automatically sets `samr21-xpro` when `BOARD` is not set, build with `BOARD=native make` for the expected build fail** 
- [x] fault_handler
- [x] float **-> only shows/spams `-` on the screen**
- [x] fmt_print
- [x] gnrc_ipv6_ext
- [x] gnrc_sixlowpan
- [x] irq
- [x] leds
- [x] libfixmath
- [x] lwip **-> automatically sets `iotlab-m3` when `BOARD` is not set, build with `BOARD=native make`**
- [x] malloc **-> only `malloc` tested yet since I don't want to wait for filling my whole RAM with 1024 byte chunks**
- [x] minimal
- [x] msg_send_receive
- [x] msg_try_receive
- [x] mutex_order
- [x] mutex_unlock_and_sleep
- [x] netdev2_test
- [x] netstats_l2
- [x] nhdp
- [x] periph_adc
- [x] periph_cpuid
- [x] periph_dac
- [x] periph_gpio **-> compiles without warning and runs**
- [x] periph_hwrng
- [x] periph_i2c
- [x] periph_pwm
- [x] periph_rtc **-> compiles without warning and runs: `f: rtc_set_alarm: not implemented`**
- [x] periph_rtt
- [x] periph_spi
- [x] periph_timer
- [x] periph_uart **-> compiles without warning and runs: `UART used for STDIO (the shell): UART_DEV(-1)`**
- [x] pipe
- [x] pkg_cmsis-dsp
- [x] pkg_jsmn
- [x] pkg_micro-ecc
- [x] pkg_u8g2
- [x] posix_semaphore
- [x] posix_sleep
- [x] pthread
- [x] pthread_barrier
- [x] pthread_cleanup
- [x] pthread_condition_variable
- [x] pthread_cooperation
- [x] pthread_rwlock
- [x] pthread_tls
- [x] saul **-> compiles without warning and runs: `No SAUL devices present`**
- [x] sched_testing
- [x] shell
- [x] sizeof_tcb
- [x] slip **(compiled and started, function not tested yet)**
- [x] struct_tm_utility
- [x] thread_basic
- [x] thread_cooperation
- [x] thread_exit
- [x] thread_flags
- [x] thread_flood
- [x] thread_msg
- [x] thread_msg_avail
- [x] thread_msg_block_wo_queue
- [x] thread_msg_block_w_queue
- [x] thread_msg_seq
- [x] warn_conflict
- [x] xtimer_drift
- [x] xtimer_hang
- [x] xtimer_longterm
- [x] xtimer_msg
- [x] xtimer_msg_receive_timeout
- [x] xtimer_now64_continuity
- [x] xtimer_remove
- [x] xtimer_reset
- [x] xtimer_usleep_until
- [x] zep (compiled and started, function not tested yet)

list made manually performing:
``` sh
ls -1a | sed  -e 's/^/- [ ] /'
```
in `RIOT/tests`

**Comment by BytesGalore** [comment]
feel free to edit the list :)

**Comment by kYc0o** [comment]
Great! Thanks @BytesGalore @miri64 any hints on emb6 and lwip errors?

**Comment by miri64** [comment]
@BytesGalore @kYc0o can not reproduce, sadly :(

**Comment by BytesGalore** [comment]
@kYc0o @miri64 `emb6` sets the `samr21-xpro` board as default [1].
using:
``` sh
BOARD=native make
```
results in the expected behaviour, i.e. unsatisfied requirements and build fail
[1] https://github.com/RIOT-OS/RIOT/blob/master/tests/emb6/Makefile#L5

**Comment by miri64** [comment]
The reason this application sets it as a default is because there is no native support for it.

**Comment by miri64** [comment]
(emb6 only has IEEE 802.15.4 support so porting it for native wouldn't make much sense anyway, at least until #5582 is merged)

**Comment by miri64** [comment]
((also also: https://github.com/RIOT-OS/RIOT/issues/4672 needs to be solved, so auto-init also works for non GNRC-stacks))

**Comment by BytesGalore** [comment]
@miri64 yup I expected it to not compile and run but I expected a specific behaviour, i.e. failing with an unsatisfied requirements warning.

Similar applies for `lwip` the `iotlab-m3` board is set when `BOARD` is not provided [1].
using:
``` sh
BOARD=native make
```
results in a successful build and allows to start the compiled test-application (though untested yet)

[1] https://github.com/RIOT-OS/RIOT/blob/master/tests/lwip/Makefile#L3

**Comment by kYc0o** [comment]
So what's the conclusion on this? Can we say that the test ran successfully?

**Comment by BytesGalore** [comment]
@kYc0o don't know, I guess `lwip` is not supposed to run on `native` but it successfully builds and the test-application can be started.
Beside this uncertainty I would say the test ran successfully.

btw. Since we have no release branch yet, I performed the tests on:
https://github.com/RIOT-OS/RIOT/commit/b5cb68bd6673abe02166f8af7782aa2745ca08cd

**Comment by kYc0o** [comment]
Ok great. Yes that was the last commit before I started the tests too.

**Comment by miri64** [comment]
lwIP *is* supposed to run on native! So if it runs what is the problem? :/

**Comment by BytesGalore** [comment]
@miri64 if its supposed to run on `native` I propose that we change the default set `BOARD` accordingly.
> So if it runs what is the problem?

When I start it on `native` `ifconfig` states:
```
ifconfig
ET_00:  inet6 fe80::d8c3:d5ff:fe46:7582
```
but sending some packet fails:
```
> udp send 2001::1 8080 1
udp send 2001::1 8080 1
could not send
> ip send 2001::1 inet6 10
ip send 2001::1 inet6 10
could not send
```
probably I just failed to use it properly.

**Comment by BytesGalore** [comment]
ok, I failed :blush: 
```
> udp send fe80::1 8080 1
udp send fe80::1 8080 1
Success: send 1 byte to [fe80::1]:8080)
> ip send fe80::1 inet6 1
ip send fe80::1 inet6 1
Success: send 1 byte to fe80::1 (next header: 0)
```

**Comment by miri64** [comment]
:+1:

**Comment by BytesGalore** [comment]
I propose https://github.com/RIOT-OS/RIOT/pull/5698 to change the default `BOARD` to `native` for `lwip`
