### ISSUE TITLE
02-tests/task 02 Release 2016.07 - RC1

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/Release-Specs#23]
# Task \# 02
## Perform a subset of tests on [`iotlab-m3`](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-IoT-LAB-M3) node:

- [x] bitarithm_timings
- [ ] bloom_bytes
- [ ] coap
- [x] conn_ip **sent 3 pings out (`ping6`)**
- [ ] cpp11_condition_variable
- [ ] cpp11_mutex
- [x] cpp11_thread
- [ ] driver_adt7310
- [ ] driver_at30tse75x
- [x] driver_at86rf2xx
- [ ] driver_bh1750
- [ ] driver_bmp180
- [x] driver_dht  **-> results in expected behaviour: gets stuck at [`dht_read(dev, &temp, &hum)`](https://github.com/RIOT-OS/RIOT/blob/master/tests/driver_dht/main.c#L43), since no DHT 11/22 temperature and humidity sensor is attached**
- [ ] driver_enc28j60
- [ ] driver_encx24j600
- [x] driver_hdc1000 **-> results in expected behaviour: `Initializing HDC1000 sensor at I2C_0... [Failed]`**
- [ ] driver_hih6130
- [ ] driver_ina220
- [x] driver_isl29020
- [ ] driver_isl29125
- [ ] driver_kw2xrf
- [x] driver_l3g4200d
- [ ] driver_lis3dh
- [ ] driver_lis3mdl
- [x] driver_lps331ap
- [ ] driver_lsm303dlhc
- [ ] driver_mag3110
- [x] driver_mma8652 **-> results in expected behaviour: `Initializing MMA8652 accelerometer at I2C_0... [Failed]`**

- [ ] driver_mpl3115a2
- [ ] driver_mpu9150
- [x] driver_mq3
- [ ] driver_nrf24l01p_lowlevel
- [ ] driver_nrfmin
- [x] driver_nvram_spi **-> results in expected behaviour: `Verifying contents... [Failed]`**
- [ ] driver_pcd8544
- [ ] driver_pir
- [x] driver_servo
- [ ] driver_si70xx
- [ ] driver_srf02
- [x] driver_srf08 **-> results in expected behaviour: no values are printed, since no SRF08 ultrasonic sensor is attached**
- [ ] driver_tcs37727
- [ ] driver_tmp006
- [x] driver_xbee **-> results in expected behaviour: the device cannot be configured, since no xbee shield is attached**
- [ ] emb6
- [ ] fault_handler
- [x] float **-> only shows/spams `-` on the screen**
- [ ] fmt_print
- [ ] gnrc_ipv6_ext
- [x] gnrc_sixlowpan
- [ ] irq
- [ ] leds
- [x] libfixmath
- [ ] lwip
- [ ] malloc
- [x] minimal
- [ ] msg_send_receive
- [ ] msg_try_receive
- [x] mutex_order
- [ ] mutex_unlock_and_sleep
- [ ] netdev2_test
- [x] netstats_l2
- [ ] nhdp
- [ ] periph_adc
- [x] periph_cpuid
- [ ] periph_dac
- [ ] periph_gpio
- [x] periph_hwrng
- [ ] periph_i2c
- [ ] periph_pwm
- [x] periph_rtc
- [ ] periph_rtt
- [ ] periph_spi
- [x] periph_timer
- [ ] periph_uart
- [ ] pipe
- [x] pkg_cmsis-dsp
- [ ] pkg_jsmn
- [ ] pkg_micro-ecc
- [x] pkg_u8g2
- [ ] posix_semaphore
- [ ] posix_sleep
- [x] pthread
- [ ] pthread_barrier
- [ ] pthread_cleanup
- [x] pthread_condition_variable
- [ ] pthread_cooperation
- [ ] pthread_rwlock
- [x] pthread_tls
- [ ] saul
- [ ] sched_testing
- [x] shell
- [ ] sizeof_tcb
- [ ] slip
- [x] struct_tm_utility
- [ ] thread_basic
- [ ] thread_cooperation
- [x] thread_exit
- [ ] thread_flags
- [ ] thread_flood
- [x] thread_msg
- [ ] thread_msg_avail
- [ ] thread_msg_block_wo_queue
- [x] thread_msg_block_w_queue
- [ ] thread_msg_seq
- [ ] warn_conflict
- [x] xtimer_drift **-> I ran it for a handful minutes: max `drift/jitter` is about `+-35 us` (these high values occured ~ 4 times a `min`)**
- [ ] xtimer_hang
- [ ] xtimer_longterm
- [x] xtimer_msg
- [ ] xtimer_msg_receive_timeout
- [ ] xtimer_now64_continuity
- [x] xtimer_remove
- [ ] xtimer_reset
- [ ] xtimer_usleep_until
- [x] zep

list made manually by executing:
``` sh
ls -1a | sed  -e 's/^/- [ ] /'
```
in `RIOT/tests` and removing `unittests` et al. from the list

**Comment by BytesGalore** [comment]
tests performed on:
https://github.com/RIOT-OS/RIOT/commit/b5cb68bd6673abe02166f8af7782aa2745ca08cd
with:
`gcc version 5.3.1 20160307 (release) [ARM/embedded-5-branch revision 234589] (GNU Tools for ARM Embedded Processors)`
