### ISSUE TITLE
Release 2021.10 - RC2

### ISSUE THREAD

**Issue by benpicco** [RIOT-OS/Release-Specs#237]
This issue lists the status of all tests for the [Release Candidate 2 of the 2021.10](https://github.com/RIOT-OS/RIOT/releases/tag/2021.10-RC2) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/01-ci/README.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/01-ci/README.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/01-ci/README.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/01-ci/README.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/01-ci/README.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/02-tests/README.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/02-tests/README.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md)
  - [ ] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native)
  - [ ] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native)
  - [ ] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
  - [ ] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour)
  - [ ] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress)
  - [ ] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md)
  - [ ] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [ ] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [ ] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-03---icmpv6-echo-with-large-payload)
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xprocc2538)
  - [ ] [Task #06 (Experimental)- ICMPv6 link-local echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xprocc2538)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-09---icmpv6-stress-test-on-iotlab-m3)
  - [ ] [Task #10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation)
  - [ ] [Task #11 (Experimental) - ICMPv6 stress test on nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-11-experimental---icmpv6-stress-test-on-nrf802154)
  - [ ] [Task #12 (Experimental) - ICMPv6 multicast echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-12-experimental---icmpv6-multicast-echo-with-iotlab-m3nrf802154)
  - [ ] [Task #13 (Experimental) - ICMPv6 link-local echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/04-single-hop-6lowpan-icmp/README.md#task-13-experimental---icmpv6-link-local-echo-with-iotlab-m3nrf802154)
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/05-single-hop-route/README.md)
  - [ ] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [ ] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [ ] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [ ] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md)
  - [ ] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3)
  - [ ] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression)
  - [ ] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor)
  - [ ] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor)
  - [ ] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md#task-05---empty-udp-on-native)
  - [ ] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3)
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/07-multi-hop/README.md)
  - [ ] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/07-multi-hop/README.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/07-multi-hop/README.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/07-multi-hop/README.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/07-multi-hop/README.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/07-multi-hop/README.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md)
  - [ ] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux)
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [ ] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)
  - [x] ~~Task #09 - deprecated~~
  - [x] ~~Task #10 - deprecated~~
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
  - [ ] [Task #12 - ICMPv6 echo between Border Router with WiFi uplink to named Internet host](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-12---icmpv6-echo-between-border-router-with-wifi-uplink-to-named-internet-host)
  - [ ] [Task #13 - ICMPv6 echo between ESP and named Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/08-interop/README.md#task-13---icmpv6-echo-between-esp-and-named-internet-host-through-linux-with-6lowpan)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/09-coap/README.md)
  - [ ] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/09-coap/README.md#task-01---cord-endpoint)
  - [ ] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/09-coap/README.md#task-02---confirmable-retries)
  - [ ] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/09-coap/README.md#task-03---block1)
  - [ ] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/09-coap/README.md#task-04---block2)
  - [ ] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/09-coap/README.md#task-05---observe-registration-and-notification)
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md)
  - [ ] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination)
  - [ ] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [ ] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address)
  - [ ] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss)
  - [ ] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable)
  - [ ] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload)
  - [ ] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-07---packet-too-big)
  - [ ] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [ ] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered)
  - [ ] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation)
- [ ] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md)
  - [ ] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md#task-01---lorawan-example)
  - [ ] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md#task-02---otaa-join-procedure)
  - [ ] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md#task-03---abp-join-procedure)
  - [ ] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence)
  - [ ] [Task #05 - GNRC LoRaWAN (Over The Air Activation)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md#task-05---gnrc-lorawan-over-the-air-activation)
  - [ ] [Task #06 - GNRC LoRaWAN (ABP)](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/11-lorawan/README.md#task-06---gnrc-lorawan-abp)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/99-compile-and-test-one-board/README.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/9e4c12d4ee208c6bc414c28a17070d86dc138a44/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares)
