### ISSUE TITLE
Release 2022.07 - RC1

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/Release-Specs#253]
This issue lists the status of all tests for the [Release Candidate 1 of the 2022.07](https://github.com/RIOT-OS/RIOT/releases/tag/2022.07-RC1) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/01-ci/README.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/01-ci/README.md#task-01---compile-test)
  - [x] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/01-ci/README.md#task-02---unittests-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/01-ci/README.md#task-03---unittests-on-native-separated) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/01-ci/README.md#task-04---unittests-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/02-tests/README.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/02-tests/README.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md)
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - ICMPv6 stress test on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #05 - ICMPv6 stress test on native (neighbor cache stress)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-03---icmpv6-echo-with-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xprocc2538)
  - [ ] [Task #06 (Experimental)- ICMPv6 link-local echo with samr21-xpro/cc2538](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xprocc2538)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [x] [Task #09 - ICMPv6 stress test on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-09---icmpv6-stress-test-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) @miri64 (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1189108952) 
  - [x] [Task #11 (Experimental) - ICMPv6 stress test on nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-11-experimental---icmpv6-stress-test-on-nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #12 (Experimental) - ICMPv6 multicast echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-12-experimental---icmpv6-multicast-echo-with-iotlab-m3nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #13 (Experimental) - ICMPv6 link-local echo with iotlab-m3/nrf802154](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-13-experimental---icmpv6-link-local-echo-with-iotlab-m3nrf802154) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [x] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/05-single-hop-route/README.md)
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [x] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md)
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #05 - Empty UDP on native](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md#task-05---empty-udp-on-native) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #06 - Empty UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/07-multi-hop/README.md)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/07-multi-hop/README.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/07-multi-hop/README.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/07-multi-hop/README.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/07-multi-hop/README.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [ ] [Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/07-multi-hop/README.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [x] [Task #03 - UDP exchange between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki) @MrKevinWeiss
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] ~~Task #09 - deprecated~~
  - [x] ~~Task #10 - deprecated~~
  - [ ] [Task #11 - UDP exchange between iotlab-m3 and Zephyr](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr)
  - [ ] [Task #12 - ICMPv6 echo between Border Router with WiFi uplink to named Internet host](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-12---icmpv6-echo-between-border-router-with-wifi-uplink-to-named-internet-host)
  - [ ] [Task #13 - ICMPv6 echo between ESP and named Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/08-interop/README.md#task-13---icmpv6-echo-between-esp-and-named-internet-host-through-linux-with-6lowpan)
- [x] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/09-coap/README.md)
  - [x] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/09-coap/README.md#task-01---cord-endpoint) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/09-coap/README.md#task-02---confirmable-retries) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/09-coap/README.md#task-03---block1) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/09-coap/README.md#task-04---block2) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/09-coap/README.md#task-05---observe-registration-and-notification) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [x] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md)
  - [x] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-07---packet-too-big) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
- [x] [11-lorawan](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md)
  - [x] [Task #01 - LoRaWAN example](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md#task-01---lorawan-example) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #02 - OTAA join procedure](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md#task-02---otaa-join-procedure) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #03 - ABP join procedure](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md#task-03---abp-join-procedure) @jia200x
  - [x] [Task #04 - LoRaWAN device parameters persistence](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence) @riot-ci (see https://github.com/RIOT-OS/Release-Specs/issues/253#issuecomment-1186946987) 
  - [x] [Task #05 - GNRC LoRaWAN (Over The Air Activation)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md#task-05---gnrc-lorawan-over-the-air-activation) @jia200x
  - [x] [~Task #06 - GNRC LoRaWAN (ABP)~](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/11-lorawan/README.md#task-06---gnrc-lorawan-abp) (see https://github.com/RIOT-OS/RIOT/issues/16962)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/99-compile-and-test-one-board/README.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares)

**Comment by MrKevinWeiss** [comment]
Normally @jia200x runs the LoRa tests (task 11).  I think there are some issues with the required network for the autotests to work.

**Comment by MrKevinWeiss** [comment]
Maybe we can ask @miri64 to take a look a[04. Task 10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) as it seems like it is failing now but was passing the last release.

**Comment by chrysn** [comment]
The fragmentation one I'm just looking into (although admittedly more to understand better how they are run; when it comes to the actual issue it's likely I'd indeed need her help).

**Comment by MrKevinWeiss** [comment]
I will try to run (or kindly ask HAW people to run)  the interop tests.

**Comment by miri64** [comment]
> Maybe we can ask @miri64 to take a look a[04. Task 10 (Experimental) - ICMPv6 echo with large payload (IPv6 fragmentation)](https://github.com/RIOT-OS/Release-Specs/blob/86f21188954683c16429d18de57a75332208f8ce/04-single-hop-6lowpan-icmp/README.md#task-10-experimental---icmpv6-echo-with-large-payload-ipv6-fragmentation) as it seems like it is failing now but was passing the last release.

From the [test report](https://github.com/RIOT-OS/RIOT/runs/7386065381?check_suite_focus=true#step:14:429) it looks like, that the test already failed in the flashing stage. So probably just a communication error with the testbed. Should pass in the next run (we can also just restart the workflow to see if it works this time).

**Comment by miri64** [comment]
<h1>Test Report</h1>


<table>
  <thead>
    <tr><th></th><th>Task</th><th>Outcome</th></tr>
  </thead>
  <tbody>
  </tbody>
</table>

**Comment by miri64** [comment]
(I used `tox -e test -- -k "spec04 and task10"` to locally test)

**Comment by MrKevinWeiss** [comment]
[arduino-mega2560 failures](https://gist.github.com/MrKevinWeiss/2a1ddbdf5655947adee81f1292cd4031)

**Comment by MrKevinWeiss** [comment]
[pba-d-01-kw2x failures](https://gist.github.com/MrKevinWeiss/2a1ddbdf5655947adee81f1292cd4031)

**Comment by jia200x** [comment]
<details><summary>11. Task 03 - ABP join procedure - PASS</summary>

```
> loramac set dr 5
loramac set dr 5
> loramac set rx2_dr 3
loramac set rx2_dr 3
> loramac join abp
loramac join abp
Join procedure succeeded!
> loramac tx RIOT hola uncnf 123
loramac tx RIOT hola uncnf 123
Usage: loramac tx <payload> [<cnf|uncnf>] [port]
> loramac tx RIOT uncnf 123
loramac tx RIOT uncnf 123
Message sent with success
> loramac tx RIOT uncnf 123
loramac tx RIOT uncnf 123
The Network Server has pending data
Message sent with success
> loramac tx RIOT cnf 123
loramac tx RIOT cnf 123
Received ACK from network
Message sent with success
> loramac set dr 4   
loramac set dr 4
> loramac tx RIOT uncnf 123
loramac tx RIOT uncnf 123
Message sent with success
> loramac set dr 0          
loramac set dr 0
> loramac tx RIOT cnf 123
loramac tx RIOT cnf 123
Received ACK from network
Message sent with success
>   
```
</details>

**Comment by jia200x** [comment]
<details><summary>Task 05 - GNRC LoRaWAN (Over The Air Activation) - PASS </summary>

```
> ifconfig
ifconfig
Iface  3  HWaddr: 26:0B:69:B5  Frequency: 868500000Hz  RSSI: -157  BW: 125kHz  SF: 12  CR: 4/5  Link: up 
           TX-Power: 14dBm  State: SLEEP  Demod margin.: 0  Num gateways.: 0 
          IQ_INVERT  
          RX_SINGLE  OTAA  L2-PDU:767  
          
> help
help
Command              Description
---------------------------------------
ifconfig             Configure network interfaces
pm                   interact with layered PM subsystem
reboot               Reboot the node
txtsnd               Sends a custom string as is over the link layer
version              Prints current RIOT_VERSION
> help        
help
Command              Description
---------------------------------------
ifconfig             Configure network interfaces
pm                   interact with layered PM subsystem
reboot               Reboot the node
txtsnd               Sends a custom string as is over the link layer
version              Prints current RIOT_VERSION
> ifconfig 3 -ack_req
ifconfig 3 -ack_req
success: unset option
> txtsnd 3 01 RIOT
txtsnd 3 01 RIOT
> PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
00000000  DE  AD  BE  EF
~~ SNIP  1 - size:   9 byte, type: NETTYPE_NETIF (-1)
if_pid: 3  rssi: -32768  lqi: 0
flags: 0x0
src_l2addr: (nil)
dst_l2addr: 02
~~ PKT    -  2 snips, total size:  13 byte
ifconfig 3 set dr 5
ifconfig 3 set dr 5
success: set datarate on interface 3 to 5
> ifconfig 3 ack_req
ifconfig 3 ack_req
success: set option
> txtsnd 3 01 RIOT
txtsnd 3 01 RIOT
> txtsnd 01 RIOT
txtsnd 01 RIOT
usage: txtsnd <if> [<L2 addr>|bcast] <data>
> txtsnd 3 01 RIOT
txtsnd 3 01 RIOT
> 
```
</details>

**Comment by jia200x** [comment]
All (available) LoRaWAN test passed!
