### ISSUE TITLE
02-tests/task 02 Release 2016.10 - RC3

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/Release-Specs#26]
# Task # 02
## Perform a subset of tests on [`iotlab-m3`](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-IoT-LAB-M3) node:
- [ ] bitarithm_timings
- [x] bloom_bytes OK but don't know if the output is right:
```console
INFO # checking 10000 elements took 2145ms
INFO # 
INFO # 267 elements probably in the filter.
INFO # 9733 elements not in the filter.
INFO #  false positive rate.
INFO # 
INFO # All done!
```
- [ ] coap
- [ ] conn_ip 
- [x] cpp11_condition_variable __OK__
- [ ] cpp11_mutex
- [x] cpp11_thread __OK__
- [ ] driver_adt7310
- [ ] driver_at30tse75x
- [x] driver_at86rf2xx __OK__
- [ ] driver_bh1750
- [x] driver_bmp180 __OK__ Results in error as expected
- [ ] driver_dht
- [ ] driver_enc28j60
- [ ] driver_encx24j600
- [x] driver_hdc1000 __OK__ Results in error as expected
- [ ] driver_hih6130
- [ ] driver_ina220
- [ ] driver_io1_xplained
- [x] driver_isl29020 __OK__
- [ ] driver_isl29125
- [ ] driver_kw2xrf
- [x] driver_l3g4200d __OK__
- [ ] driver_lis3dh
- [ ] driver_lis3mdl
- [ ] driver_lpd8808
- [x] driver_lps331ap __OK__
- [ ] driver_lsm303dlhc
- [ ] driver_mag3110
- [x] driver_mma8652 __OK__ Results in error as expected
- [ ] driver_mpl3115a2
- [ ] driver_mpu9150
- [x] driver_mq3 __OK__ Lectures are 0 since there's no sensor
- [ ] driver_nrf24l01p_lowlevel
- [ ] driver_nrfmin
- [ ] driver_nvram_spi
- [x] driver_pcd8544 __OK__
- [ ] driver_pir
- [ ] driver_servo
- [x] driver_si70xx __OK__ Results in error as expected
- [ ] driver_srf02
- [ ] driver_srf08
- [x] driver_tcs37727 __OK__ Results in error as expected
- [ ] driver_tmp006
- [ ] driver_xbee
- [x] emb6 __OK__
- [ ] fault_handler
- [ ] float 
- [x] fmt_print __OK__
- [ ] gnrc_ipv6_ext
- [ ] gnrc_sixlowpan
- [x] gnrc_sock_ip __OK__
- [x] gnrc_sock_udp __OK__
- [ ] irq
- [ ] leds
- [ ] libfixmath
- [x] lwip __OK__
- [ ] malloc
- [ ] minimal
- [x] mpu_stack_guard __OK__ Fails because iotlab-m3 is not whitelisted
- [x] msg_send_receive __OK__
- [ ] msg_try_receive
- [ ] mutex_order
- [x] mutex_unlock_and_sleep __OK__
- [ ] netdev2_test
- [ ] netstats_l2
- [x] nhdp __OK__ but fails in OS X
- [x] od __OK__
- [ ] periph_adc
- [ ] periph_cpuid
- [x] periph_dac __OK__ compiles and runs but there's no DAC for iotlab-m3
- [ ] periph_gpio
- [ ] periph_hwrng
- [x] periph_i2c __OK__ sensors work as expected
- [ ] periph_pwm
- [ ] periph_rtc
- [x] periph_rtt __OK__
- [ ] periph_spi
- [ ] periph_timer
- [x] periph_uart __OK__
- [ ] pipe
- [x] pkg_aversiveplusplus __OK__
- [ ] pkg_cmsis-dsp
- [x] pkg_jsmn __OK__
- [ ] pkg_micro-ecc
- [x] pkg_tiny-asn1 __OK__
- [ ] pkg_u8g2
- [x] posix_semaphore __OK__
- [ ] posix_sleep
- [ ] pthread
- [x] pthread_barrier __OK__
- [ ] pthread_cleanup
- [ ] pthread_condition_variable
- [x] pthread_cooperation __OK__
- [ ] pthread_rwlock
- [ ] pthread_tls
- [x] saul __OK__
- [ ] sched_testing
- [ ] shell
- [x] sizeof_tcb __OK__
- [ ] slip
- [ ] struct_tm_utility
- [x] thread_basic __OK__
- [ ] thread_cooperation
- [ ] thread_exit
- [x] thread_flags __OK__
- [ ] thread_flood
- [ ] thread_msg
- [x] thread_msg_avail __OK__
- [ ] thread_msg_block_wo_queue
- [ ] thread_msg_block_w_queue
- [x] thread_msg_seq __OK__
- [ ] warn_conflict
- [ ] xtimer_drift
- [x] xtimer_hang __OK__
- [ ] xtimer_longterm
- [ ] xtimer_msg
- [x] xtimer_msg_receive_timeout __OK__
- [ ] xtimer_now64_continuity
- [x] xtimer_periodic_wakeup __OK__
- [ ] xtimer_remove
- [x] xtimer_reset __OK__
- [ ] xtimer_shift_on_compare
- [ ] zep

This list is based on previous #23 with different test marked for this release. I also added the new ones which are systematically performed.

**Comment by kYc0o** [comment]
Some strange thing... when I flash any firmware I receive the output as `Version: 2017.01-devel ...` is this normal? @miri64 can you check?

**Comment by miri64** [comment]
> ... is this normal? @miri64 can you check?

Yes and I don't need to, but I can explain ;-) Have a look at what commit `2016.10-RC1` is pointing at:

```
$ git show --decorate 2016.10-RC1
commit f8ec2f1135271d015fa8e1d79b19d9db1135d2d4 (tag: 2017.01-devel, tag: 2016.10-RC1)
Merge: ee698f1 f87dd60
Author: Martine Lenders <authmillenon@gmail.com>
Date:   Tue Nov 1 16:05:09 2016 +0100

    Merge pull request #5997 from aabadie/nucleo_arduino_pinmap
    
    Provide arduino feature to Nucleo boards

```

That's the branching-of point of `2016.10-branch` from `master` (so the start of the new release). Since `2017.01-devel` is an annotated tag (for the very reason to be picked up by `git describe`) `git describe` picks up preferred to `2016.10-RC1` which only is a [lightweight tag][1]. As soon as we have a `2016.10` release (releases are annotated tags with some GitHub-specific web flavoring ;-)) we `git describe` will show the distance from that one.

[1]: https://git-scm.com/book/en/v2/Git-Basics-Tagging#Annotated-Tags

**Comment by miri64** [comment]
@cgundogan @OlegHahm can you look into the output of `tests/bloom_bytes`?

**Comment by miri64** [comment]
@kYc0o emb6 issue fixed in https://github.com/RIOT-OS/RIOT/pull/6045

**Comment by kYc0o** [comment]
Should I wait for RC2 to continue the tests?

**Comment by miri64** [comment]
Yes. Will create it tomorrow morning.

**Comment by miri64** [comment]
We are on RC3 already, so please continue with that one.

**Comment by kYc0o** [comment]
OK ça roule! :P

**Comment by kYc0o** [comment]
Kernel panic in `gnrc_sock_udp`:

```console
main(): This is RIOT! (Version: 2017.01-devel-22-g66dfb-bluelatex.saclay.inria.fr-HEAD)
Calling test_sock_udp_create__EADDRINUSE()
Calling test_sock_udp_create__EAFNOSUPPORT()
Calling test_sock_udp_create__EINVAL_addr()
Calling test_sock_udp_create__EINVAL_netif()
Calling test_sock_udp_create__no_endpoints()
Calling test_sock_udp_create__only_local()
Calling test_sock_udp_create__only_local_reuse_ep()
Calling test_sock_udp_create__only_remote()
Calling test_sock_udp_create__full()
Calling test_sock_udp_recv__EADDRNOTAVAIL()
Calling test_sock_udp_recv__EAGAIN()
Calling test_sock_udp_recv__ENOBUFS()
Calling test_sock_udp_recv__EPROTO()
Calling test_sock_udp_recv__ETIMEDOUT()
 * Calling sock_udp_recv()
 * (timed out with timeout 1000000)
Calling test_sock_udp_recv__socketed()
Calling test_sock_udp_recv__socketed_with_remote()
Calling test_sock_udp_recv__unsocketed()
Calling test_sock_udp_recv__unsocketed_with_remote()
Calling test_sock_udp_recv__with_timeout()
Calling test_sock_udp_recv__non_blocking()
Calling test_sock_udp_send__EAFNOSUPPORT()
Calling test_sock_udp_send__EINVAL_addr()
Calling test_sock_udp_send__EINVAL_netif()
Calling test_sock_udp_send__EINVAL_port()
Calling test_sock_udp_send__ENOTCONN()
Calling test_sock_udp_send__socketed_no_local_no_netif()
0x80011b5
*** RIOT kernel panic:
FAILED ASSERTION.

pid | name                 | state    Q | pri | stack ( used) | base       | current    
  - | isr_stack            | -        - |   - |   512 (  164) | 0x20000000 | 0x200001c8
  1 | idle                 | pending  Q |  15 |   256 (  128) | 0x20000464 | 0x200004e4 
  2 | main                 | running  Q |   7 |  1536 (  720) | 0x20000564 | 0x20000994 
  3 | ipv6                 | bl rx    _ |   4 |  1024 (  300) | 0x200011a0 | 0x20001474 
  4 | udp                  | bl rx    _ |   5 |  1024 (  256) | 0x20000d5c | 0x2000105c 
    | SUM                  |            |     |  4352 ( 1568)

*** halted.
```

**Comment by miri64** [comment]
that's a `FAILED ASSERTION`. Can you tell me which board you are using and which line the assertion fails (using http://doc.riot-os.org/group__core__util.html#ga2200149ba880bf26fed140bdcf318113)

**Comment by miri64** [comment]
Ah, got it already: 

```
tests/gnrc_sock_udp/main.c:455 => 0x8000319
```

And that's because the packet buffer is not empty nor clean:

```
(gdb) print *_first_unused 
$6 = {next = 0x0, size = 196}
(gdb) print *(gnrc_pktsnip_t *)(_pktbuf + 196)
$9 = {users = 0, next = 0x0, data = 0x20001bb8, size = 0, type = 88}
```

I'll try to find time to dig into this :-/

**Comment by miri64** [comment]
(probably related to https://github.com/RIOT-OS/RIOT/issues/4048?)

**Comment by kYc0o** [comment]
The release specs says that this tests should be done in an iotlab-m3, which is the one I'm using.

**Comment by kYc0o** [comment]
`POSIX_SEMAPHORE` fails at `TEST 4`:

```console
main(): This is RIOT! (Version: 2017.01-devel-22-g66dfb-bluelatex.saclay.inria.fr-HEAD)
######################### TEST1:
first: sem_init
first: thread create
first: thread created
first: sem_getvalue
first: sem_getvalue != 0
first: do yield
second: sem_trywait
second: sem_trywait failed
second: sem_trywait done with == 0
second: wait for post
first: done yield
first: sem_trywait
first: sem_trywait FAILED
first: sem_trywait done
first: sem_post
second: sem was posted
second: end
first: sem_post done
first: sem_destroy
first: end
######################### TEST2:
first: sem_init
first: thread create: 5
first: thread created: priority 5 (1/5)
first: thread create: 4
first: thread created: priority 4 (2/5)
first: thread create: 3
first: thread created: priority 3 (3/5)
first: thread create: 2
first: thread created: priority 2 (4/5)
first: thread create: 1
first: thread created: priority 1 (5/5)
------------------------------------------
post no. 0
Thread 'priority 1' woke up.
Back in main thread.
post no. 1
Thread 'priority 2' woke up.
Back in main thread.
post no. 2
Thread 'priority 3' woke up.
Back in main thread.
post no. 3
Thread 'priority 4' woke up.
Back in main thread.
post no. 4
Thread 'priority 5' woke up.
Back in main thread.
######################### TEST3:
m3-7;first: sem_init s1
first: sem_init s2
first: create thread 1
first: create thread 2
------------------------------------------
post s1
Thread 1 woke up after waiting for s1.
post s2
Thread 2 woke up after waiting for s2.
post s2
Thread 1 woke up after waiting for s2.
post s1
Thread 2 woke up after waiting for s1.
######################### TEST4:
first: sem_init s1
first: wait 1 sec for s1
first: timed out
first: waited only lu usec => FAILED
first: waited lu usec
######################### DONE
```

**Comment by kYc0o** [comment]
Just finished the tests on iotlab-m3 with these tests failing:

```
gnrc_sock_udp 
od
posix_semaphore
sizeof_tcb 
```

**Comment by miri64** [comment]
How do `od` and `sizeof_tcb` fail?

**Comment by kYc0o** [comment]
`sizeof_tcb` fails at the printing, the output is not formatted and only a "zu" is shown in the results.

`od` fails with a pointer which is out of the stack or something like this. I'll provide the exact output.

**Comment by kYc0o** [comment]
Well actually I don't know if it's an expected behaviour or an error, but after a big output of tests for several functions it ends by this:

```console
od(long_str, sizeof(long_str), OD_WIDTH_DEFAULT, OD_FLAGS_BYTES_INT | OD_FLAGS_LENGTH_8)
000000000Stack pointer corrupted, reset to top of stack
FSR/FAR:
 CFSR: 0x01000000
 HFSR: 0x40000000
 DFSR: 0x00000000
 AFSR: 0x00000000
Misc
EXC_RET: 0xfffffffd
```

**Comment by kYc0o** [comment]
I think it fails here:

```c
/* Test different 8-byte-wise byte formats */
    CALL(od(long_str, sizeof(long_str), OD_WIDTH_DEFAULT,
            OD_FLAGS_BYTES_INT | OD_FLAGS_LENGTH_8));
    CALL(od(long_str, sizeof(long_str), OD_WIDTH_DEFAULT,
            OD_FLAGS_BYTES_DECIMAL | OD_FLAGS_LENGTH_8));
    CALL(od(long_str, sizeof(long_str), OD_WIDTH_DEFAULT,
            OD_FLAGS_BYTES_UINT | OD_FLAGS_LENGTH_8));
    CALL(od(long_str, sizeof(long_str), OD_WIDTH_DEFAULT,
            OD_FLAGS_BYTES_HEX | OD_FLAGS_LENGTH_8));
```

**Comment by miri64** [comment]
For `sizeof_tcb` fix is provided in https://github.com/RIOT-OS/RIOT/pull/6078

**Comment by kYc0o** [comment]
Great thanks! testing asap.

**Comment by miri64** [comment]
For `posix_semaphore` fix is provided at https://github.com/RIOT-OS/RIOT/pull/6079

**Comment by miri64** [comment]
`od` and `gnrc_sock_udp` are a different game. Look into them now.

**Comment by miri64** [comment]
Interestingly enough, without optimization the error in `od` does not happen :-/

**Comment by miri64** [comment]
`od` "fixed" in https://github.com/RIOT-OS/RIOT/pull/6080

**Comment by miri64** [comment]
Turns out the issue with gnrc_sock_udp *was* related to https://github.com/RIOT-OS/RIOT/issues/5748. Here's a quick-fix: https://github.com/RIOT-OS/RIOT/pull/6084

**Comment by kYc0o** [comment]
Excellent, everything works well now. I'll move to the next task.

**Comment by miri64** [comment]
I hope you stay on RC3 for that! ;-) For `gnrc_sock_ip` (which I tested since I was working on `gnrc_sock_udp`) you might need https://github.com/RIOT-OS/RIOT/pull/6083. Otherwise this will fail, too. Will write a mail to devel and maintainers about the state of RC4. If you want to wait for that, before continuing testing RC3, I understand.

**Comment by kYc0o** [comment]
Yes! I'm on RC3. Yes I also looked at https://github.com/RIOT-OS/RIOT/pull/6083 and I can retest if needed.
Ok, I can wait for RC4 to move for the tests on samr21-xpro (task 03).

**Comment by miri64** [comment]
> Ok, I can wait for RC4 to move for the tests on samr21-xpro (task 03).

Might be still of use to prevent an RC5 ;-) Just saying :-).

**Comment by kYc0o** [comment]
I forgot `posix_semaphore` and got another error :/ :

```console
######################### TEST1:
first: sem_init
first: thread create
first: thread created
first: sem_getvalue
first: sem_getvalue != 0
first: do yield
second: sem_trywait
second: sem_trywait failed
second: sem_trywait done with == 0
second: wait for post
first: done yield
first: sem_trywait
first: sem_trywait FAILED
1first: sem_trywait done
first: sem_post
second: sem was posted
second: end
first: sem_post done
first: sem_destroy
first: end
```

**Comment by kYc0o** [comment]
Maybe the timeouts are too short?

**Comment by kYc0o** [comment]
(hit the bad button)

**Comment by miri64** [comment]
> Maybe the timeouts are too short?

what timeouts?

**Comment by miri64** [comment]
Are you sure this is a fail? The test script [expects exactly the output you provided](https://github.com/RIOT-OS/RIOT/blob/master/tests/posix_semaphore/tests/01-run.py#L16-L35)

**Comment by kYc0o** [comment]
Oups! just interpreted the failing message as a real failure, and I didn't look at such script. Then these tests are over.

**Comment by miri64** [comment]
Superseded by #35
