### ISSUE TITLE
02-tests/task 02 Release 2016.10 - RC4

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/Release-Specs#35]
# Task # 02
## Perform a subset of tests on [`iotlab-m3`](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-IoT-LAB-M3) node:
- [ ] bitarithm_timings
- [x] bloom_bytes OK but don't know if the output is right:
```console
INFO # checking 10000 elements took 2145ms
INFO # 
INFO # 267 elements probably in the filter.
INFO # 9733 elements not in the filter.
INFO #  false positive rate.
INFO # 
INFO # All done!
```
- [ ] coap
- [ ] conn_ip 
- [x] cpp11_condition_variable __OK__
- [ ] cpp11_mutex
- [x] cpp11_thread __OK__
- [ ] driver_adt7310
- [ ] driver_at30tse75x
- [x] driver_at86rf2xx __OK__
- [ ] driver_bh1750
- [x] driver_bmp180 __OK__ Results in error as expected
- [ ] driver_dht
- [ ] driver_enc28j60
- [ ] driver_encx24j600
- [x] driver_hdc1000 __OK__ Results in error as expected
- [ ] driver_hih6130
- [ ] driver_ina220
- [ ] driver_io1_xplained
- [x] driver_isl29020 __OK__
- [ ] driver_isl29125
- [ ] driver_kw2xrf
- [x] driver_l3g4200d __OK__
- [ ] driver_lis3dh
- [ ] driver_lis3mdl
- [ ] driver_lpd8808
- [x] driver_lps331ap __OK__
- [ ] driver_lsm303dlhc
- [ ] driver_mag3110
- [x] driver_mma8652 __OK__ Results in error as expected
- [ ] driver_mpl3115a2
- [ ] driver_mpu9150
- [x] driver_mq3 __OK__ Lectures are 0 since there's no sensor
- [ ] driver_nrf24l01p_lowlevel
- [ ] driver_nrfmin
- [ ] driver_nvram_spi
- [x] driver_pcd8544 __OK__ Runs but no display to test
- [ ] driver_pir
- [ ] driver_servo
- [x] driver_si70xx __OK__ Results in error as expected
- [ ] driver_srf02
- [ ] driver_srf08
- [x] driver_tcs37727 __OK__ Results in error as expected
- [ ] driver_tmp006
- [ ] driver_xbee
- [x] emb6 __OK__
- [ ] fault_handler
- [ ] float 
- [x] fmt_print __OK__
- [ ] gnrc_ipv6_ext
- [ ] gnrc_sixlowpan
- [x] gnrc_sock_ip __OK__
- [x] gnrc_sock_udp __OK__
- [ ] irq
- [ ] leds
- [ ] libfixmath
- [x] lwip __OK__
- [ ] malloc
- [ ] minimal
- [x] mpu_stack_guard __OK__ Shows failure because board is not whitelisted
- [x] msg_send_receive __OK__
- [ ] msg_try_receive
- [ ] mutex_order
- [x] mutex_unlock_and_sleep __OK__
- [ ] netdev2_test
- [ ] netstats_l2
- [x] nhdp __OK__ But build in OS X fails
- [x] od __OK__
- [ ] periph_adc
- [ ] periph_cpuid
- [x] periph_dac __OK__ But `periph_dac` module is not provided for iotlab-m3
- [ ] periph_gpio
- [ ] periph_hwrng
- [x] periph_i2c __OK__ All drivers work as expected
- [ ] periph_pwm
- [ ] periph_rtc
- [x] periph_rtt __OK__
- [ ] periph_spi
- [ ] periph_timer
- [x] periph_uart __OK__
- [ ] pipe
- [x] pkg_aversiveplusplus __OK__ But no servos attached to board
- [ ] pkg_cmsis-dsp
- [x] pkg_jsmn __OK__
- [ ] pkg_micro-ecc
- [x] pkg_tiny-asn1 __OK__
- [ ] pkg_u8g2
- [x] posix_semaphore __OK__
- [ ] posix_sleep
- [ ] pthread
- [x] pthread_barrier __OK__
- [ ] pthread_cleanup
- [ ] pthread_condition_variable
- [x] pthread_cooperation __OK__
- [ ] pthread_rwlock
- [ ] pthread_tls
- [x] saul __OK__
- [ ] sched_testing
- [ ] shell
- [x] sizeof_tcb __OK__
- [ ] slip
- [ ] struct_tm_utility
- [x] thread_basic __OK__
- [ ] thread_cooperation
- [ ] thread_exit
- [x] thread_flags __OK__
- [ ] thread_flood
- [ ] thread_msg
- [x] thread_msg_avail __OK__
- [ ] thread_msg_block_wo_queue
- [ ] thread_msg_block_w_queue
- [x] thread_msg_seq __OK__
- [ ] warn_conflict
- [ ] xtimer_drift
- [x] xtimer_hang __OK__
- [ ] xtimer_longterm
- [ ] xtimer_msg
- [x] xtimer_msg_receive_timeout __OK__
- [ ] xtimer_now64_continuity
- [x] xtimer_periodic_wakeup __OK__
- [ ] xtimer_remove
- [x] xtimer_reset __OK__
- [ ] xtimer_shift_on_compare
- [ ] zep

This list is based on previous #23 with different test marked for this release. I also added the new ones which are systematically performed.

**Comment by kYc0o** [comment]
All subset of tests succeeded.
