### ISSUE TITLE
02-tests/task 03 Release 2016.10 - RC4

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/Release-Specs#36]
# Task #02.03
## Perform a subset of tests on `samr21-xpro` node:
- [x] bitarithm_timings
- [x] bloom_bytes
- [x] coap
- [x] conn_ip
- [x] cpp11_condition_variable
- [x] cpp11_mutex
- [x] cpp11_thread
- [x] driver_at86rf2xx
- [x] driver_io1_xplained
- [x] fault_handler
- [x] float 
- [x] fmt_print
- [x] gnrc_ipv6_ext
- [x] gnrc_sixlowpan
- [x] gnrc_sock_ip
- [x] gnrc_sock_udp
- [x] irq
- [x] leds
- [x] libfixmath
- [x] malloc
- [x] minimal
- [x] msg_send_receive
- [x] msg_try_receive
- [x] mutex_order
- [x] netdev2_test
- [x] netstats_l2
- [x] nhdp
- [x] periph_cpuid
- [x] periph_gpio
- [x] periph_rtc
- [x] periph_spi
- [x] periph_timer
- [x] pipe
- [x] pkg_cmsis-dsp
- [x] pkg_micro-ecc [failed as expected since required feature is missing]
- [x] pkg_u8g2
- [x] posix_sleep
- [x] pthread
- [x] pthread_cleanup
- [x] pthread_condition_variable
- [x] pthread_rwlock
- [x] pthread_tls
- [x] sched_testing
- [x] shell
- [x] slip
- [x] struct_tm_utility
- [x] thread_cooperation
- [x] thread_exit
- [x] thread_flood
- [x] thread_msg
- [x] thread_msg_avail
- [x] thread_msg_block_wo_queue
- [x] thread_msg_block_w_queue
- [x] warn_conflict
- [x] xtimer_drift
- [x] xtimer_longterm
- [x] xtimer_msg
- [x] xtimer_now64_continuity
- [x] xtimer_remove

This list is based on previous #24 with different test marked for this release. I also added the new ones which are systematically performed.

**Comment by miri64** [comment]
I selected the tests using

```
ls -d tests/* | sort -R | head -n 65 | sort
```

```
tests/bloom_bytes
tests/coap
tests/conn_ip
tests/cpp11_condition_variable
tests/cpp11_thread
tests/driver_adt7310
tests/driver_bh1750
tests/driver_bmp180
tests/driver_dht
tests/driver_enc28j60
tests/driver_hdc1000
tests/driver_ina220
tests/driver_isl29125
tests/driver_mpl3115a2
tests/driver_mq3
tests/driver_nrf24l01p_lowlevel
tests/driver_nvram_spi
tests/driver_pcd8544
tests/driver_si70xx
tests/driver_srf02
tests/driver_srf08
tests/fault_handler
tests/fmt_print
tests/gnrc_sixlowpan
tests/gnrc_sock_udp
tests/irq
tests/lwip_sock_ip
tests/malloc
tests/minimal
tests/msg_try_receive
tests/netdev2_test
tests/nhdp
tests/od
tests/periph_adc
tests/periph_cpuid
tests/periph_pwm
tests/periph_rtt
tests/periph_spi
tests/periph_timer
tests/periph_uart
tests/pipe
tests/pkg_jsmn
tests/posix_semaphore
tests/pthread
tests/pthread_cleanup
tests/pthread_cooperation
tests/pthread_rwlock
tests/sched_testing
tests/sizeof_tcb
tests/slip
tests/struct_tm_utility
tests/thread_basic
tests/thread_exit
tests/thread_flood
tests/thread_msg
tests/thread_msg_avail
tests/thread_msg_block_w_queue
tests/thread_msg_seq
tests/warn_conflict
tests/xtimer_hang
tests/xtimer_msg
tests/xtimer_msg_receive_timeout
tests/xtimer_now64_continuity
tests/xtimer_periodic_wakeup
tests/zep
```

**Comment by miri64** [comment]
Ah, well I should probably exclude the driver tests that are not on that board  ;-) will test other stuff not tested instead https://github.com/RIOT-OS/Release-Specs/issues/26

**Comment by miri64** [comment]
The issue on native (https://github.com/RIOT-OS/Release-Specs/issues/34) seems not to be present on `samr21-xpro`

**Comment by miri64** [comment]
Oops, I read seconds.... Will test tomorrow more longterm.

**Comment by miri64** [comment]
Did it now after all... it freezes after 20 minutes also.
