### ISSUE TITLE
02-tests/task 02 Release 2017.01 - RC2

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/Release-Specs#40]
# Task # 02
## Perform a subset of tests on [`iotlab-m3`](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-IoT-LAB-M3) node:
- [x] bitarithm_timings
- [ ] bloom_bytes
- [ ] board_calliope-mini
- [x] board_microbit (**as expected:** whitelist works, headers are missing for this board)
- [ ] conn_ip
- [ ] cpp11_condition_variable
- [x] cpp11_mutex
- [ ] cpp11_thread
- [ ] driver_adt7310
- [x] driver_at30tse75x (**as expected:** calling/initializing in shell returns an error)
- [ ] driver_at86rf2xx
- [ ] driver_bh1750
- [x] driver_bme280 (**as expected:** returns initialization error after boot)
- [ ] driver_bmp180
- [ ] driver_dht
- [x] driver_enc28j60 (**as expected:** with no adaptor connected the device cannot be used, **Note:** the `ENC_RST` GPIO pin must be set to a different pin for this test, e.g. 0,7, since it conflicts with the onboard transceiver sleep pin)
- [ ] driver_encx24j600
- [ ] driver_hdc1000
- [x] driver_hih6130 (**as expected:** without attached  humidity sensor the communication fails)
- [ ] driver_ina220
- [ ] driver_io1_xplained
- [x] driver_isl29020
- [ ] driver_isl29125
- [ ] driver_jc42
- [x] driver_kw2xrf (**:boom:** the transceiver is not attached so fails initializing it, RIOT ends up in a **kernel panic** after the failed initialization)
- [ ] driver_l3g4200d
- [ ] driver_lis3dh
- [x] driver_lis3mdl (**as expected:** whitelist works, initializing the missing magnetometer fails)
- [ ] driver_lpd8808
- [ ] driver_lps331ap
- [x] driver_lsm303dlhc
- [ ] driver_mag3110
- [ ] driver_mma8x5x
- [x] driver_mpl3115a2 (**as expected:** the pressure sensor is not attached so initialization fails)
- [ ] driver_mpu9150
- [ ] driver_mq3
- [x] driver_nrf24l01p_lowlevel (**as expected:** the transceiver is not attached so initialization fails and the register reads always return -1)
- [ ] driver_nvram_spi
- [ ] driver_pcd8544
- [x] driver_pir  (**as expected:** no motion sensor is attached so initialization fails)
- [ ] driver_pn532
- [ ] driver_sdcard_spi
- [x] driver_servo (**as expected:** compilation fails since `periph_pwm` is not available on this board)
- [ ] driver_si70xx
- [ ] driver_srf02
- [x] driver_srf08 (**as expected:** no range sensor is mounted so we get no output)
- [ ] driver_tcs37727
- [ ] driver_tmp006
- [x] driver_xbee (**as expected:** no range sensor is mounted so we get no output)
- [ ] emb6
- [ ] fault_handler
- [x] float
- [ ] fmt_print
- [ ] gnrc_ipv6_ext
- [x] gnrc_sixlowpan (**seems that pexpect does not run correctly for me, @cgundogan succesfully ran the test**)
- [ ] gnrc_sock_ip
- [ ] gnrc_sock_udp
- [x] irq
- [ ] leds
- [ ] libfixmath
- [x] lwip (compiles, is flashable and ifconfig shows a device, but `make test` fails https://github.com/RIOT-OS/RIOT/issues/6533, calling `ps` in the shell spams a wall of garbage in the shell)
- [ ] lwip_sock_ip
- [ ] malloc
- [x] minimal
- [ ] mpu_stack_guard
- [ ] msg_send_receive
- [x] msg_try_receive
- [ ] mutex_order
- [ ] mutex_unlock_and_sleep
- [x] netdev2_test
- [ ] netstats_l2
- [ ] nhdp
- [x] od (**works as expected**, testrunner doesn't work for non-native boards)
- [ ] periph_adc
- [ ] periph_cpuid
- [x] periph_dac (**as expected:** no DAC is mounted so we get no output)
- [ ] periph_flashpage
- [ ] periph_gpio
- [x] periph_hwrng (**as expected:** we get warned and linking fails due to missing objects for the absent hwrng)
- [ ] periph_i2c
- [ ] periph_pwm
- [x] periph_rtc (**as expected:** we get warned and build fails without a peripheral realtime clock)
- [ ] periph_rtt
- [ ] periph_spi
- [x] periph_timer
- [ ] periph_uart
- [ ] pipe
- [x] pkg_aversiveplusplus (**as expected:** without attached servos the probing for them fails)
- [ ] pkg_cmsis-dsp
- [ ] pkg_jsmn
- [x] pkg_libcoap https://github.com/RIOT-OS/RIOT/pull/6536
- [ ] pkg_micro-ecc
- [ ] pkg_micro-ecc-with-hwrng
- [x] pkg_oonf_api https://github.com/RIOT-OS/RIOT/pull/6537
- [ ] pkg_tiny-asn1
- [ ] pkg_u8g2
- [x] posix_semaphore (**works as expected**, testrunner doesn't work for non-native boards)
- [ ] posix_sleep
- [ ] pthread
- [x] pthread_barrier
- [ ] pthread_cleanup
- [ ] pthread_condition_variable
- [x] pthread_cooperation
- [ ] pthread_rwlock
- [ ] pthread_tls
- [x] saul
- [ ] sched_testing
- [ ] shell
- [x] sizeof_tcb
- [ ] slip
- [ ] struct_tm_utility
- [x] thread_basic (**works as expected**, testrunner doesn't work for non-native boards)
- [ ] thread_cooperation
- [ ] thread_exit
- [x] thread_flags
- [ ] thread_flood
- [ ] thread_msg
- [x] thread_msg_avail
- [ ] thread_msg_block_wo_queue
- [ ] thread_msg_block_w_queue
- [x] thread_msg_seq
- [ ] warn_conflict
- [ ] xtimer_drift
- [x] xtimer_hang
- [ ] xtimer_longterm
- [ ] xtimer_msg
- [x] xtimer_msg_receive_timeout (**works as expected**, testrunner doesn't work for non-native boards)
- [ ] xtimer_now64_continuity
- [ ] xtimer_periodic_wakeup
- [x] xtimer_remove
- [ ] xtimer_reset
- [ ] xtimer_usleep
- [x] zep

list made manually by executing:

``` sh
ls -1a | sed  -e 's/^/- [ ] /'
```

in `RIOT/tests` and removing `unittests` et al. from the list
