### ISSUE TITLE
02-tests/task 03 Release 2017.01 - RC2

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/Release-Specs#41]
# Task # 03
### Perform a subset of tests (!= subset from [Task #02](https://github.com/RIOT-OS/Release-Specs/issues/40)) on [`samr21-xpro`](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-SAMR21-xpro) node:
- [x] bitarithm_timings
- [x] bloom_bytes
- [ ] board_calliope-mini
- [ ] board_microbit
- [x] conn_ip
- [ ] cpp11_condition_variable
- [ ] cpp11_mutex
- [x] cpp11_thread
- [ ] driver_adt7310
- [ ] driver_at30tse75x
- [x] driver_at86rf2xx
- [ ] driver_bh1750
- [ ] driver_bme280
- [ ] driver_bmp180
- [ ] driver_dht
- [ ] driver_enc28j60
- [ ] driver_encx24j600
- [ ] driver_hdc1000
- [ ] driver_hih6130
- [ ] driver_ina220
- [ ] driver_io1_xplained
- [ ] driver_isl29020
- [ ] driver_isl29125
- [ ] driver_jc42
- [ ] driver_kw2xrf
- [ ] driver_l3g4200d
- [ ] driver_lis3dh
- [ ] driver_lis3mdl
- [ ] driver_lpd8808
- [ ] driver_lps331ap
- [ ] driver_lsm303dlhc
- [ ] driver_mag3110
- [ ] driver_mma8x5x
- [ ] driver_mpl3115a2
- [ ] driver_mpu9150
- [ ] driver_mq3
- [x] driver_nrf24l01p_lowlevel
- [ ] driver_nvram_spi
- [ ] driver_pcd8544
- [ ] driver_pir
- [ ] driver_pn532
- [ ] driver_sdcard_spi
- [ ] driver_servo
- [ ] driver_si70xx
- [ ] driver_srf02
- [ ] driver_srf08
- [ ] driver_tcs37727
- [ ] driver_tmp006
- [ ] driver_xbee
- [x] emb6
- [x] fault_handler
- [ ] float
- [x] fmt_print
- [x] gnrc_ipv6_ext
- [ ] gnrc_sixlowpan
- [x] gnrc_sock_ip
- [x] gnrc_sock_udp
- [ ] irq
- [x] leds
- [x] libfixmath
- [x] libfixmath_unittests
- [ ] lwip
- [x] lwip_sock_ip
- [ ] Makefile.tests_common
- [ ] malloc
- [x] minimal
- [ ] mpu_stack_guard
- [x] msg_send_receive
- [ ] msg_try_receive
- [ ] mutex_order
- [x] mutex_unlock_and_sleep
- [ ] netdev2_test
- [x] netstats_l2
- [x] nhdp
- [ ] od
- [ ] periph_adc
- [x] periph_cpuid
- [ ] periph_dac
- [ ] periph_flashpage
- [x] periph_gpio
- [ ] periph_hwrng
- [ ] periph_i2c
- [x] periph_pwm
- [x] periph_rtc
- [x] periph_rtt
- [ ] periph_spi
- [x] periph_timer
- [ ] periph_uart
- [x] pipe
- [ ] pkg_aversiveplusplus
- [x] pkg_cmsis-dsp
- [ ] pkg_jsmn
- [ ] pkg_libcoap
- [x] pkg_micro-ecc
- [ ] pkg_micro-ecc-with-hwrng
- [ ] pkg_oonf_api
- [ ] pkg_tiny-asn1, (Repo currently down)
- [ ] pkg_u8g2
- [ ] posix_semaphore
- [x] posix_sleep
- [ ] pthread
- [ ] pthread_barrier
- [x] pthread_cleanup
- [ ] pthread_condition_variable
- [ ] pthread_cooperation
- [x] pthread_rwlock
- [ ] pthread_tls
- [ ] saul
- [x] sched_testing
- [ ] shell
- [x] sizeof_tcb
- [ ] slip
- [x] struct_tm_utility
- [ ] thread_basic
- [x] thread_cooperation
- [ ] thread_exit
- [x] thread_flags
- [ ] thread_flood
- [x] thread_msg
- [ ] thread_msg_avail
- [x] thread_msg_block_wo_queue
- [x] thread_msg_block_w_queue
- [ ] thread_msg_seq
- [x] warn_conflict
- [ ] xtimer_drift
- [x] xtimer_hang
- [ ] xtimer_longterm
- [x] xtimer_msg
- [ ] xtimer_msg_receive_timeout
- [x] xtimer_now64_continuity
- [x] xtimer_periodic_wakeup
- [x] xtimer_remove
- [ ] xtimer_reset
- [x] xtimer_usleep
- [ ] zep

list made manually by executing:

``` sh
ls -1a | sed  -e 's/^/- [ ] /'
```

in `RIOT/tests` and removing `unittests` et al. from the list
