### ISSUE TITLE
02-tests/task 01 Release 2018.01 - RC1

### ISSUE THREAD

**Issue by A-Paul** [RIOT-OS/Release-Specs#57]
- [x] bitarithm_timings **success**
- [x] bloom_bytes **success**
- [x] buttons **success**
- [ ] can_trx
- [x] cbor **success**
- [ ] conn_can
- [x] cpp11_condition_variable **success**
- [x] cpp11_mutex **success**
- [x] cpp11_thread **success**
- [x] driver_apa102
- [x] driver_dht
- [x] driver_grove_ledbar
- [x] driver_lpd8808 **not blacklisted, hangs**
- [x] driver_my9221 **not blacklisted, kernel panic** 
- [x] driver_pir **not blacklisted, init failed** 
- [x] driver_rn2xx3 **not blacklisted, kernel panic** 
- [x] driver_soft_spi **not blacklisted, hangs**
- [x] driver_xbee **not blacklisted, kernel panic** 
- [x] events **success**
- [x] evtimer_msg **success**
- [x] evtimer_underflow **success**
- [x] fault_handler **success**
- [x] float **success**
- [x] fmt_print **success**
- [x] gnrc_ipv6_ext **success**
- [ ] gnrc_ipv6_nib
- [ ] gnrc_ipv6_nib_6ln
- [x] gnrc_ndp **failed**, kernel panic, see https://github.com/RIOT-OS/RIOT/issues/8458
- [x] gnrc_netif **success**
- [x] gnrc_sixlowpan **success**
- [ ] gnrc_sock_dns
- [ ] gnrc_sock_ip
- [ ] gnrc_sock_udp
- [x] gnrc_udp **success**
- [x] irq **success**
- [ ] leds
- [x] libfixmath **success**
- [x] libfixmath_unittests **success**
- [ ] lwip
- [x] lwip_sock_ip **success**
- [x] lwip_sock_tcp **success**
- [x] lwip_sock_udp **success**
- [x] malloc **success**
- [x] minimal **success**
- [x] msg_avail **success**
- [x] msg_send_receive **success**
- [x] msg_try_receive **success**
- [x] mutex_order **success**
- [x] mutex_unlock_and_sleep **success**
- [ ] netstats_l2
- [x] od **success**
- [x] periph_cpuid **success**
- [ ] periph_gpio
- [x] periph_hwrng **failed**, see: https://github.com/RIOT-OS/RIOT/issues/8443
- [ ] periph_rtc
- [x] periph_timer **success**
- [x] periph_uart **success**
- [x] pipe **success**
- [x] pkg_fatfs **success**
- [x] pkg_fatfs_vfs **success**
- [ ] pkg_microcoap
- [x] pkg_minmea **success**
- [x] pkg_u8g2 **success**
- [x] pkg_umorse **success**
- [x] posix_semaphore **success**
- [x] posix_time **success**
- [x] ps_schedstatistics **success**
- [x] pthread **success**
- [x] pthread_barrier **success**
- [x] pthread_cleanup **success**
- [x] pthread_condition_variable **success**
- [x] pthread_cooperation **success**
- [x] pthread_rwlock **success**
- [x] pthread_tls **success**
- [x] rmutex **success**
- [ ] rng
- [x] saul **success**
- [x] sched_testing **success**
- [ ] sizeof_tcb
- [ ] slip
- [ ] sntp
- [x] socket_zep
- [ ] ssp
- [x] struct_tm_utility **success**
- [x] thread_basic **success**
- [x] thread_cooperation **success**
- [x] thread_exit **success**
- [x] thread_flags **success**
- [x] thread_flags_xtimer **success**
- [x] thread_flood **success**
- [x] thread_msg **success**
- [x] thread_msg_block_wo_queue **success**
- [x] thread_msg_block_w_queue **success**
- [x] thread_msg_seq **success**
- [x] thread_priority_inversion **failed**, hangup , see https://github.com/RIOT-OS/RIOT/issues/8444
- [x] trickle **success**
- [x] xtimer_drift **success**
- [x] xtimer_hang **success**
- [x] xtimer_longterm **success**
- [x] xtimer_msg **success**
- [x] xtimer_msg_receive_timeout **success**
- [x] xtimer_now64_continuity **success**
- [x] xtimer_periodic_wakeup **success**
- [x] xtimer_remove **success**
- [x] xtimer_reset **success**
- [x] xtimer_usleep **success**
- [x] xtimer_usleep_short **success**

All performed tests have a checkmark and are either success, failed (with short comment) or have an unclear result (at least for me).

**Comment by smlng** [comment]
outdated by #59
