### ISSUE TITLE
02-tests/task 01 Release 2018.01 - R2

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/Release-Specs#59]
First checkbox marks a tests as run. Second (sub) checkbox indicates success, please add comment on failure.

- [x] **bitarithm_timings**
  - [x] success?
- [x] **bloom_bytes**
  - [x] success?
- [x] ~~**board_calliope-mini**~~
  - [ ] success? does not work with native
- [x] ~~**board_microbit**~~
  - [ ] success? does not work with native
- [x] **buttons**
  - [ ] success? native has no buttons
- [x] **can_trx**
  - [x] success? No README or auto test script, unclear what to do.
- [x] **cbor**
  - [x] success?
- [x] **conn_can**
  - [x] success? But no CAN devices available on native
- [x] **cpp11_condition_variable**
  - [x] success?
- [x] **cpp11_mutex**
  - [x] success?
- [x] **cpp11_thread**
  - [x] success?
- [x] ~~**driver_adcxx1c**~~
  - [ ] success? missing feature
- [x] ~~**driver_adt7310**~~
  - [ ] success? missing feature
- [x] ~~**driver_adxl345**~~
  - [ ] success? missing feature
- [x] ~~**driver_apa102**~~
  - [ ] success?
- [x] ~~**driver_at30tse75x**~~
  - [ ] success? missing feature
- [x] ~~**driver_at86rf2xx**~~
  - [ ] success? missing feature
- [x] ~~**driver_ata8520e**~~
  - [ ] success? missing feature
- [x] ~~**driver_bh1750**~~
  - [ ] success? missing feature
- [x] ~~**driver_bmp180**~~
  - [ ] success? missing feature
- [x] ~~**driver_bmx280**~~
  - [ ] success? missing feature 
- [x] **driver_dht**
  - [x] success? Still, makes no sense on native
- [x] ~~**driver_ds1307**~~
  - [ ] success? missing feature
- [x] ~~**driver_dsp0401**~~
  - [ ] success? missing feature
- [x] **driver_dynamixel**
  - [x] success? Still, makes no sense on native
- [x] ~~**driver_enc28j60**~~
  - [ ] success? missing feature
- [x] ~~**driver_encx24j600**~~
  - [ ] success? missing feature
- [x] **driver_feetech**
  - [x] success? Still, makes no sense on native
- [x] **driver_grove_ledbar**
  - [ ] success? Makes no sense on native, no device connected
- [x] ~~**driver_hd44780**~~
  - [ ] success? missing feature
- [x] ~~**driver_hdc1000**~~
  - [ ] success? missing feature
- [x] ~~**driver_hih6130**~~
  - [ ] success? missing feature
- [x] ~~**driver_hts221**~~
  - [ ] success? missing feature
- [x] ~~**driver_ina220**~~
  - [ ] success? missing feature
- [x] ~~**driver_io1_xplained**~~
  - [ ] success? missing feature
- [x] ~~**driver_isl29020**~~
  - [ ] success? missing feature
- [x] ~~**driver_isl29125**~~
  - [ ] success? missing feature
- [x] ~~**driver_jc42**~~
  - [ ] success? missing feature
- [x] ~~**driver_kw2xrf**~~
  - [ ] success? missing feature
- [x] ~~**driver_l3g4200d**~~
  - [ ] success? missing feature
- [x] ~~**driver_lc709203f**~~
  - [ ] success? missing feature 
- [x] ~~**driver_lis2dh12**~~
  - [ ] success? missing feature
- [x] ~~**driver_lis3dh**~~
  - [ ] success? missing feature 
- [x] ~~**driver_lis3mdl**~~
  - [ ] success? missing feature
- [x] **driver_lpd8808**
  - [x] success?Makes no sense on native, no device connected
- [x] ~~**driver_lps331ap**~~
  - [ ] success? missing feature
- [x] ~~**driver_lsm303dlhc**~~
  - [ ] success? missing feature 
- [x] ~~**driver_lsm6dsl**~~
  - [ ] success? missing feature
- [x] ~~**driver_mag3110**~~
  - [ ] success? missing feature
- [x] ~~**driver_mma7660**~~
  - [ ] success? missing feature
- [x] ~~**driver_mma8x5x**~~
  - [ ] success? missing feature
- [x] ~~**driver_mpl3115a2**~~
  - [ ] success? missing feature
- [x] ~~**driver_mpu9150**~~
  - [ ] success? missing feature
- [x] ~~**driver_mq3**~~
  - [ ] success? missing feature
- [x] **driver_my9221**
  - [ ] success?  Makes no sense on native, no device connected
- [x] ~~**driver_nrf24l01p_lowlevel**~~
  - [ ] success? missing feature
- [x] ~~**driver_nvram_spi**~~
  - [ ] success? missing feature
- [x] ~~**driver_pcd8544**~~
  - [ ] success? missing feature
- [x] **driver_pir**
  - [ ] success? Makes no sense on native, no device connected
- [x] ~~**driver_pn532**~~
  - [ ] success? missing feature
- [x] **driver_rn2xx3**
  - [ ] success? Makes no sense on native, no device connected
- [x] ~~**driver_sdcard_spi**~~
  - [ ] success? missing feature
- [x] ~~**driver_servo**~~
  - [ ] success? missing feature
- [x] ~~**driver_si70xx**~~
  - [ ] success? missing feature
- [x] **driver_soft_spi**
  - [x] success?
- [x] ~~**driver_srf02**~~
  - [ ] success? missing feature
- [x] ~~**driver_srf08**~~
  - [ ] success? missing feature
- [x] ~~**driver_sx127x**~~
  - [ ] success? missing feature
- [x] ~~**driver_tcs37727**~~
  - [ ] success? missing feature
- [x] ~~**driver_tmp006**~~
  - [ ] success? missing feature
- [x] ~~**driver_tsl2561**~~
  - [ ] success? missing feature
- [x] ~~**driver_veml6070**~~
  - [ ] success? missing feature
- [x] **driver_xbee**
  - [ ] success? Failed assertion, but also makes no sense on native, no device connected
- [x] ~~**emb6**~~
  - [ ] success? missing feature
- [x] **events**
  - [x] success?
- [x] **evtimer_msg**
  - [x] success?
- [x] **evtimer_underflow**
  - [x] success?
- [x] **fault_handler**
  - [x] success? On Linux, but does not crash on macOS, just hangs after write to 0x0000
- [x] **float**
  - [x] success?
- [x] **fmt_print**
  - [x] success?
- [x] **gnrc_ipv6_ext**
  - [x] success?
- [x] **gnrc_ipv6_nib**
  - [x] success? Needs fix in #8480
- [x] **gnrc_ipv6_nib_6ln**
  - [x] success? Needs fix in #8480
- [x] **gnrc_ndp**
  - [x] success?
- [x] **gnrc_netif**
  - [x] success? Works on Linux, but fails on macOS see https://github.com/RIOT-OS/RIOT/issues/8476
- [x] **gnrc_sixlowpan**
  - [x] success?
- [x] **gnrc_sock_dns**
  - [x] success?
- [x] **gnrc_sock_ip**
  - [x] success?
- [x] **gnrc_sock_udp**
  - [x] success?
- [ ] **gnrc_tcp_client**
  - [ ] success?
- [ ] **gnrc_tcp_server**
  - [ ] success?
- [x] **gnrc_udp**
  - [x] success?
- [x] ~~**gomach**~~
  - [ ] success? native not supported
- [x] **irq**
  - [x] success?
- [x] **leds**
  - [x] success?
- [x] **libfixmath**
  - [x] success?
- [x] **libfixmath_unittests**
  - [x] success?
- [x] **lwip**
  - [x] success?
- [x] **lwip_sock_ip**
  - [x] success?
- [x] **lwip_sock_tcp**
  - [x] success?
- [x] **lwip_sock_udp**
  - [x] success?
- [x] ~~**lwmac**~~
  - [ ] success? native not supported
- [x] **malloc**
  - [x] success?
- [x] ~~**mcuboot**~~
  - [ ] success? native not supported
- [x] **minimal**
  - [x] success?
- [x] ~~**mpu_stack_guard**~~
  - [ ] success? native not supported
- [x] **msg_avail**
  - [x] success?
- [x] **msg_send_receive**
  - [x] success?
- [x] **msg_try_receive**
  - [x] success?
- [x] **mutex_order**
  - [x] success? linux O.K, failes under OSX
- [x] **mutex_unlock_and_sleep**
  - [x] success?
- [x] **netdev_test**
  - [x] success? Fails with DEVELHELP=1
- [x] **netstats_l2**
  - [x] success?
- [x] **nhdp**
  - [x] success?
- [x] **od**
  - [x] success?
- [x] ~~**openthread**~~
  - [ ] success? native not supported
- [x] ~~**periph_adc**~~
  - [ ] success? native not supported
- [x] **periph_cpuid**
  - [x] success?
- [x] ~~**periph_dac**~~
  - [ ] success? native not supported
- [x] ~~**periph_flashpage**~~
  - [ ] success? native not supported
- [x] **periph_gpio**
  - [x] success?
- [x] ~~**periph_gpio_arduino**~~
  - [ ] success? native not supported
- [x] **periph_hwrng**
  - [x] success?
- [x] ~~**periph_i2c**~~
  - [ ] success? native not supported
- [x] ~~**periph_pwm**~~
  - [ ] success? native not supported
- [x] **periph_rtc**
  - [ ] success? fails, as expected, alarm not implemented 
- [x] ~~**periph_rtt**~~ 
  - [ ] success? native not supported
- [x] ~~**periph_spi**~~
  - [ ] success? native not supported
- [x] **periph_timer**
  - [x] success?
- [x] **periph_uart**
  - [x] success?
- [x] **pipe**
  - [x] success?
- [ ] ~~**pkg_cmsis-dsp**~~
  - [ ] success? native not supported
- [x] **pkg_fatfs**
  - [x] success?
- [x]  #**pkg_fatfs_vfs**
  - [x] success?
- [x] **pkg_jsmn**
  - [x] success?
- [x] **pkg_libcoap**
  - [x] success?
- [x] **pkg_micro-ecc**
  - [x] success?
- [x] **pkg_micro-ecc-with-hwrng**
  - [x] success?
- [x] **pkg_microcoap**
  - [x] success?
- [x] **pkg_minmea**
  - [x] success?
- [x] **pkg_oonf_api**
  - [x] success?
- [x] ~~**pkg_semtech-loramac**~~
  - [ ] success? native not supported
- [x] **pkg_tiny-asn1**
  - [x] success?
- [x] **pkg_u8g2**
  - [x] success?
- [x] **pkg_umorse**
  - [x] success?
- [x] **posix_semaphore**
  - [x] success?
- [x] **posix_time**
  - [x] success?
- [x] **ps_schedstatistics**
  - [x] success?
- [x] **pthread**
  - [x] success?
- [x] **pthread_barrier**
  - [x] success?
- [x] **pthread_cleanup**
  - [x] success?
- [x] **pthread_condition_variable**
  - [x] success?
- [x] **pthread_cooperation**
  - [x] success?
- [x] **pthread_rwlock**
  - [x] success?
- [x] **pthread_tls**
  - [x] success?
- [x] **rmutex**
  - [x] success?
- [x] **rng**
  - [x] success?
- [x] **saul**
  - [x] success?
- [x] **sched_testing**
  - [x] success?
- [x] **shell**
  - [x] success?
- [x] **sizeof_tcb**
  - [x] success?
- [x] **slip**
  - [x] success?
- [x] **sntp**
  - [x] success?
- [x] **socket_zep**
  - [x] success?
- [x] **ssp**
  - [x] success?
- [x] **struct_tm_utility**
  - [x] success?
- [x] **thread_basic**
  - [x] success?
- [x] **thread_cooperation**
  - [x] success?
- [x] **thread_exit**
  - [x] success?
- [x] **thread_flags**
  - [x] success?
- [x] **thread_flags_xtimer**
  - [x] success?
- [x] **thread_flood**
  - [x] success?
- [x] **thread_msg**
  - [x] success?
- [x] **thread_msg_block_w_queue**
  - [x] success?
- [x] **thread_msg_block_wo_queue**
  - [x] success?
- [x] **thread_msg_seq**
  - [x] success?
- [x] **thread_priority_inversion**
  - [ ] success? fails as expected
- [x] **trickle**
  - [x] success?
- [x] **unittests**
  - [x] success?
- [x] ~~**warn_conflict**~~
  - [ ] success? native not supported
- [x] **xtimer_drift**
  - [ ] success?
- [x] **xtimer_hang**
  - [x] success?
- [x] **xtimer_longterm**
  - [x] success?
- [x] **xtimer_msg**
  - [x] success?
- [x] **xtimer_msg_receive_timeout**
  - [x] success?
- [x] **xtimer_now64_continuity**
  - [x] success?
- [x] **xtimer_periodic_wakeup**
  - [x] success?
- [x] **xtimer_remove**
  - [x] success?
- [x] **xtimer_reset**
  - [x] success?
- [x] **xtimer_usleep**
  - [x] success?
- [x] **xtimer_usleep_short**
  - [x] success?

**Comment by smlng** [comment]
`tests/driver_xbee` failes on native as expected, with:

```
/RIOT/tests/driver_xbee/bin/native/tests_driver_xbee.elf  
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

drivers/xbee/xbee.c:478 => 0x2c0c
*** RIOT kernel panic:
FAILED ASSERTION.

*** halted.


native: exiting
```

**Comment by smlng** [comment]
`tests/mutex_order` fails with:

```
/RIOT/tests/mutex_order/bin/native/tests_mutex_order.elf   
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2018.04-devel-93-gac578-mobi25.inet.haw-hamburg.de-fix_tests_180129)
Mutex order test
Please refer to the README.md for more information

T3 (prio 6): trying to lock mutex now
T4 (prio 4): trying to lock mutex now
T5 (prio 0): trying to lock mutex now
T6 (prio 2): trying to lock mutex now
T7 (prio 1): trying to lock mutex now
T5 (prio 0): locked mutex now
T7 (prio 1): locked mutex now
Unexpected end of file in expect script at "child.expect(u"T\d+ \(prio (\d+)\): locked mutex now")" (tests/mutex_order/tests/01-run.py:28)

Process already stopped
make: *** [test] Error 1
```

**Comment by smlng** [comment]
`tests/netdev_test` fails when DEVELHELP=1 (hence might be expected @miri64 ?) with 

```
/RIOT/tests/netdev_test/bin/native/tests_netdev_test.elf   
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2018.04-devel-29-g8a60f-mobi1.inet.haw-hamburg.de-HEAD)
sys/net/gnrc/netif/gnrc_netif.c:1157 => 0x804ade1
*** RIOT kernel panic:
FAILED ASSERTION.

*** halted.


native: exiting
Unexpected end of file in expect script at "child.expect_exact('Executing test_get_addr()')" (tests/netdev_test/tests/01-run.py:14)

Process already stopped
Makefile:21: recipe for target 'test' failed
make: *** [test] Error 1
```

but succeeds with DEVELHELP=0

**Comment by smlng** [comment]
`tests/periph_rtc` fails, as it does not fire alarm 4x every 2s as expected

**Comment by smlng** [comment]
`tests/posix_semaphore` runs on Linux, but fails on macOS with:

```
/RIOT/tests/posix_semaphore/bin/native/tests_posix_semaphore.elf   
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2018.04-devel-93-gac578-mobi25.inet.haw-hamburg.de-fix_tests_180129)
######################### TEST1:
first: sem_init
first: thread create
first: thread created
first: sem_getvalue
first: sem_getvalue != 0
first: do yield
second: sem_trywait
second: sem_trywait failed
second: sem_trywait done with == 0
second: wait for post
first: done yield
first: sem_trywait
first: sem_trywait FAILED
first: sem_trywait done
first: sem_post
second: sem was posted
second: end
first: sem_post done
first: sem_destroy
first: end
######################### TEST2:
first: sem_init
first: thread create: 5
first: thread created: priority 5 (1/5)
first: thread create: 4
first: thread created: priority 4 (2/5)
first: thread create: 3
first: thread created: priority 3 (3/5)
first: thread create: 2
first: thread created: priority 2 (4/5)
first: thread create: 1
first: thread created: priority 1 (5/5)
------------------------------------------
post no. 0
Thread 'priority 1' woke up.
Unexpected end of file in expect script at "term.expect_exact("Back in main thread.")" (tests/posix_semaphore/tests/01-run.py:52)

Process already stopped
make: *** [test] Error 1
```

**Comment by smlng** [comment]
`tests/pthread_rwlock` works on Linux, but fails macOS, i.e. exits after second thread finished

**Comment by smlng** [comment]
`tests/rmutex` works on Linux, but fails on macOS, i.e. stops/exists after T4

**Comment by smlng** [comment]
`tests/thread_cooperations` works on Linux, but fails on macOS, i.e., exists before completion

**Comment by smlng** [comment]
same for `tests/thread_exit`

**Comment by smlng** [comment]
`tests/threag_flags` works on Linux, but fails on macOS with slightly too high delay

**Comment by smlng** [comment]
`tests/thread_msg_seq` works on Linux, but fails on macOS, i.e., exists before completion

**Comment by smlng** [comment]
`tests/xtimer_drift` fails on Linux after some time, and on macOS, too. But, on macOS very quickly (<20s) and with higher drift and jitter.

**Comment by miri64** [comment]
@smlng can you please open issues in the RIOT repository for your findings? I'm already starting to loose track.

**Comment by miri64** [comment]
> tests/driver_xbee failes on native as expected, 

If you run `native` on Raspberry Pi you can expose its UART to use xbee.

**Comment by miri64** [comment]
> tests/netdev_test fails when DEVELHELP=1 (hence might be expected @miri64 ?) with

The whole point of this test is to test the `netdev_test` framework, so having assertions about the device it might not fulfill is bad, so yes.

**Comment by miri64** [comment]
Regarding the other tests: I'm not sure they ever were run on MacOS... But it might be a hint that the RIOT scheduler backend for native on MacOS is broken.

**Comment by miri64** [comment]
>> tests/netdev_test fails when DEVELHELP=1 (hence might be expected @miri64 ?) with
>
> The whole point of this test is to test the `netdev_test` framework, so having assertions about the device it might not fulfill is bad, so yes.

See https://github.com/RIOT-OS/RIOT/pull/8485

**Comment by jia200x** [comment]
> tests/xtimer_drift fails on Linux after some time, and on macOS, too. But, on macOS very quickly (<20s) and with higher drift and jitter.

Maybe related to [RIOT-OS/RIOT#6442](https://github.com/RIOT-OS/RIOT/issues/6442)

**Comment by cladmi** [comment]
`tests/periph_rtc`: fails for good reason, 'rtc_set_time: not implemented'
`tests/mutex_order`: works for me on Linux.

**Comment by smlng** [comment]
@cladmi yeah saw that too

**Comment by smlng** [comment]
done
