### ISSUE TITLE
Release 2018.04 - RC2

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/Release-Specs#62]
This issue lists the status of all tests for the [Release Candidate 2 of the 2018.04](https://github.com/RIOT-OS/RIOT/releases/tag/2018.04-RC2) release.

Specs tested:
- [x] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/01-ci/01-ci.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/01-ci/01-ci.md#task-01) @kaspar030 (using murdock result)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/01-ci/01-ci.md#task-02) @kaspar030 (using murdock result)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/01-ci/01-ci.md#task-03) @kaspar030
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/01-ci/01-ci.md#task-04) @cladmi [link](https://github.com/RIOT-OS/RIOT/pull/9092#pullrequestreview-118000929)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/02-tests/02-tests.md)
  - [ ] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/02-tests/02-tests.md#task-01)
  - [ ] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/02-tests/02-tests.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/02-tests/02-tests.md#task-03)  [run by murdock](https://ci.riot-os.org/RIOT-OS/RIOT/2018.04-branch/latest/output.html)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03)
- [x] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03)
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04)
  - [x] [Task #05 (experimental)](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05)
  - [x] [Task #06 (experimental)](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06)
  - [x] [Task #07 (experimental)](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07) **[FAILED]**
  - [x] [Task #08 (experimental)](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08) **[FAILED]**
- [x] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/05-single-hop-route/05-single-hop-route.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/05-single-hop-route/05-single-hop-route.md#task-01) @kaspar030
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/05-single-hop-route/05-single-hop-route.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/05-single-hop-route/05-single-hop-route.md#task-03) @kaspar030
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/05-single-hop-route/05-single-hop-route.md#task-04) @kaspar030
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/06-single-hop-udp/06-single-hop-udp.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/06-single-hop-udp/06-single-hop-udp.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/06-single-hop-udp/06-single-hop-udp.md#task-02)
- [x] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/07-multi-hop/07-multi-hop.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/07-multi-hop/07-multi-hop.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/07-multi-hop/07-multi-hop.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/07-multi-hop/07-multi-hop.md#task-03)
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/07-multi-hop/07-multi-hop.md#task-04)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md)
  - [ ] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-02)
  - [ ] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-03)
  - [ ] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-04)
  - [ ] [Task #05](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-05)
  - [ ] [Task #06](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-06)
  - [x] [Task #07](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-07)
  - [ ] [Task #08](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-08)
  - [x] [Task #09](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-09)
  - [ ] [Task #10](https://github.com/RIOT-OS/Release-Specs/blob/1edc542c4e50e1c582d3cd437c6655050eabd6cf/08-interop/08-interop.md#task-10)

**Comment by kaspar030** [comment]
FYI, nightly build results are [here](https://ci.riot-os.org/RIOT-OS/RIOT/2018.04-branch/latest/output.html).

The changes to -RC1 are quite minimal (arduino and gcoap related only). What do you think, can we re-use the tests that were done (mostly by @aabadie) in #61 for -RC1? How did we handle that for the last releases?

**Comment by cladmi** [comment]
I am testing all tests that have `TESTS_ON_CI_WHITELIST`

The most important problem for the moment is that `unittests` fail for `iotlab-m3` and `iotlab-a8-m3` in the `tests-qDSA`I get a hardfault in the `keypair` function.

`wsn430` have errors too, some tests to fix and also other broken things. I will do a more detailed report.

**Comment by kaspar030** [comment]
> unittests fail for iotlab-m3 and iotlab-a8-m3 in the tests-qDSAI get a hardfault in the keypair function.

Can you try removing the LARGE_STACK_TESTS avr condition (so tests-qDSA is always "large stack")?

**Comment by cladmi** [comment]
I was testing them with all tests included so should already have been a `LARGE_STACK_TESTS`.
It is still broken with the following:

``` diff
-ifneq (, $(filter $(AVR_BOARDS), $(BOARD)))
-  LARGE_STACK_TESTS += tests-qDSA
-endif
+LARGE_STACK_TESTS += tests-qDSA
```

I will do the test report, a few fix PRs and I can start investigating.

**Comment by cladmi** [comment]
I ran test on tests/directory that are supported, with enough memory, and had the 'TEST_ON_CI_WHITELIST' tag.
I did run on wsn430-v1_4, iotlab-m3, and iotlab-a8-m3.
I was not using @kYc0o PR to add TEST_ON_CI_WHITELIST on other tests yet. It can be a next step to test more cases.

### Tests fixed on wsn430:

 * sizeof_tcb: needed different size as 16bit
 * mutex_unlock_and_sleep: increase timeout (test takes 10 minutes...)
 * bloom_bytes: increase timeeout
 * float: increase timeout

### Test broken on iotlab-m3 iotlab-a8-m3
 * unittests in the `qDSA` test

### Tests I have trouble running because the interactive test start before the board is ready

TODO: make the start condition more robust

 * iotlab-a8-m3:
    * rng
    * ps_schedsctatistics
    * shell
* wsn430:
    * struct_tm_utility, re-running it other time worked

### Tests not working on board

I think I should simply blacklist the wsn430 boards here

 * wsn430
     * pkg_micro-ecc: node reboot during test
        * no 16b support: https://github.com/kmackay/micro-ecc/issues/96
     * pkg_tiny-asn1: test says "could not allocate the memory for the ASN.1 objects"

### Board gets stuck during test
 * wsn430
    * bitarith_timings: stuck after first output of bitarithm_msb
    * rng: stuck at 'dump 10'
    * thread_flags_xtimer: never goes after "timeout 1"
    * all but one 'pthread_*" tests are broken, never gets after the first output line (pthread_rwlock works)
        * pthread
        * pthread_cooperation
        * pthread_cleanup
        * pthread_condition_variable
        * pthread_barrier
        * pthread_tls

**Comment by kaspar030** [comment]
> wsn430

That doesn't look very good. I guess msp430 needs quite some work overall...

**Comment by cladmi** [comment]
I put the PRs for wsn430 in the release milestone https://github.com/RIOT-OS/RIOT/milestone/22

**Comment by kaspar030** [comment]
I'm starting with the 05- tests on native now.

**Comment by kYc0o** [comment]
I'm on 6.

**Comment by kYc0o** [comment]
I'm on 7.

**Comment by kaspar030** [comment]
05- on native had some problems, see #63 and https://github.com/RIOT-OS/RIOT/issues/9061.

**Comment by kYc0o** [comment]
I'm struggling a lot with the RPL tests. I don't have a real clue what might be wrong, but then, should we stop the release until the problem is found?

**Comment by kYc0o** [comment]
For info, it seems broken since the last release. I'm having good results with 2017.10 with the same set of nodes and the same tests. The RPL graph also seems to be the same, but I'm not 100% sure.

**Comment by kaspar030** [comment]
> I'm struggling a lot with the RPL tests.

Can you elaborate what does not work? Maybe you're hitting a similar problem as in 05- on native. Try adding ```CFLAGS += -DGNRC_NETIF_IPV6_GROUPS_NUMOF=8``` to the Makefile.

**Comment by kYc0o** [comment]
> Can you elaborate what does not work? 

Single hop routes work sometimes, more than one hop it definitely doesn't work.

> Try adding CFLAGS += -DGNRC_NETIF_IPV6_GROUPS_NUMOF=8 to the Makefile.

I'm almost sure that's not the problem but I'll try and report back.

**Comment by kYc0o** [comment]
>> Try adding CFLAGS += -DGNRC_NETIF_IPV6_GROUPS_NUMOF=8 to the Makefile.

> I'm almost sure that's not the problem but I'll try and report back.

Just tested, the (unsuccessful) result is the same.

**Comment by cladmi** [comment]
My tests failing only on iotlab-a8-m3 where an issue in my test runner (https://github.com/RIOT-OS/RIOT/pull/9011#issuecomment-386370556). They are now just failing on the same as m3 nodes.

**Comment by miri64** [comment]
@kYc0o can you test with https://github.com/RIOT-OS/RIOT/pull/9073. Also make sure both the NIB off-link store (`GNRC_IPV6_NIB_OFFL_NUMOF`, for route destinations) and NIB on-link store (`GNRC_IPV6_NIB_NUMOF`, for route next-hops) is sufficiently large. For RPL to work properly `GNRC_IPV6_NIB_OFFL_NUMOF` should be at least `#nodes+1`.

**Comment by aabadie** [comment]
Tasks 4.7 and 4.8 are marked failed but I re-ran them on iotlab and got:
- 4.7: `1000 packets transmitted, 973 received, 3% packet loss, time 291.06369993 s`
- 4.8: `1000 packets transmitted, 992 received, 1% packet loss, time 441.06100079 s`

So they pass. Who tested them ?
I'm using the following command lines on the Arduino Zero node:

- for 4.7:
```
> ifconfig 7 set chan 17   # also on the samr21-xpro
> ping6 1000 ff02::1 50 100
```

- for 4.8:
```
> ifconfig 7 set chan 26   # also on the samr21-xpro
> ping6 1000 fe80::xx:xx:xx::1 100 100
```

**Comment by bergzand** [comment]
@miri64 I've tested a bit with 3 native instances (gnrc_networking) in a chain-like topology. Traffic between tap0 and tap2 is dropped to simulate a topology where node0 and node2 can communicate with node1, but node0 and node2 can't communicate.

Pinging between node0 and node2 doesn't work with both RPL and manual routing. What I observe is that when pinging from node0 to node2 is that node0 starts doing neighbour solicitations for the address of node2.

As soon as I remove the prefix from all nodes with `nib prefix del 6 2001:db8::/64` ping6 works again with multiple hops.

**Comment by miri64** [comment]
@bergzand I analized this with a debugger. Problem is, that routers in Ethernet configuration (IMHO correctly because we usually don't have a weird "mesh wants to share a prefix multihop"-situation there) advertise prefixes they configured as on-link using the L-flag in the [PIO](https://tools.ietf.org/html/rfc4861#section-4.6.2) (this happens [here](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ipv6/nib/nib_pl.c#L61-L65)). This causes the node to look up the address in the neighbor cache (as described in [RFC 4861](https://tools.ietf.org/html/rfc4861#section-5.2)) instead of the forwarding table. So I rather would say that either the scenario as described by you is invalid or we should have some extra state for RPL(-like) network interfaces, so that mesh-wide prefixing is allowed. But that is more a feature than a bug fix.

**Comment by miri64** [comment]
So won't fix, when it comes to that ;-).

**Comment by cgundogan** [comment]
>So won't fix, when it comes to that ;-).

Then we should say that we do not support multi-hop in native anymore, be it with RPL or not? It at least worked in previous RIOT versions so we are dropping that feature (for now)?

**Comment by miri64** [comment]
> Then we should say that we do not support multi-hop in native anymore, be it with RPL or not? It at least worked in previous RIOT versions so we are dropping that feature (for now)?

we support Multihop in native. Just not multihop prefix delegation. And that afaik was the case before as well and if not it was most definitely acting erroneously (so it was a bug, not a feature :P).

**Comment by kaspar030** [comment]
I've lost track. Can someone sum up what's the state with RPL and multihop regarding the release?

**Comment by kYc0o** [comment]
The two of RPL tests passed successfully. It was a matter of configuration since the max nib entries was too small for my experiment. Moreover, since the topology was a bit dense and maybe noisy some of the DAOs were lost during initialisation, therefore I decreased the DAOs send interval. Also Martine's #9073 helped to keep a coherent nib for that small interval (10 secs).

**Comment by kYc0o** [comment]
> Tasks 4.7 and 4.8 are marked failed but I re-ran them on iotlab and got:

For some strange reason, in the tag 2018.04-RC2 I have the following

```console
2018-05-07 12:26:16,104 - INFO #  main(): This is RIOT! (Version: 2018.04-snake.local-HEAD)
2018-05-07 12:26:16,108 - INFO # RIOT network stack example application
2018-05-07 12:26:16,110 - INFO # All up, running the shell now
ifconfig
2018-05-07 12:26:19,982 - INFO #  ifconfig
2018-05-07 12:26:20,031 - INFO # Iface  7  HWaddr: f8:54  Channel: 26  NID: 0x23
2018-05-07 12:26:20,033 - INFO #           Long HWaddr: 00:13:a2:00:40:a9:f8:d4 
2018-05-07 12:26:20,034 - INFO #           MTU:100  HL:64  RTR  
2018-05-07 12:26:20,036 - INFO #           Source address length: 8
2018-05-07 12:26:20,038 - INFO #           Link type: wireless
2018-05-07 12:26:20,043 - INFO #           inet6 addr: fe80::  scope: local  VAL
2018-05-07 12:26:20,046 - INFO #           inet6 group: ff02::2
2018-05-07 12:26:20,048 - INFO #           inet6 group: ff02::1
2018-05-07 12:26:20,052 - INFO #           inet6 group: ff02::301:ff00:0
2018-05-07 12:26:20,055 - INFO #           inet6 group: ff02::1a
2018-05-07 12:26:20,056 - INFO #           
2018-05-07 12:26:20,061 - INFO #            Protocol or device doesn't provide statistics.
2018-05-07 12:26:20,063 - INFO #           Statistics for IPv6
2018-05-07 12:26:20,071 - INFO #             RX packets 0  bytes 0
2018-05-07 12:26:20,076 - INFO #             TX packets 3 (Multicast: 3)  bytes 162
2018-05-07 12:26:20,081 - INFO #             TX succeeded 3 errors 0
2018-05-07 12:26:20,082 - INFO # 
```

And on branch 2018.04-devel

```console
2018-05-07 12:24:20,237 - INFO #  main(): This is RIOT! (Version: 2018.07-devel-1000-g7ea2b-snake.local-HEAD)
2018-05-07 12:24:20,240 - INFO # RIOT network stack example application
2018-05-07 12:24:20,243 - INFO # All up, running the shell now
> ifconfig
2018-05-07 12:24:25,500 - INFO #  ifconfig
2018-05-07 12:24:25,541 - INFO # Iface  7  HWaddr: f8:54  Channel: 26  NID: 0x23
2018-05-07 12:24:25,544 - INFO #           Long HWaddr: 00:13:a2:00:40:a9:f8:d4 
2018-05-07 12:24:25,548 - INFO #           MTU:1280  HL:64  RTR  
2018-05-07 12:24:25,549 - INFO #           IPHC  
2018-05-07 12:24:25,553 - INFO #           Source address length: 8
2018-05-07 12:24:25,555 - INFO #           Link type: wireless
2018-05-07 12:24:25,564 - INFO #           inet6 addr: fe80::213:a200:40a9:f8d4  scope: local  VAL
2018-05-07 12:24:25,565 - INFO #           inet6 group: ff02::2
2018-05-07 12:24:25,567 - INFO #           inet6 group: ff02::1
2018-05-07 12:24:25,570 - INFO #           inet6 group: ff02::301:ffa9:f8d4
2018-05-07 12:24:25,574 - INFO #           inet6 group: ff02::1a
2018-05-07 12:24:25,577 - INFO #           
2018-05-07 12:24:25,589 - INFO #            Protocol or device doesn't provide statistics.
2018-05-07 12:24:25,590 - INFO #           Statistics for IPv6
2018-05-07 12:24:25,591 - INFO #             RX packets 0  bytes 0
2018-05-07 12:24:25,594 - INFO #             TX packets 3 (Multicast: 3)  bytes 178
2018-05-07 12:24:25,595 - INFO #             TX succeeded 3 errors 0
2018-05-07 12:24:25,595 - INFO # 
```

That's why my tests failed.

**Comment by kaspar030** [comment]
So RPL basically works, but with the default settings, only with up to 8 nodes?

**Comment by kYc0o** [comment]
> So RPL basically works, but with the default settings, only with up to 8 nodes?

Exactly, the maximum number of neighbours is defined as:

`sys/include/net/gnrc/ipv6/nib/conf.h:#define GNRC_IPV6_NIB_OFFL_NUMOF            (8)`

**Comment by kaspar030** [comment]
Ok, apart from that, we're missing:

- 02.01 run *all* tests on native. CI runs only the simple ones.
- 02.02 run *some* tests != 02.03 on iotlab-m3
- 05.02
- 07.01
- 07.02
- 08

gogogo! ;)

**Comment by kaspar030** [comment]
> @kaspar030, HIL reports are still pointing to a non existing page, see here for example.

That's fixed now, see [master](https://ci.riot-os.org/RIOT-OS/RIOT/master/latest/output.html) or [2018.04-branch](https://ci.riot-os.org/RIOT-OS/RIOT/2018.04-branch/latest/output.html).

**Comment by cladmi** [comment]
For task 2, I added https://github.com/RIOT-OS/RIOT/pull/9007 to enable more `TEST_ON_CI_WHITELIST`.

I re-ran all tests in tests/directory that are supported, with enough memory, and had the 'TEST_ON_CI_WHITELIST' tag (even 'native').
I did run on wsn430-v1_4, iotlab-m3, and iotlab-a8-m3, samr21-xpro, arduino-zero using IoT-LAB.
`wsn430-v1_4` results where the same as before. I have the following errors:


* trickle:
  * arduino-zero
* pkg_cayenne-lpp: https://github.com/RIOT-OS/RIOT/pull/9019
  * iotlab-a8-m3
  * arduino-zero
  * iotlab-m3
  * samr21-xpro
* gnrc_netif: 
  * samr21-xpro https://gist.github.com/cladmi/83301f7af482fbe0fec6b01511e7d301
* libfixmath_unittests: PR incoming
  * iotlab-m3 / samr21-xpro

**Comment by cladmi** [comment]
Yeah I was not precise enough in my report, I wanted to give more details on the other ones, my bad.
Indeed the ones noted before as `Tests fixed on wsn430`, and the `pkg_tiny-asn1` where fixed and backported.
My report should more have been: `micro-ecc` is not merged in master, and none of the `Board gets stuck during test` have been fixed.

**Comment by cladmi** [comment]
The automated scripts for task7 do not work out of the box, I try to find what happens. Something with an expect line.

**Comment by cladmi** [comment]
Problem is that when doing `ifconfig`, addresses are now displayed without the `/prefix_len` (I hacked the script to not expect it)

Also, the test is using `fibroute` in `setFibRoutesInARow`
`shell: command not found: fibroute`.

I see to fix it.

**Comment by cladmi** [comment]
### Task 7.01

I adapted the IOTLABHelper.py script to the new commands and output to make the test work.

```
Successfully pinged with 3 hops
SUCCESS
```

**Comment by cladmi** [comment]
### Task 7.02

Failed with first selected node but worked on the second with the same IOTLABHelper.py changes.

```
Sent successfully with packet loss of 0.0%
Successfully communicated with UDP over 3 hops
SUCCESS
```

**Comment by kYc0o** [comment]
I'm on 8.2

**Comment by kYc0o** [comment]
8.9 done successfully.

**Comment by cladmi** [comment]
Thank all for testing. Please remind me next week if I forget to upstream the changes for task 07.

**Comment by miri64** [comment]
(closing this one, since we are currently testing 2018.07 ;-))
