### ISSUE TITLE
Release 2018.07 - RC1

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/Release-Specs#65]
This issue lists the status of all tests for the [Release Candidate 1 of the 2018.07](https://github.com/RIOT-OS/RIOT/releases/tag/2018.07-RC1) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/01-ci/01-ci.md) @cladmi (Related PR: ~https://github.com/RIOT-OS/RIOT/pull/9644~ ~https://github.com/RIOT-OS/RIOT/pull/9643~ ~https://github.com/RIOT-OS/RIOT/pull/9507~)
  - [ ] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/01-ci/01-ci.md#task-01)  Issues but PR provided. I will re-run the failed tests now that they are backported.
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/01-ci/01-ci.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/01-ci/01-ci.md#task-03)
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/01-ci/01-ci.md#task-04) Increase test timeout ~https://github.com/RIOT-OS/RIOT/pull/9590~
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/02-tests/02-tests.md) @cladmi (Related PR: ~https://github.com/RIOT-OS/RIOT/pull/9637~)
  - [ ] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/02-tests/02-tests.md#task-01)
  - [ ] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/02-tests/02-tests.md#task-02)
  - [ ] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/02-tests/02-tests.md#task-03)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md) @PeterKietzmann
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03)
- [x] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md) @PeterKietzmann
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03)
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04)
  - [x] ([Task #05](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05-experimental) ) @PeterKietzmann
  - [x] ([Task #06](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06-experimental)) @PeterKietzmann
  - [ ] ([Task #07](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07-experimental))
  - [ ] ([Task #08](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08-experimental))
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/05-single-hop-route/05-single-hop-route.md) (Related Issue: ~https://github.com/RIOT-OS/Release-Specs/issues/63~) @jia200x
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/05-single-hop-route/05-single-hop-route.md#task-01) (0% packet loss)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/05-single-hop-route/05-single-hop-route.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/05-single-hop-route/05-single-hop-route.md#task-03)
  - [x] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/05-single-hop-route/05-single-hop-route.md#task-04)
- [x] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/06-single-hop-udp/06-single-hop-udp.md) (Related Issues: https://github.com/RIOT-OS/Release-Specs/issues/53) @jia200x
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/06-single-hop-udp/06-single-hop-udp.md#task-01) (0.2% packet loss)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/06-single-hop-udp/06-single-hop-udp.md#task-02) (0.2% packet loss)
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/07-multi-hop/07-multi-hop.md) (Related ~PR: https://github.com/RIOT-OS/Release-Specs/pull/66~ Issue: https://github.com/RIOT-OS/Release-Specs/issues/54)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/07-multi-hop/07-multi-hop.md#task-01)
  - [x] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/07-multi-hop/07-multi-hop.md#task-02)
  - [ ] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/07-multi-hop/07-multi-hop.md#task-03)
  - [ ] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/07-multi-hop/07-multi-hop.md#task-04)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md)
  - [x] [Task #01](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-01) @PeterKietzmann
  - [ ] [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-02)
  - [x] [Task #03](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-03)
  - [ ] [Task #04](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-04)
  - [ ] [Task #05](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-05)
  - [ ] [Task #06](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-06)
  - [ ] [Task #07](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-07)
  - [ ] [Task #08](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-08)
  - [x] [Task #09](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-09) @PeterKietzmann
  - [ ] [Task #10](https://github.com/RIOT-OS/Release-Specs/blob/5d603752594eb04744ccfb0e57a4ec82f85fc07d/08-interop/08-interop.md#task-10)

**Comment by cladmi** [comment]
I needed to fix some timeouts to run task02, task04. But other than that they work. I will provide PRs here and in RIOT for these.

**Comment by cladmi** [comment]
PR to update the scripts in 01-CI: https://github.com/RIOT-OS/Release-Specs/pull/67

**Comment by kYc0o** [comment]
Contiki test done and successful.

**Comment by cladmi** [comment]
For 01-Ci, It took me a long time to actually make it run on my computer entirely (see the PR https://github.com/RIOT-OS/Release-Specs/pull/67 for updating the test scripts)

I arrived with issue that were already mentioned in the PR to update the docker container to `bionic` https://github.com/RIOT-OS/RIOT/pull/9507 There are PRs for fixing the issues already open.

**Comment by miri64** [comment]
You are still on RC1 for testing? With all the fixes merged, shouldn't you proceed to RC2 by now?

**Comment by cladmi** [comment]
I was only running the automated tests for the moment and fixes are not merged for them. I will do a report for Task 2.

**Comment by cladmi** [comment]
For Task 02 I used the script I wrote for running compilation and tests for one board: https://github.com/RIOT-OS/Release-Specs/pull/68 The results of the tests are stored in https://github.com/cladmi/RIOT_2018_07_tests_results

So I have a summary for more boards than the task requires.
Here is the summary:

### Compilation failed

Compilation was done for 
```
arduino-zero
b-l072z-lrwan1
iotlab-a8-m3
iotlab-m3
native
pba-d-01-kw2x
samr21-xpro
stm32f4discovery
wsn430-v1_3b
wsn430-v1_4
```

* `ccn-lite-relay` failed on computer with an old version of cmake https://github.com/RIOT-OS/RIOT/issues/9064 which is known
   * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/iotlab-m3/examples/ccn-lite-relay/compilation.failed
   * @aabadie it is currently not possible to build `ccn-lite-relay` on IoT-LAB frontends
* `tests/pkg_fatfs_vfs` and `tests/pkg_u8g2` for `wsn430` platforms it is just not compiling for a long time and should be put as not enough memory https://github.com/RIOT-OS/RIOT/pull/9507
  * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/wsn430-v1_3b/tests/pkg_fatfs_vfs/compilation.failed
  * https://github.com/cladmi/RIOT_2018_07_tests_results/tree/master/cladmi-iotlab/wsn430-v1_3b/tests/pkg_u8g2
 * `tests/driver_at` fails with `arm-none-eabi-gcc 8.1.0` which means all other applications look ok with it (at least for `stm32f4discovery` There is a `-Werror=cast-function-type` warning which would need a fix someday
   * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/driver_at/compilation.failed

Tests failed comes in the next one.

**Comment by cladmi** [comment]
### Test failed

Tests where run on the same boards except `wsn430-*` as flashing was broken after two or three flash.

```
arduino-zero
b-l072z-lrwan1
iotlab-a8-m3
iotlab-m3
native
pba-d-01-kw2x
samr21-xpro
stm32f4discovery
```

* `tests/cbor` only succeeded on `native`, which is known to be broken on other.
* `driver_ds1307` test fails on `iotlab-m3`, `iotlab-a8-m3`, `stm32f4discovery`
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/iotlab-m3/tests/driver_ds1307/test.failed (same for `iotlab-a8-m3`)
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/driver_ds1307/test.failed
* `driver_groove_ledbar` which fails for `stm43f4discovery` and `b-l072z-lrwan1`. It crashes where-as it does not on iotlab but just runs through. Maybe it should be more robust.
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/driver_grove_ledbar/test.failed
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jia200x-linuxlaptop/b-l072z-lrwan1/tests/driver_grove_ledbar/test.failed
* `driver_hd4478` has a hardfault on `arduino-zero` but it should require a special setup, so maybe just need to handle errors and say a "test skip" or something
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/arduino-zero/tests/driver_hd44780/test.failed
* `driver_my9221` failed assertion on all boards as nothing is connected
* `gnrc_ipv6_ext` fails on `arduino-zero` and `stm43f4discovery`
    * Hardfault https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/arduino-zero/tests/gnrc_ipv6_ext/test.failed
    * TImeout for `pkt->users: 0` https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/gnrc_ipv6_ext/test.failed
* `gnrc_netif` fails everywhere, it is a test script issue that was known but not yet fixed https://github.com/RIOT-OS/RIOT/pull/9007
* `gnrc_sixlowpan` fails on everything except `native`:
    * `child.expect_exact("tag: 0x1")` failed on `iotlab-m3`, `samr21-xpro` but the test also sometime worked when run on IoT-LAB and not on my computer https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-linuxlaptop/iotlab-m3/tests/gnrc_sixlowpan/test.failed
    * `hardfault` on `b-l072z-lrwan1` https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jia200x-linuxlaptop/b-l072z-lrwan1/tests/gnrc_sixlowpan/test.failed
    * Assertion failed on `stm32f4discovery` and `arduino-zero` https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/gnrc_sixlowpan/test.failed https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/arduino-zero/tests/gnrc_sixlowpan/test.failed
   * Segmentation fault in native https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-linuxlaptop/native/tests/gnrc_sixlowpan/test.failed
* `libfixmath` test is sometime failing, must be a timeout not big enough issue
    * b-l072z-lrwan1
    * iotlab-m3
    * pba-d-01-kw2x
    * samr21-xpro
* `libfixmath_unittests` also failing with a timeout on `b-l072z-lrwan1` also expect timing issue here
* `pkg_fatfs_vfs` it fails on all hardware as it supposed to have a setup step using an `sdcard`
* `ps_schedstatistics` fails with hardfault in cascade for `pba-d-01-kw2x`
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/dpetry-ubuntu16_04_laptop/pba-d-01-kw2x/tests/ps_schedstatistics/test.failed
* `pthread_condition_variable` timeouts for `b-l072z-lrwan1` maybe just a timeout issue
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jia200x-linuxlaptop/b-l072z-lrwan1/tests/pthread_condition_variable/test.failed
* `trickle` test failed with failures found in the test firmware
    *  `iotlab-a8-m3`: https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-iotlab/iotlab-a8-m3/tests/trickle/test.failed
    * `stm32f4discovery`: https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/trickle/test.failed
* `warn_conflict`  failed for `smt43f4discovery` looks related to GCC 8
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/jcarrano-linuxdesktop/stm32f4discovery/tests/warn_conflict/test.failed
* `xtimer_periodic_wakeup` failed for `pba-d-01-kw2x`.
    * https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/dpetry-ubuntu16_04_laptop/pba-d-01-kw2x/tests/xtimer_periodic_wakeup/test.failed

**Comment by miri64** [comment]
> child.expect_exact("tag: 0x1") failed on iotlab-m3, samr21-xpro but the test also sometime worked when run on IoT-LAB and not on my computer https://github.com/cladmi/RIOT_2018_07_tests_results/blob/master/cladmi-linuxlaptop/iotlab-m3/tests/gnrc_sixlowpan/test.failed

due to https://github.com/RIOT-OS/RIOT/pull/9585 this also happens in master.

**Comment by miri64** [comment]
> gnrc_netif fails everywhere, it is a test script issue that was known but not yet fixed RIOT-OS/RIOT#9007

Comments made in RIOT-OS/RIOT#9007 still uphold

**Comment by miri64** [comment]
> gnrc_ipv6_ext fails on arduino-zero and stm43f4discovery

Might also be related that to the fact, that the default interface instead of a dummy interface is used. Both these boards don't have a netdev on board.

**Comment by PeterKietzmann** [comment]
04-single-hop-6lowpan-icmp Task #06 passed with 7% loss. I assume this relates to #7304

**Comment by cladmi** [comment]
@cgundogan may you can take a look at `trickle` errors ? https://github.com/RIOT-OS/Release-Specs/issues/65#issuecomment-408906530

**Comment by miri64** [comment]
Mhh... Rerunning `gnrc_netif` actually reveals a segfault that wasn't there before. I will investigate.

**Comment by cladmi** [comment]
@miri64 I added a PR to enable it in CI to try having it for the release https://github.com/RIOT-OS/RIOT/pull/9669

**Comment by miri64** [comment]
Provided several fixes (I linked them in https://github.com/RIOT-OS/RIOT/pull/9669).

**Comment by cladmi** [comment]
Closing in favor of #69
