### ISSUE TITLE
Release 2018.10 - RC2

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/Release-Specs#81]
This issue lists the status of all tests for the [Release Candidate 2 of the 2018.10](https://github.com/RIOT-OS/RIOT/releases/tag/2018.10-RC2) release.

Specs tested:
- [x] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/01-ci/01-ci.md)
  - [x] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/01-ci/01-ci.md#task-01---compile-test) @jia200x  
  - [x] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/01-ci/01-ci.md#task-02---unittests-on-native) @jia200x
  - [x] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/01-ci/01-ci.md#task-03---unittests-on-native-separated) @jia200x
  - [x] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3) @jia200x
- [x] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/02-tests/02-tests.md)
  - [x] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [x] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [x] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native)
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native)
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour) @jia200x
- [x] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md) (@miri64)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) (1% packet loss)
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) (0% packet loss from both sides)
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03---icmpv6-echo-with-large-payload) (3% packet loss)
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes) (1% packet loss from both sides)
  - [x] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [x] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [x] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee) (3% packet loss arduino-zero => samr21-xpro, 6% packet loss samr21-xpro => arduino-zero)
  - [x] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee-15-minutes) (3% packet loss arduino-zero => samr21-xpro, 1% packet loss samr21-xpro => arduino-zero)
- [x] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/05-single-hop-route/05-single-hop-route.md) @jia200x
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [x] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/06-single-hop-udp/06-single-hop-udp.md) @leandrolanzieri 
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3) ```1% packet loss```
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/7f8f4feb784da1d939720e0e296d6111189aa8d6/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression) ```0.5% packet loss```
- [x] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/07-multi-hop/07-multi-hop.md) @MrKevinWeiss 
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/07-multi-hop/07-multi-hop.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/07-multi-hop/07-multi-hop.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/07-multi-hop/07-multi-hop.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/07-multi-hop/07-multi-hop.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
- [x] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [x] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [x] [Task #03 - ICMPv6 echo between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-03---icmpv6-echo-between-iotlab-m3-and-contiki) (@kYc0o already tested it in RC-1. I will use the same results since nothing changed here)
  - [x] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [x] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [x] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [x] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)
  - [x] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3)
  - [x] [Task #10 - UDP between lwIP and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3)
- [x] [09-coap](https://github.com/RIOT-OS/Release-Specs/pull/77) (Experimental) @kb2ma 
    - [x] `Task #01 - CORD Endpoint`
    - [x] `Task #02 - Confirmable retries`
    - [x] `Task #03 - Block1`
    - [x] `Task #04 - Block2`
    - [x] `Task #05 - Observe registration and notification`
- [x] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [x] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/3d437d115a0e44822058a7bd4c33066af9924a2b/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by jia200x** [comment]
@kb2ma do you have time to re-run the `09-coap` tasks again? :)

**Comment by kb2ma** [comment]
No problem, @jia200x. I'll should get to it by Wednesday morning.

**Comment by jia200x** [comment]
> No problem, @jia200x. I'll should get to it by Wednesday morning.

Awesome! Thank you so much!

**Comment by jia200x** [comment]
waiting for 01/01. Unittests pass in all variants

**Comment by miri64** [comment]
I don't have access to a remote, so 4.5 and 4.6 needs to be done by someone else.

**Comment by jia200x** [comment]
> I don't have access to a remote, so 4.5 and 4.6 needs to be done by someone else.

We can run it here at HAW

**Comment by miri64** [comment]
Nothing interesting to report for task 4.

**Comment by jia200x** [comment]
GNRC - emb6 - lwip triade works as expected in the interop tests

**Comment by kb2ma** [comment]
09-coap works as expected.

**Comment by jia200x** [comment]
Native tests:
```
Failures during test:
- [tests/driver_my9221](tests/driver_my9221/test.failed)
- [tests/pkg_cayenne-lpp](tests/pkg_cayenne-lpp/test.failed)
- [tests/pkg_lora-serialization](tests/pkg_lora-serialization/test.failed)
```

`driver_my9221` is expected to fail on native (it shouldn't run IMO though). `pkg_cayenne-lpp` and `pkg_lora-serialization` fail in GCC8 because of floating point implementation. Not blocking for the release though.

I think we should implement the classic `AssertAlmostEqual` for these tests soon-ish

**Comment by miri64** [comment]
FYI, @bergzand found a serious bug in https://github.com/RIOT-OS/RIOT/pull/10246#issuecomment-436786898. Luckily in its current version https://github.com/RIOT-OS/RIOT/pull/10246 fixes that (though very ugly, but later reversible).

**Comment by jia200x** [comment]
Output of compile test:
```
Errors:

Outcome:
        success: arduino_hello-world, asymcute_mqttsn, bindist, ccn-lite-relay, cord_ep, cord_epsim, default, dtls-echo, emcute_mqttsn, filesystem, gcoap, gnrc_border_router, gnrc_minimal, gnrc_networking, gnrc_networking_mac, gnrc_tftp, hello-world, ipc_pingpong, javascript, lorawan, lua_REPL, lua_basic, nanocoap_server, ndn-ping, nimble_gatt, openthread, posix_sockets, riot_and_cpp, saul, skald_eddystone, skald_ibeacon, timer_periodic_wakeup, bench_msg_pingpong, bench_mutex_pingpong, bench_runtime_coreapis, bench_sched_nop, bench_sizeof_coretypes, bench_thread_flags_pingpong, bench_thread_yield_pingpong, bench_timers, bitarithm_timings, bloom_bytes, board_calliope-mini, board_microbit, buttons, can_trx, cb_mux, cb_mux_bench, conn_can, cortexm_common_ldscript, cpp11_condition_variable, cpp11_mutex, cpp11_thread, cpu_efm32_features, driver_adcxx1c, driver_ads101x, driver_adt7310, driver_adxl345, driver_apa102, driver_at, driver_at30tse75x, driver_at86rf2xx, driver_ata8520e, driver_bh1750, driver_bmp180, driver_bmx055, driver_bmx280, driver_dht, driver_ds1307, driver_ds18, driver_dsp0401, driver_dynamixel, driver_enc28j60, driver_encx24j600, driver_feetech, driver_fxos8700, driver_grove_ledbar, driver_hd44780, driver_hdc1000, driver_hih6130, driver_hts221, driver_ina220, driver_io1_xplained, driver_isl29020, driver_isl29125, driver_jc42, driver_kw2xrf, driver_l3g4200d, driver_lc709203f, driver_lis2dh12, driver_lis3dh, driver_lis3mdl, driver_lpd8808, driver_lps331ap, driver_lsm303dlhc, driver_lsm6dsl, driver_mag3110, driver_mma7660, driver_mma8x5x, driver_mpl3115a2, driver_mpu9150, driver_mq3, driver_my9221, driver_nrf24l01p_lowlevel, driver_nvram_spi, driver_pcd8544, driver_pir, driver_pn532, driver_pulse_counter, driver_rn2xx3, driver_sdcard_spi, driver_servo, driver_sht1x, driver_si114x, driver_si70xx, driver_soft_spi, driver_srf02, driver_srf04, driver_srf08, driver_sx127x, driver_tcs37727, driver_tmp006, driver_tsl2561, driver_tsl4531x, driver_vcnl40x0, driver_veml6070, driver_xbee, eepreg, emb6, events, evtimer_msg, evtimer_underflow, external_module_dirs, fault_handler, float, fmt_print, gnrc_gomach, gnrc_ipv6_ext, gnrc_ipv6_nib_6ln, gnrc_lwmac, gnrc_ndp, gnrc_netif, gnrc_sixlowpan, gnrc_sock_dns, gnrc_sock_ip, gnrc_sock_udp, gnrc_tcp_client, gnrc_tcp_server, gnrc_udp, irq, isr_yield_higher, leds, libc_newlib, libfixmath, libfixmath_unittests, lwip, lwip_sock_ip, lwip_sock_tcp, lwip_sock_udp, malloc, mcuboot, memarray, minimal, mpu_stack_guard, msg_avail, msg_send_receive, msg_try_receive, mutex_order, mutex_unlock_and_sleep, netdev_test, netstats_l2, nhdp, od, periph_adc, periph_cpuid, periph_dac, periph_dma, periph_eeprom, periph_flashpage, periph_gpio, periph_hwrng, periph_i2c, periph_pm, periph_pwm, periph_qdec, periph_rtc, periph_rtt, periph_spi, periph_timer, periph_uart, pipe, pkg_cayenne-lpp, pkg_cmsis-dsp, pkg_fatfs, pkg_fatfs_vfs, pkg_hacl, pkg_heatshrink, pkg_jsmn, pkg_libb2, pkg_libcoap, pkg_libcose, pkg_libhydrogen, pkg_lora-serialization, pkg_micro-ecc, pkg_micro-ecc-with-hwrng, pkg_microcoap, pkg_minmea, pkg_monocypher, pkg_oonf_api, pkg_semtech-loramac, pkg_tiny-asn1, pkg_tinycbor, pkg_tinycrypt, pkg_tweetnacl, pkg_u8g2, pkg_ucglib, pkg_umorse, posix_semaphore, posix_time, ps_schedstatistics, pthread, pthread_barrier, pthread_cleanup, pthread_condition_variable, pthread_cooperation, pthread_rwlock, pthread_tls, puf_sram, rmutex, rng, saul, sched_testing, shell, slip, sntp, socket_zep, ssp, struct_tm_utility, sys_arduino, thread_basic, thread_cooperation, thread_exit, thread_flags, thread_flags_xtimer, thread_flood, thread_msg, thread_msg_block_w_queue, thread_msg_block_wo_queue, thread_msg_seq, thread_priority_inversion, thread_race, trace, trickle, unittests, warn_conflict, xtimer_drift, xtimer_hang, xtimer_longterm, xtimer_msg, xtimer_msg_receive_timeout, xtimer_now64_continuity, xtimer_periodic_wakeup, xtimer_remove, xtimer_reset, xtimer_usleep, xtimer_usleep_short
        failed: gnrc_ipv6_nib
Errors: 0 Warnings: 0
```

The `gnrc_ipv6_nib` example fails to build on `waspmote-pro`. It's the same problem as described in [RIOT-OS/Release-Specs#76 (comment)](https://github.com/RIOT-OS/Release-Specs/issues/76#issuecomment-434270312), and it's solved with RIOT-OS/RIOT#9646. So, no need to worry about it

**Comment by cladmi** [comment]
I ran some `scan-build` to test the new docker images and it reports actual bugs like `(netif == NULL) ? netif->pid : 0);`  for `make -C examples/gnrc_networking scan-build`

I will try running it for the boards supporting llvm and do a report.

**Comment by miri64** [comment]
> I ran some scan-build to test the new docker images and it reports actual bugs like (netif == NULL) ? netif->pid : 0); for make -C examples/gnrc_networking scan-build

I'm doing a fix for the native reports as we speak. @jia200x do we do another release candidate for all those last minute GNRC stuff?

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/10350.

**Comment by jia200x** [comment]
> I'm doing a fix for the native reports as we speak. @jia200x do we do another release candidate for all those last minute GNRC stuff?

Yes. Also for the latest fixes

**Comment by cladmi** [comment]
Unfortunately I did not have time to run and analyze them before the week-end.

**Comment by miri64** [comment]
Who tested 8.6 and 8.7 because the RIOT border router on `samr21-xpro` crashes for me in the current release branch oO

**Comment by jia200x** [comment]
> Who tested 8.6 and 8.7 because the RIOT border router on samr21-xpro crashes for me in the current release branch oO

I tested it. It didn't crash in any of the RC. Let me re-check in any case

**Comment by miri64** [comment]
(It also crashes on RC2, I checked)

**Comment by miri64** [comment]
All-clear: it was the broken samr21-xpro I was using ^^"

**Comment by jia200x** [comment]
Already in RC3
