### ISSUE TITLE
Release 2018.10 - RC3

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/Release-Specs#84]
This issue lists the status of all tests for the [Release Candidate 3 of the 2018.10](https://github.com/RIOT-OS/RIOT/releases/tag/2018.10-RC3) release.

Specs tested:
- [x] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/01-ci/01-ci.md)
  - [x] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/01-ci/01-ci.md#task-01---compile-test)
  - [x] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/01-ci/01-ci.md#task-02---unittests-on-native)
  - [x] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/01-ci/01-ci.md#task-03---unittests-on-native-separated)
  - [x] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3)
- [x] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/02-tests/02-tests.md) @jia200x (running in parallel with `compile_and_test_for_board.py`)
  - [x] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [x] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [x] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [x] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md) @leandrolanzieri
  - [x] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native) `avg. packet loss: 0%`
  - [x] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native) `avg. packet loss: 0%`
  - [x] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour) `packet loss: 0%`
- [x] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md)
  - [x] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01---icmpv6-link-local-echo-with-iotlab-m3) `packet loss: 0%` @leandrolanzieri 
  - [x] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro) `packet loss: 5%`
  - [x] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03---icmpv6-echo-with-large-payload) `packet loss: 1%`
  - [x] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes) `packet loss: 1%`
  - [x] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [x] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [x] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [x] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
- [x] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/05-single-hop-route/05-single-hop-route.md)
  - [x] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route) `0% packet loss`
  - [x] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route) `avg. packet loss: 0.9%`
  - [x] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route) `0% packet loss`
  - [x] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route) `avg. packet loss: 0%`
- [x] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/06-single-hop-udp/06-single-hop-udp.md) (@miri64)
  - [x] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3) 0% packet loss (in lille)
  - [x] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression) 0% packet loss (in lille)
- [x] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/07-multi-hop/07-multi-hop.md) (@MrKevinWeiss)
  - [x] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/07-multi-hop/07-multi-hop.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [x] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/07-multi-hop/07-multi-hop.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [x] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/07-multi-hop/07-multi-hop.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [x] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/07-multi-hop/07-multi-hop.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
- [x] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md)
  - [x] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [x] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [x] [Task #03 - ICMPv6 echo between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-03---icmpv6-echo-between-iotlab-m3-and-contiki) (by @kYc0o in RC1)
  - [x] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [x] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [x] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [x] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [x] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)
  - [x] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3)
  - [x] [Task #10 - UDP between lwIP and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3)
- [x] [09-coap](https://github.com/RIOT-OS/Release-Specs/pull/77) Tests by @kb2ma in RC2
    - [x] `Task #01 - CORD Endpoint`
    - [x] `Task #02 - Confirmable retries`
    - [x] `Task #03 - Block1`
    - [x] `Task #04 - Block2`
    - [x] `Task #05 - Observe registration and notification`
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/a89920e1d9feb078f54aca56deebd9c04d10266c/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by jia200x** [comment]
nothing interesting to report in `samr21-xpro` and `iotlab-m3` tests

**Comment by jia200x** [comment]
For `native`, same results as RC2

**Comment by jia200x** [comment]
nothing interesting to report in the compile test. `gnrv_ipv6_nib` fails on waspmote, but it's fixed with RIOT-OS/RIOT#9646

**Comment by miri64** [comment]
Release is out ;-)
