### ISSUE TITLE
Release 2019.01 - RC1

### ISSUE THREAD

**Issue by aabadie** [RIOT-OS/Release-Specs#92]
This issue lists the status of all tests for the [Release Candidate 1 of the 2019.01](https://github.com/RIOT-OS/RIOT/releases/tag/2019.01-RC1) release.

Specs tested:
- [ ] [01-ci](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/01-ci/01-ci.md)
  - [ ] [Task #01 - Compile test](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/01-ci/01-ci.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/01-ci/01-ci.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/01-ci/01-ci.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/02-tests/02-tests.md)
  - [ ] [Task #01 - All tests on native](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [ ] [Task #01 - ICMPv6 multicast echo on native](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native)
  - [ ] [Task #02 - ICMPv6 link-local echo on native](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native)
  - [ ] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md)
  - [ ] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [ ] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [ ] [Task #03 - ICMPv6 echo with large payload](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03---icmpv6-echo-with-large-payload)
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #09 - ICMPv6 stress test](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-09---icmpv6-stress-test)
- [ ] [05-single-hop-route](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/05-single-hop-route/05-single-hop-route.md)
  - [ ] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [ ] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [ ] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [ ] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [ ] [06-single-hop-udp](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/06-single-hop-udp/06-single-hop-udp.md)
  - [ ] [Task #01 - UDP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3)
  - [ ] [Task #02 - UDP on iotlab-m3 (UDP port compression)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-udp-port-compression)
  - [ ] [Task #03 - UDP on native (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/06-single-hop-udp/06-single-hop-udp.md#task-03---udp-on-native-non-existent-neighbor)
  - [ ] [Task #04 - UDP on iotlab-m3 (non-existent neighbor)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/06-single-hop-udp/06-single-hop-udp.md#task-04---udp-on-iotlab-m3-non-existent-neighbor)
- [ ] [07-multi-hop](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/07-multi-hop/07-multi-hop.md)
  - [ ] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/07-multi-hop/07-multi-hop.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/07-multi-hop/07-multi-hop.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/07-multi-hop/07-multi-hop.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/07-multi-hop/07-multi-hop.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md)
  - [ ] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - ICMPv6 echo between iotlab-m3 and Contiki](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-03---icmpv6-echo-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [ ] [Task #08 - UDP between GNRC and lwIP on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3)
  - [ ] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3)
  - [ ] [Task #10 - UDP between lwIP and emb6 on iotlab-m3](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3)
- [ ] [09-coap](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/09-coap/coap.md)
  - [ ] [Task #01 - CORD Endpoint](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/09-coap/coap.md#task-01---cord-endpoint)
  - [ ] [Task #02 - Confirmable retries](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/09-coap/coap.md#task-02---confirmable-retries)
  - [ ] [Task #03 - Block1](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/09-coap/coap.md#task-03---block1)
  - [ ] [Task #04 - Block2](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/09-coap/coap.md#task-04---block2)
  - [ ] [Task #05 - Observe registration and notification](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/09-coap/coap.md#task-05---observe-registration-and-notification)
- [ ] [10-icmpv6-error](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md)
  - [ ] [Task #01 - Destination unreachable - no route to destination](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-01---destination-unreachable---no-route-to-destination)
  - [ ] [Task #02 - Destination unreachable - Beyond scope of source address](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-02---destination-unreachable---beyond-scope-of-source-address)
  - [ ] [Task #03 - Destination unreachable - address unreachable (target node address)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-03---destination-unreachable---address-unreachable-target-node-address)
  - [ ] [Task #04 - Destination unreachable - address unreachable (neighbor cache miss)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss)
  - [ ] [Task #05 - Destination unreachable - port unreachable](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-05---destination-unreachable---port-unreachable)
  - [ ] [Task #06 - Destination unreachable - port unreachable (large payload)](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-06---destination-unreachable---port-unreachable-large-payload)
  - [ ] [Task #07 - Packet too big](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-07---packet-too-big)
  - [ ] [Task #08 - Time exceeded - hop limit exceeded in transit](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-08---time-exceeded---hop-limit-exceeded-in-transit)
  - [ ] [Task #09 - Parameter problem - erroneous header field encountered](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-09---parameter-problem---erroneous-header-field-encountered)
  - [ ] [Task #10 - IPv6-in-IPv6 encapsulation](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/10-icmpv6-error/10-icmpv6-error.md#task-10---ipv6-in-ipv6-encapsulation)
- [ ] [99-compile-and-test-one-board](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/99-compile-and-test-one-board/99-compile-and-test-one-board.md)
  - [ ] [Task #01 - Run tests on different hardwares](https://github.com/RIOT-OS/Release-Specs/blob/4d4d22e12421dbd026e7086a7ce4d338bdf1dd22/99-compile-and-test-one-board/99-compile-and-test-one-board.md#task-01---run-tests-on-different-hardwares)

**Comment by miri64** [comment]
I started running Task 1.1. Should be done during the weekend.

**Comment by kb2ma** [comment]
09-coap runs fine on native.

**Comment by miri64** [comment]
10-icmpv6-error succeeded, however I found some errors in its testing procedures (fixed in #93) and an unrelated bug in RIOT itself (fixed in https://github.com/RIOT-OS/RIOT/pull/10879).

**Comment by aabadie** [comment]
I ran the automatic python script for tasks 2.2 and tasks 2.3 and got the following tests failing:
- tests/gnrc_ipv6_ext: needs to be root and maybe another setup is required to able to reach the node from the script (ethos, or something)
- tests/gnrc_rpl_srh: same as the first one
- tests/pkg_fatfs_vfs: needs some MTD setup for these boards which is not provided by default.

All other tests succeeded.

**Comment by cgundogan** [comment]
I successfully ran all multi-hop tests (following the description in https://github.com/RIOT-OS/Release-Specs/pull/85, btw)

**Comment by miri64** [comment]
> tests/gnrc_ipv6_ext: needs to be root and maybe another setup is required to able to reach the node from the script (ethos, or something)

You need `scapy` and `ethos` for it. Both require `sudo` (`ethos` because the `start_network.sh` script is a little bit screwed up) and `scapy` because it needs to be able to send Ethernet frames.

**Comment by leandrolanzieri** [comment]
Successfully ran the single-hop-udp tests

**Comment by cgundogan** [comment]
I updated the progress list above, since some of my modifications removed @leandrolanzieri 's checks. We really need to find another way of documenting our progress ..

**Comment by miri64** [comment]
> I started running Task 1.1. Should be done during the weekend.

All but `gnrc_sixlowpan_frag` succeeded

```
        Building application: gnrc_sixlowpan_frag (122/252)
                : acd52832 ... success., airfy-beacon ... success., arduino-due ... success., arduino-duemilanove ... success., arduino-mega2560 ... success., arduino-mkr1000 ... success., arduino-mkrfox1200 ... success., arduino-mkrzero ... success., arduino-uno ... success., arduino-zero ... success., avsextrem ... success., b-l072z-lrwan1 ... success., b-l475e-iot01a ... success., blackpill ... success., bluepill ... success., calliope-mini ... success., cc2538dk ... success., cc2650-launchpad ... success., cc2650stk ... success., chronos ... failed!, ek-lm4f120xl ... success., esp32-mh-et-live-minikit ... success., esp32-olimex-evb ... success., esp32-wemos-lolin-d32-pro ... success., esp32-wroom-32 ... success., esp32-wrover-kit ... success., esp8266-esp-12x ... success., esp8266-olimex-mod ... success., esp8266-sparkfun-thing ... success., f4vi1 ... success., feather-m0 ... success., firefly ... success., fox ... success., frdm-k22f ... success., frdm-k64f ... success., frdm-kw41z ... success., hifive1 ... success., ikea-tradfri ... success., iotlab-a8-m3 ... success., iotlab-m3 ... success., jiminy-mega256rfr2 ... success., limifrog-v1 ... success., lobaro-lorabox ... success., maple-mini ... success., mbed_lpc1768 ... success., mega-xplained ... success., microbit ... success., mips-malta ... success., msb-430 ... failed!, msb-430h ... failed!, msba2 ... success., msbiot ... success., mulle ... success., native ... success., nrf51dk ... success., nrf51dongle ... success., nrf52840-mdk ... success., nrf52840dk ... success., nrf52dk ... success., nrf6310 ... success., nucleo-f030r8 ... success., nucleo-f031k6 ... success., nucleo-f042k6 ... success., nucleo-f070rb ... success., nucleo-f072rb ... success., nucleo-f091rc ... success., nucleo-f103rb ... success., nucleo-f207zg ... success., nucleo-f302r8 ... success., nucleo-f303k8 ... success., nucleo-f303re ... success., nucleo-f303ze ... success., nucleo-f334r8 ... success., nucleo-f401re ... success., nucleo-f410rb ... success., nucleo-f411re ... success., nucleo-f412zg ... success., nucleo-f413zh ... success., nucleo-f429zi ... success., nucleo-f446re ... success., nucleo-f446ze ... success., nucleo-f722ze ... success., nucleo-f746zg ... success., nucleo-f767zi ... success., nucleo-l031k6 ... success., nucleo-l053r8 ... success., nucleo-l073rz ... success., nucleo-l152re ... success., nucleo-l432kc ... success., nucleo-l433rc ... success., nucleo-l452re ... success., nucleo-l476rg ... success., nucleo-l496zg ... success., nz32-sc151 ... success., opencm904 ... success., openmote-b ... success., openmote-cc2538 ... success., pba-d-01-kw2x ... success., phynode-kw41z ... success., pic32-clicker ... success., pic32-wifire ... success., remote-pa ... success., remote-reva ... success., remote-revb ... success., ruuvitag ... success., samd21-xpro ... success., saml10-xpro ... success., saml11-xpro ... success., saml21-xpro ... success., samr21-xpro ... success., samr30-xpro ... success., seeeduino_arch-pro ... success., sensebox_samd21 ... success., slstk3401a ... success., slstk3402a ... success., sltb001a ... success., slwstk6000b ... success., slwstk6220a ... success., sodaq-autonomo ... success., sodaq-explorer ... success., sodaq-one ... success., sodaq-sara-aff ... success., spark-core ... success., stk3600 ... success., stk3700 ... success., stm32f0discovery ... success., stm32f3discovery ... success., stm32f429i-disc1 ... success., stm32f4discovery ... success., stm32f769i-disco ... success., stm32l476g-disco ... success., teensy31 ... success., telosb ... failed!, thingy52 ... success., ublox-c030-u201 ... success., udoo ... success., usb-kw41z ... success., waspmote-pro ... success., wsn430-v1_3b ... failed!, wsn430-v1_4 ... failed!, yunjia-nrf51822 ... success., z1 ... failed!
                make buildtest error!
```

Will investigate what's wrong.

**Comment by miri64** [comment]
> > I started running Task 1.1. Should be done during the weekend.
> 
> All but `gnrc_sixlowpan_frag` succeeded
> 
> ```
>         Building application: gnrc_sixlowpan_frag (122/252)
>                 : acd52832 ... success., airfy-beacon ... success., arduino-due ... success., arduino-duemilanove ... success., arduino-mega2560 ... success., arduino-mkr1000 ... success., arduino-mkrfox1200 ... success., arduino-mkrzero ... success., arduino-uno ... success., arduino-zero ... success., avsextrem ... success., b-l072z-lrwan1 ... success., b-l475e-iot01a ... success., blackpill ... success., bluepill ... success., calliope-mini ... success., cc2538dk ... success., cc2650-launchpad ... success., cc2650stk ... success., chronos ... failed!, ek-lm4f120xl ... success., esp32-mh-et-live-minikit ... success., esp32-olimex-evb ... success., esp32-wemos-lolin-d32-pro ... success., esp32-wroom-32 ... success., esp32-wrover-kit ... success., esp8266-esp-12x ... success., esp8266-olimex-mod ... success., esp8266-sparkfun-thing ... success., f4vi1 ... success., feather-m0 ... success., firefly ... success., fox ... success., frdm-k22f ... success., frdm-k64f ... success., frdm-kw41z ... success., hifive1 ... success., ikea-tradfri ... success., iotlab-a8-m3 ... success., iotlab-m3 ... success., jiminy-mega256rfr2 ... success., limifrog-v1 ... success., lobaro-lorabox ... success., maple-mini ... success., mbed_lpc1768 ... success., mega-xplained ... success., microbit ... success., mips-malta ... success., msb-430 ... failed!, msb-430h ... failed!, msba2 ... success., msbiot ... success., mulle ... success., native ... success., nrf51dk ... success., nrf51dongle ... success., nrf52840-mdk ... success., nrf52840dk ... success., nrf52dk ... success., nrf6310 ... success., nucleo-f030r8 ... success., nucleo-f031k6 ... success., nucleo-f042k6 ... success., nucleo-f070rb ... success., nucleo-f072rb ... success., nucleo-f091rc ... success., nucleo-f103rb ... success., nucleo-f207zg ... success., nucleo-f302r8 ... success., nucleo-f303k8 ... success., nucleo-f303re ... success., nucleo-f303ze ... success., nucleo-f334r8 ... success., nucleo-f401re ... success., nucleo-f410rb ... success., nucleo-f411re ... success., nucleo-f412zg ... success., nucleo-f413zh ... success., nucleo-f429zi ... success., nucleo-f446re ... success., nucleo-f446ze ... success., nucleo-f722ze ... success., nucleo-f746zg ... success., nucleo-f767zi ... success., nucleo-l031k6 ... success., nucleo-l053r8 ... success., nucleo-l073rz ... success., nucleo-l152re ... success., nucleo-l432kc ... success., nucleo-l433rc ... success., nucleo-l452re ... success., nucleo-l476rg ... success., nucleo-l496zg ... success., nz32-sc151 ... success., opencm904 ... success., openmote-b ... success., openmote-cc2538 ... success., pba-d-01-kw2x ... success., phynode-kw41z ... success., pic32-clicker ... success., pic32-wifire ... success., remote-pa ... success., remote-reva ... success., remote-revb ... success., ruuvitag ... success., samd21-xpro ... success., saml10-xpro ... success., saml11-xpro ... success., saml21-xpro ... success., samr21-xpro ... success., samr30-xpro ... success., seeeduino_arch-pro ... success., sensebox_samd21 ... success., slstk3401a ... success., slstk3402a ... success., sltb001a ... success., slwstk6000b ... success., slwstk6220a ... success., sodaq-autonomo ... success., sodaq-explorer ... success., sodaq-one ... success., sodaq-sara-aff ... success., spark-core ... success., stk3600 ... success., stk3700 ... success., stm32f0discovery ... success., stm32f3discovery ... success., stm32f429i-disc1 ... success., stm32f4discovery ... success., stm32f769i-disco ... success., stm32l476g-disco ... success., teensy31 ... success., telosb ... failed!, thingy52 ... success., ublox-c030-u201 ... success., udoo ... success., usb-kw41z ... success., waspmote-pro ... success., wsn430-v1_3b ... failed!, wsn430-v1_4 ... failed!, yunjia-nrf51822 ... success., z1 ... failed!
>                 make buildtest error!
> ```
> Will investigate what's wrong.

Ok, the application gets too large for MSP430 platforms on my machine, but on Murdock it is small enough (see [build](https://ci.riot-os.org/RIOT-OS/RIOT/10886/7d966d34dd722acf60034078e5da39499aa0de6a/output.html) of https://github.com/RIOT-OS/RIOT/pull/10886 e.g.), so not really a problem.

**Comment by miri64** [comment]
> We really need to find another way of documenting our progress ..

Maybe a reusable project could help with that?

**Comment by aabadie** [comment]
Task 4.4 is failing, packet loss is above 10%

**Comment by cgundogan** [comment]
>2019-01-28 18:47:48,865 - INFO # --- fe80::1711:6b10:65fa:a932 ping statistics ---
2019-01-28 18:47:48,871 - INFO # 10000 packets transmitted, 9991 received, 1% packet loss, time 1313.06522340 s
2019-01-28 18:47:48,874 - INFO # rtt min/avg/max = 17.590/22.397/46.515 ms

@aabadie this is what I get with a local setup. Maybe you have some interferences on channel 26 at your site?

**Comment by aabadie** [comment]
> Maybe you have some interferences on channel 26 at your site?

Maybe yes, I'll rerun the tests on another channel.

**Comment by miri64** [comment]
I redid 10.07 with https://github.com/RIOT-OS/Release-Specs/pull/96 included. Still passes.

**Comment by aabadie** [comment]
>  I'll rerun the tests on another channel.

They are passing ~5% packet loss.

**Comment by aabadie** [comment]
Tasks 05 are passing. I also ran tasks 04 (except 04.05 and 04.06 because I don't have the hardware) with success.

**Comment by aabadie** [comment]
Also completed tasks 1.3 and 1.4 with success.

**Comment by jia200x** [comment]
tasks 05, 06 and 07 from 08.interop run OK

**Comment by jia200x** [comment]
Interop tests between GNRC, emb6 and lwip pass

**Comment by aabadie** [comment]
I ran 99 on nrf52dk, samr21-xpro and iotlab-m3 and got the same results as reported in https://github.com/RIOT-OS/Release-Specs/issues/92#issuecomment-457928353

**Comment by aabadie** [comment]
Is there someone who could test 4.5, 4.6, 8.3 and 8.4 ? After that, we are ready for the RC2

**Comment by miri64** [comment]
Nothing unexpected to report for 8.4.

**Comment by miri64** [comment]
I finally was able to do 8.3. I based it on @kYc0o comment here https://github.com/RIOT-OS/Release-Specs/issues/58#issuecomment-361926531. It was still not that straightforward. I will try to update the specs and test descriptions.
